### ISSUE TITLE
Allow to override pip version for pipenv users

### ISSUE THREAD

**Issue by vityas** [heroku/heroku-buildpack-python#1093]
## question
Assuming that we don't want to build a new buildpack, is there a workaround for pipenv users to be able to install packages that require a newer pip? unpin and override pip.

## reason
A common example of a package that will fail to install is `tensorflow>=2.0`

## side question
I doubt any developers keep using `pip==9.0.2`. It seems like the main and only reason to pin 9.0.2 is that (https://github.com/heroku/heroku-buildpack-python/issues/786) 

it "would require users to uninstall and reinstall their local pipenv environments"

 Not sure how some one-time inconvenience can outweigh the need to have the same environment. which simply not possible with the old pip.

## example PR
see the attached PR. I created it as an example. It might not be the best solution, I would love to see some workarounds.

**Comment by edmorley** [comment]
Hi! I've left a comment on the PR:
https://github.com/heroku/heroku-buildpack-python/pull/1094#pullrequestreview-506483377

**Comment by timmygee** [comment]
Just flagging that the legend @alan-eu has created a fork that does exactly this

https://github.com/alan-eu/heroku-buildpack-python

**Comment by edmorley** [comment]
Hi! The pipenv version has just been updated in #1169.

I'm closing this out since adding env var support for pipenv/pip is something that I believe will introduce more issues than it fixes for the reasons mentioned in:
https://github.com/heroku/heroku-buildpack-python/pull/1094#issuecomment-778201602

However thank you for suggesting this change, and please do open issues for any other ideas you may have :-)

**Comment by timmygee** [comment]
To you decision to not support this, I respectfully object. Complex Django applications such as my own, rely on dependency resolution as provided by `Pipenv.lock`. It also requires the python [cryptography](https://github.com/pyca/cryptography) module, which itself requires a recent version of pip to actually build and install. pip version 9 does not cut it. The fact that this buildpack only provides pip version 9 for projects built out with pipenv, when the latest version of pip is version 20+, is not great.

I'd switch to poetry, which seems to be preferred over pipenv these days but that's not supported by this buildpack at all.

I can now literally only get my project deployed using @alan-eu's forked version of this buildpack.

I know I'm not the only one who has this problem. Anyone who uses pipenv and packages that require a modern version of pip will also have this issue. Please support the python community when it comes to this.

**Comment by tolomea** [comment]
@timmygee The pull @edmorley linked updates both Pip and Pipenv to current versions.

**Comment by timmygee** [comment]
Right! Thanks @tolomea. That wasn't clear.

That also solves my problem just fine. Thank you @edmorley for doing this!

**Comment by edmorley** [comment]
No problem! I'm going to try and keep pipenv more up to date moving forwards (and hope to never have to pin it to an older pip again!).
