### ISSUE TITLE
API to query currently supported Python runtimes

### ISSUE THREAD

**Issue by zyv** [heroku/heroku-buildpack-python#1181]
Hi @edmorley ,

We are thinking about supporting version specifications for runtimes in our buildpack (see moneymeets/python-poetry-buildpack#6 for the background if you're interested).

Is there a public Heroku API to find out which runtimes are currently supported? The best sources I could find so far are:

* https://devcenter.heroku.com/articles/python-support#supported-runtimes (HTML page)
* https://raw.githubusercontent.com/heroku/heroku-buildpack-python/main/README.md (Markdown file, unclear whether `main` branch = guaranteed currently deployed @ Heroku)

Obviously, parsing HTML or Markdown from script is no fun. Is there an API or at least a plain text file in specified format that one can download somewhere which is guaranteed to have the same list as on Heroku Dev Center?

Thanks!

**Comment by zyv** [comment]
P.S. Of course ideally the endpoint should be able to optionally return all available versions, not only currently supported ones, or return everything, but mark specific versions as currently supported.

**Comment by edmorley** [comment]
@zyv Hi! There is not a public API - the files are just uploaded to S3.

I think the best way to solve this is to fix #913, that way moneymeets/python-poetry-buildpack could just write eg `python-3.9` into `runtime.txt`, which would automatically use the latest supported release of that major version.

**Comment by edmorley** [comment]
One advantage of the #913 approach would be that the resultant Python version would be deterministic for the buildpack release. That is, pinning to an older buildpack would give a consistent Python version, even when future Python releases are performed. Using an API would mean the Python version would change even when pinned to an older buildpack release.

**Comment by edmorley** [comment]
Closing in favour of #913. In the meantime you can pull/parse this file:
https://raw.githubusercontent.com/heroku/heroku-buildpack-python/main/bin/default_pythons
