### ISSUE TITLE
Cannot Deploy due to slug oversize

### ISSUE THREAD

**Issue by Sagnik220** [heroku/heroku-buildpack-python#1202]
I am using Tensorflow 2.5.0rc2 which is approximately 450mb itself the total slug size is going over 600mb, would be helpful if anyone can give me some alternative methods by which I can deploy

**Comment by edmorley** [comment]
Hi! Sorry for the delayed reply - the GitHub issues here aren't as actively monitored as support tickets. For issues like this I would recommend filing a support ticket via:
https://help.heroku.com/

In the meantime, I would check out this guide to reducing slug size:
https://help.heroku.com/KUFMEES1/my-slug-size-is-too-large-how-can-i-make-it-smaller

Failing that, the support team can bump the slug limit slightly for individual apps if required (though be aware a larger slug size means a slower app boot time, so in general it's best to try and optimise the slug size as much as possible first).
