### ISSUE TITLE
How to make it "play nice" with versioneer?

### ISSUE THREAD

**Issue by yarikoptic** [heroku/heroku-buildpack-python#1222]
https://github.com/python-versioneer/python-versioneer/ automates establishing version for any python project based on git state and available tags, and it is quite popular (at least outside of python web dev world).  If python package is `sdist`ed, then it replaces `<packagename>/_version.py` (which has all the logic for figuring out based on git) with a small file containing only versioning information based on `git describe` etc.  But that file is not populated/replaced in `develop` mode of installation (`pip install -e .`), which is (if I got it right ) the mode this buildpack relies on.

Unfortunately for our https://github.com/dandi/dandi-api , due to aforementioned need for `-e .`, as a result, we do not have version information in the "deployed" instance (ref https://github.com/dandi/dandi-api/issues/222) (well, staging is deployed straight by heroku, while for release deployment we use https://github.com/akhileshns/heroku-deploy).

I wonder if you see some quick obvious way to mitigate it?  e.g. could be something like running such a command

```
python3 setup.py build && cp build/lib/<PACKAGE>/_version.py <PACKAGE>/ 
```

before bundling/cp-ing the `<PACKAGE>` for deployment. Is there some mechanism to trigger running such a command via local to the repo, but specific to heroky, configuration etc?

I guess I could figure out how to patch our "installed copy" of https://github.com/dandi/dandi-api/blob/master/versioneer.py but that would be suboptimal since then during "upgrade of this installed copy" we would obliterate that ad-hoc patch.

attn @dchiquito

**Comment by edmorley** [comment]
Hi! I'm not sure I follow how this is an issue with this buildpack? This buildpack does not rely upon develop mode - in general use of requirements.txt with explicit dependencies is recommended (rather than the fallback that does `-e .` if no requirements.txt is found) - and whilst some people do choose to install their project as a package, that approach is not required or recommended.

For an example Python project layout that doesn't require installing your project as a package, see:
https://github.com/heroku/python-getting-started

**Comment by yarikoptic** [comment]
> rather than the fallback that does `-e .` if no requirements.txt is found

hm, I wonder if that is what mislead me/other engineers to have `-e .` added to requirements.txt .  Looking at https://github.com/heroku/heroku-buildpack-python/blob/main/bin/compile#L299 indeed code is copied only if was not "properly" installed (e.g. as if development mode was used.)  I will check  and reopen if I have more/the same question (how to run an arbitrary extra command before/after pip-install)

**Comment by edmorley** [comment]
I agree that is probably what causes confusion with users - I've been contemplating removing the fallback for a while - I think this is another reason to do so! Thank you for making me aware of it :-)
