### ISSUE TITLE
Should I have `requirements.txt` when using pipenv?

### ISSUE THREAD

**Issue by ibozhilov** [heroku/heroku-buildpack-python#1270]
I have a python project and store the dependencies in Pipfile.lock. Obviously the buildpack understands the Pipfile.lock as it installs the dependencies and everything works okay. As a result I do not use my requirements.txt file. Once I removed it, the build continued to work as expected, however now there is an error thrown:

```
cp: cannot stat '/tmp/build_a123c0456/requirements.txt': No such file or directory
```

Is that the expected behavior and should I have a requirements.txt file? If so, what should be it's content?

**Comment by edmorley** [comment]
Hi! It's a known bug in the buildpack that that error occurs when using Pipenv support. Fixing it will require a refactor of the buildpack, however the buildpack is due to be replaced by a CNB version in the future, so it's unlikely that will happen for the old version until it's replaced.

**Comment by astrojuanlu** [comment]
Is there a place where we can subscribe for progress in the migration to Cloud Native Buildpacks?

**Comment by edmorley** [comment]
https://github.com/heroku/heroku-buildpack-python/issues/796#issuecomment-1031512600
