### ISSUE TITLE
Not able to use punkt in heroku

### ISSUE THREAD

**Issue by hariprasath28AI** [heroku/heroku-buildpack-python#1317]
LookupError: ********************************************************************** Resource [93mstopwords[0m not found. Please use the NLTK Downloader to obtain the resource: [31m>>> import nltk >>> nltk.download('stopwords') [0m For more information see: https://www.nltk.org/data.html Attempted to load [93mcorpora/stopwords[0m Searched in: - '/app/.heroku/python/nltk_data' - '/app/nltk_data' - '/app/.heroku/python/nltk_data' - '/app/.heroku/python/share/nltk_data' - '/app/.heroku/python/lib/nltk_data' - '/usr/share/nltk_data' - '/usr/local/share/nltk_data' - '/usr/lib/nltk_data' - '/usr/local/lib/nltk_data'

**Comment by edmorley** [comment]
Hi! For support issues (since this isn't a fully-formed bug report), please file a support ticket at:
https://help.heroku.com/
