### ISSUE TITLE
PYPY36 and PYPY27 is not available for stack (heroku-22)

### ISSUE THREAD

**Issue by Lungsang-bod** [heroku/heroku-buildpack-python#1337]
Run time pypy36 or pypy27 isn't available for stack-22. Can you please make it available. When trying to deploy an app on heroku with OS Ubuntu-22.04 this issue comes ``` Requested runtime (PYPY36) is not available for this stack (heroku-22).```
Thank you :)

**Comment by Lungsang-bod** [comment]
Thank you for your recommended solutions. I will follow up with them.

**Comment by edmorley** [comment]
You're welcome!
