### ISSUE TITLE
Python 3.10.5 buildpack run results in "error while loading shared libraries: libpython3.10.so.1.0"

### ISSUE THREAD

**Issue by djm** [heroku/heroku-buildpack-python#1339]
Hi.

We're seeing errors installing our stack on Python `3.10.5` only.

This is after clearing all build caches with `heroku builds:cache:purge`.

```
[snip - successful pip install]

python: error while loading shared libraries: libpython3.10.so.1.0: cannot open shared object file: No such file or directory
python: error while loading shared libraries: libpython3.10.so.1.0: cannot open shared object file: No such file or directory

[snip - collectstatic would be here but doesn't get reached]

-----> Running post-compile hook

```

This works fully on `3.10.4` with no output between the successful pip install and the Django collectstatic run.

We suspect the issue lies [somewhere around here](https://github.com/heroku/heroku-buildpack-python/blob/b70427bd26943e6c5128d74bd891e4b1cd8173f3/bin/utils#L105) but have not confirmed that.

Thanks.

**Comment by edmorley** [comment]
@djm Hi!

The Python 3.10.5 release on Heroku was the first for Heroku-{18,20} that has the Python binary built using the shared library. (For Heroku-22, the change was first introduced in Python 3.10.4.). The [Heroku changelog site entry](https://devcenter.heroku.com/changelog-items/2424) for that release links to the [buildpack changelog](https://github.com/heroku/heroku-buildpack-python/blob/main/CHANGELOG.md#v211-2022-05-17) which has some more details about those changes.

My guess would be that perhaps some environment variables are set (either on the app, or via earlier faulty buildpacks) that are interfering with the `python` binary's ability to locate the shared library. For example, `LD_LIBRARY_PATH` or similar.

Could you open a support ticket at https://help.heroku.com, making sure to grant access to your app, and then link to it here, so I can take a closer look?

**Comment by djm** [comment]
@edmorley

Spot on! `PYTHONPATH`, `PATH`, `LD_LIBRARY_PATH` & `LIBRARY_PATH` were all set which was a surprise to me having never done that myself. We've moved all environments back to relying on Heroku for those values.


Thanks very much Ed; I'll close this and hopefully it'll be helpful to someone else.

**Comment by djm** [comment]
@edmorley 

Absolutely, but please take them with a pinch of salt; this particular app has been on Heroku since 2012!

```
LD_LIBRARY_PATH: /app/.heroku/vendor/lib
LIBRARY_PATH: /app/.heroku/vendor/lib
PATH: /app/.heroku/venv/bin:/bin:/usr/local/bin:/usr/bin
PYTHONPATH: /app/
```

**Comment by edmorley** [comment]
Thank you - that was helpful - I tracked those down to here:
https://github.com/heroku/heroku-buildpack-python/blob/v11/bin/release#L10-L18

In the very early days of this buildpack, it used to set some default env vars on newly created apps as part of their first build. I'll have a think about the best way to catch these cases to avoid other old apps being affected in the future.

**Comment by djm** [comment]
That checks out! Thanks for the explanation and all the work on the Python buildpack 👍
