### ISSUE TITLE
Popular cryptography library PyNaCl doesn't install.

### ISSUE THREAD

**Issue by fletom** [heroku/heroku-buildpack-python#142]
If you add the package `PyNaCl` to your requirements and push to Heroku, the build fails.

```
distutils.errors.DistutilsError: Setup script exited with error: command 'gcc' failed with exit status 1
```

**Comment by lincolnq** [comment]
If anyone is Googling and hitting this problem as of now, the solution is to add both PyNaCl and cffi to your requirements file -- you don't need any buildpack hackery anymore. Heroku's default Python buildpack knows how to install libffi but only if cffi is explicitly mentioned! (https://coderanger.net/heroku-cffi/)

**Comment by edmorley** [comment]
I've opened #296 to avoid the need for explicitly including cffi in the requirements file.

That said IMO people should really start pinning all deps as a matter of default, particularly given the benefits of pip v8's new require-hashes mode. For a not-too-painful workflow, see the suggestions in http://www.kennethreitz.org/essays/a-better-pip-workflow
