### ISSUE TITLE
 Could not install packages due to an EnvironmentError:  Could not find a suitable TLS CA certificate bundle,

### ISSUE THREAD

**Issue by metinjakupi** [heroku/heroku-buildpack-python#1484]
Could not find a suitable TLS CA certificate bundle, invalid path: .heroku/python/lib/python3.7/ensurepip/_bundled/pip-10.0.1-py2.py3-none-any.whl/pip/_vendor/certifi/cacert.pem

**Comment by edmorley** [comment]
@metinjakupi Please could you post the full build log? The error would suggest the build was using a very old (and unsupported) Python 3.7 version, however, such old versions are not available on supported Heroku stacks, so something strange must be going on (is this being run outside of Heroku?).

**Comment by metinjakupi** [comment]
@edmorley, I've been deploying applications on DigitalOcean's App Platform for the past couple of weeks without any issues. However, starting this week, I've been encountering challenges and can't successfully deploy anymore. 
Here is my build log:

<img width="1903" alt="Screenshot 2023-09-11 at 14 17 08" src="https://github.com/heroku/heroku-buildpack-python/assets/32740979/955e3b00-35d7-42d4-8015-ddf418ecb948">

Could you assist me in resolving this? Thank you.
