### ISSUE TITLE
zstd not found so buildpack fails

### ISSUE THREAD

**Issue by abulka** [heroku/heroku-buildpack-python#1611]
The [change](https://github.com/heroku/heroku-buildpack-python/commit/2c35ea401c205f5567d9b862f039f5c22bbcad7c) to using zstd instead of gzip means my dokku pushes are now failing due to the missing `zstd` command. Installing `zstd` with

```
apt install zstd
```

does not help. I am still on ubuntu 18.04.

**Comment by abulka** [comment]
I worked around this by specifying an older version of the buildpack (version 248) in a `.buildpacks` file in my project directory:

    https://github.com/heroku/heroku-buildpack-python.git#v248

**Comment by edmorley** [comment]
@abulka Hi! 

This is expected. The Heroku-18 stack is based upon Ubuntu 18.04 LTS which is EOL no longer receiving security updates and so is insecure to use. As such, the Heroku platform and its buildpacks have not supported Heroku-18 for over a year:
https://help.heroku.com/X5OE6BCA/heroku-18-end-of-life-faq
https://devcenter.heroku.com/changelog-items/2583

If Heroku-18 has happened to continue to work via third-party solutions like Dokku that's purely by luck. Once Heroku itself no longer supports a stack version, buildpacks drop support soon after, and in some cases older binaries are cleaned up from S3 meaning pinning to an old buildpack version often won't help either.

Please update to a newer [herokuish](https://github.com/gliderlabs/herokuish) version based on a newer Heroku stack version. 

Exactly how this is done is something I'm not familiar with - I would check the Dokku documentation:
https://dokku.com/docs/getting-started/upgrading/

**Comment by edmorley** [comment]
@josegonzalez Hi! I was wondering if you had any ideas for things Dokku and/or herokuish could do to make it harder for users to use an EOL Heroku stack (which is likely not going to work) and then think it's a supported workflow? For example Dokku warning or blocking use of EOL stack versions, Dokku docs changes, Dokku warnings if running an old Dokku version etc?

**Comment by abulka** [comment]
@edmorley Thanks for the informative explanation on Heroku-18's end-of-life and the importance of updating to a newer Heroku/Dokku stack version.

Where there is an infrastructure of complex, not easily understood Ubuntu 18.04 dokku deployments being used by thousands of users and limited IT resources, an upgrade is an expensive and risky undertaking.  We rely on pushing software updates - having older python buildpacks being disallowed would be damaging. I know we should upgrade our servers etc. but the reality of budgets and circumstances unfortunately say otherwise. More abstractly: most package management systems always allow older versions of software to be installed - deliberately preventing this doesn't sit comfortably - though I appreciate Heroku has to prioritise its own business interests as it sees fit. Maybe someone has a fork of the python buildpack repository that is better suited for older Ubuntu version use.

**Comment by josegonzalez** [comment]
Honestly this is also not supported by Dokku, hasn't been for a while, and users should upgrade.  The herokuish support in Dokku even changed a bit recently so the images won't even be compatible with newer Dokku due to how we setup user permissions now.

I don't know if there is a good way other than building the EOL into a label and looking to see if that label exists/parsing it out, but then someone "enterprising" would just strip the label.

The alternative here is for the python buildpack to do whatever the PHP buildpack does when they invalidate older versions of the buildpack. I routinely find that pinning the PHP buildpack causes issues downloading newer versions of dependencies, so its best to just let that buildpack float.
