### ISSUE TITLE
PEP 761: Deprecating PGP signatures

### ISSUE THREAD

**Issue by sethmlarson** [heroku/heroku-buildpack-python#1660]
Hello, I noticed this project uses PGP signatures and wanted to make you all aware of [my proposed PEP](https://peps.python.org/pep-0761/) for deprecating PGP signatures in future Python versions. Please take a look and leave questions in the [discussion thread](https://discuss.python.org/t/pep-761-deprecating-pgp-signatures-for-cpython-artifacts/67180).

**Comment by edmorley** [comment]
Hi Seth! 

Thank you for reaching out - I've left a comment on the PEP discussion:
https://discuss.python.org/t/pep-761-deprecating-pgp-signatures-for-cpython-artifacts/67180/29

**Comment by sethmlarson** [comment]
Thanks again for the feedback, I'll close this issue now :)

**Comment by edmorley** [comment]
No problem - thanks again for letting us know!
