### ISSUE TITLE
buildpack compatible with centos

### ISSUE THREAD

**Issue by markbarks** [heroku/heroku-buildpack-python#169]
I've been trying to run the buildpack in a centos docker container, however each time the pip install line is called I get errors about missing security library files. 

```
bash-4.1# /app/.heroku/python/bin/pip install -r requirements.txt --exists-action=w --src=./.heroku/src --allow-all-external
ERROR:root:code for hash md5 was not found.
Traceback (most recent call last):
  File "/app/.heroku/python/lib/python2.7/hashlib.py", line 139, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/app/.heroku/python/lib/python2.7/hashlib.py", line 91, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type md5
ERROR:root:code for hash sha1 was not found.
```

OpenSSL is installed correctly in the image:

```
bash-4.1# openssl
OpenSSL>
```

I have tried hacking the LD_LIBRARY_PATH into the script, to no avail. Any clues what I could be doing wrong? Is there a better place to ask for advice rather than raising issues?

Many thanks,
Mark

**Comment by kennethreitz** [comment]
This is out of scope.

**Comment by beechnut** [comment]
I was getting [the same error](https://gist.github.com/beechnut/686d58aa8b65d50bae02) deploying to Dokku using v33, but using the latest version of the buildpack (as of 22 Apr 2015) appears to resolve it.
