### ISSUE TITLE
No more tests

### ISSUE THREAD

**Issue by dulaccc** [heroku/heroku-buildpack-python#173]
Just wondering why [you've removed all the tests](https://github.com/heroku/heroku-buildpack-python/commit/d3f83517448ab073334a97e28c823ae3955f312b) ? I'm kind of missing them.

Cheers

**Comment by kennethreitz** [comment]
Removed to simply the codebase — they didn't actually accomplish much as they were, and were causing some problems.

**Comment by dulaccc** [comment]
thanks for the precision :)
