### ISSUE TITLE
Strip whitespace in the runtime.txt file

### ISSUE THREAD

**Issue by d0ugal** [heroku/heroku-buildpack-python#186]
Any extra whitespace will cause the build to fail. This issue came up at the Djangogirls Edinburgh workshop and caused confusion for a while.

**Comment by cclauss** [comment]
from: http://stackoverflow.com/questions/4109589/remove-all-whitespaces-in-a-file-linux

tr -d ' \t\n\r\f' <runtime.txt >runtime.txt  # ???

**Comment by d0ugal** [comment]
These options look reasonable. @kennethreitz thoughts?

**Comment by kennethreitz** [comment]
Going to leave the current implementation as-is for now. This would be a lot easier if the buildpack was written in Python :)
