### ISSUE TITLE
Bundled sqlite3-3.7.9 is not compatible with Ubuntu 14.04's GDAL

### ISSUE THREAD

**Issue by sebasmagri** [heroku/heroku-buildpack-python#190]
I'm having some issues with gdal on a 14.04 based image running a GeoDjango app with dokku.

It complains about `sqlite3_column_database_name` not being defined. I compared the symbols from the system wide libsqlite3 inside the container and the symbols from the bundled sqlite3 and such function is missing:

    root@2fdfab92c524:/# objdump -TR /app/.heroku/python/lib/libsqlite3.so.0.8.6 | grep sqlite3_column_database_name
    root@2fdfab92c524:/# objdump -TR /usr/lib/x86_64-linux-gnu/libsqlite3.so.0.8.6 | grep sqlite3_column_database_name
    0000000000010860 g    DF .text  0000000000000011  Base        sqlite3_column_database_name
    0000000000010880 g    DF .text  0000000000000011  Base        sqlite3_column_database_name16

Looking at the buildpack sources seems like it bundles sqlite-3.7.9 while Ubuntu 14.04 ships [sqlite-3.8.6](https://launchpad.net/ubuntu/+source/sqlite3). So probably upgrading the bundled sqlite3 will fix the issue.

Best Regards,

**Comment by sebasmagri** [comment]
@michaelshobbs I wrongly bugged the gdal maintainers in Ubuntu and you can find details on:

https://bugs.launchpad.net/ubuntu/+source/gdal/+bug/1406679

**Comment by diwu1989** [comment]
strongly second bumping up the version of Sqlite to the latest

**Comment by DylanLukes** [comment]
Bumping the version doesn't solve the problem. Even bumped (as in my fork) to 3.8.6, the column metadata APIs (such as `sqlite3_column_table_name` and `sqlite3_column_database_name` won't be included.

The fix should be adding the `-DSQLITE_ENABLE_COLUMN_METADATA` flag.
