### ISSUE TITLE
TypeError: PackageFinder() missing 1 required keyword argument: 'session'

### ISSUE THREAD

**Issue by ErikEvenson** [heroku/heroku-buildpack-python#191]
```
=====> Downloading Buildpack: https://github.com/heroku/heroku-buildpack-python
=====> Detected Framework: Python
Traceback (most recent call last):
  File "/tmp/buildpacks8VPA/vendor/pip-pop/pip-diff", line 114, in <module>
    main()
  File "/tmp/buildpacks8VPA/vendor/pip-pop/pip-diff", line 109, in main
    diff(**kwargs)
  File "/tmp/buildpacks8VPA/vendor/pip-pop/pip-diff", line 81, in diff
    r1 = Requirements(r1)
  File "/tmp/buildpacks8VPA/vendor/pip-pop/pip-diff", line 25, in __init__
    self.load(reqfile)
  File "/tmp/buildpacks8VPA/vendor/pip-pop/pip-diff", line 35, in load
    finder = PackageFinder([], [])
  File "/app/.heroku/python/lib/python2.7/site-packages/pip-6.0.6-py2.7.egg/pip/index.py", line 65, in __init__
    "PackageFinder() missing 1 required keyword argument: "
TypeError: PackageFinder() missing 1 required keyword argument: 'session'
```

**Comment by watsontom100** [comment]
Also getting this error. Using a multi-buildpack and only started getting it today. 

It continues after this error but then later I get a pylibmc install error as well with no changes to requirements.txt.. so seems related.

**Comment by tomdickin** [comment]
I just started getting it, also using multi-buildpack.

For me the build continues but then fails with 'failed to run repack'. Not sure if the eventual failure is related though.

@watsontom100 You just keep popping up everywhere! We use pylibmc btw, but we had no failure when it came to installing that.

**Comment by tomdickin** [comment]
Just now tried a build again, this time it decided it did need to install pylibmc after all, which completely failed (looks like the vendored libmemcached wasn't installed nor the need for it detected -- even though pylibmc is in the root/only requirements.txt)

pylibmc failed to install in addition to the above error occurring, though 'helpfully' this went on and released the now broken app.

**Comment by ErikEvenson** [comment]
I am using multi-buildpack too with the above trace.

**Comment by kennethreitz** [comment]
Fixed!

**Comment by ErikEvenson** [comment]
Fix worked for me -- thanks!
