### ISSUE TITLE
pypy support

### ISSUE THREAD

**Issue by tardyp** [heroku/heroku-buildpack-python#197]
It looks like there is an access denied on pypy runtime:
http://lang-python.s3.amazonaws.com/cedar/runtimes/pypy-2.4.0

Moreover, pypy 2.5.0 has been out for some time now.

Please enable faster python on heroku. :)

**Comment by cclauss** [comment]
This one can be closed.  https://github.com/heroku/heroku-buildpack-python/blob/master/builds/runtimes/pypy-2.5.1
