### ISSUE TITLE
PIP requirements file names

### ISSUE THREAD

**Issue by MechanisM** [heroku/heroku-buildpack-python#205]
Someone else calls pip's requirements file as "requirements.pip"? I've seen a few django-projects with same naming, and doing this by myself, but heroku's python buildpack only reads requirements file with .txt extension. "requirements.pip" - more intuitive, and I'm always using this name for pip requirements files. Please, add an option to be able to use "requirements.pip". I'm sure, I'm not alone.

**Comment by kennethreitz** [comment]
Thanks for the feedback! We're sticking to `requirements.txt` at this time, however. Thanks!
