### ISSUE TITLE
collectstatic fails when running as part of a multipack

### ISSUE THREAD

**Issue by alimony** [heroku/heroku-buildpack-python#223]
When this Python buildpack is part of a multipack, anything depending on a `PATH` modified by previous entries in the `.buildpacks` file seems to fail. An example is `collectstatic` failing because it needs a `node` binary (to run e.g. `yuglify`) but can't find it since it lives in a randomly named `/tmp/*` directory created when building `node` in a previous node buildpack step.

See [this issue](https://github.com/heroku/heroku-buildpack-nodejs/issues/230) for additional background, test cases, etc.

**Comment by hakanw** [comment]
This means that django-pipeline is not possible to set up on Heroku, which is how we found this bug. Because django-pipeline uses nodeJS for e g LessCSS, uglify-js and other things. And the easiest way to set up nodejs + django is a .buildpacks file with nodejs and python buildpacks together.

**Comment by mtford90** [comment]
In the meantime you can place the following in `bin/post_compile` to make node available:

```
export PATH=/app/.heroku/node/bin:$PATH
```

For example my Django project currently has the following post_compile script:

```
#!/usr/bin/env bash
export PATH=/app/.heroku/node/bin:$PATH
./manage.py migrate --noinput
./node_modules/bower/bin/bower install --config.interactive=false
./node_modules/gulp/bin/gulp.js  build
./manage.py collectstatic --noinput
```

**Comment by knukko** [comment]
Any news on this? Do I have to fork the python buildpack to get this working or is there any other workaround?

**Comment by Chronial** [comment]
I did not encounter this problem with the build-in multipack support: https://devcenter.heroku.com/articles/buildpacks#using-multiple-buildpacks

**Comment by kennethreitz** [comment]
I did a bunch of work around this around a month ago. Feel free to try again ;)

**Comment by pythdasch** [comment]
Is there any update about this issue ? I'm still having this problem since the 17th december, date of a release of nodejs buildpack. And as far as I red post, it's the python library which cannot find node library
