### ISSUE TITLE
Vendored GDAL isn't built with gdal_array

### ISSUE THREAD

**Issue by jlaxson** [heroku/heroku-buildpack-python#228]
I love the step of including the vendored binary right in the main buildpack, but when I try to `import osgeo.gdal_array` (which I don't do directly, but happens when calling `raster_band.ReadAsArray()`, I get an error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/app/.heroku/python/lib/python2.7/site-packages/osgeo/gdal_array.py", line 25, in <module>
    _gdal_array = swig_import_helper()
  File "/app/.heroku/python/lib/python2.7/site-packages/osgeo/gdal_array.py", line 17, in swig_import_helper
    import _gdal_array
ImportError: No module named _gdal_array
```

It appears that building the _gdal_array.so extension (which facilitates interacting with numpy) is an optional step that wasn't done with the current prebuilt binaries.  Would be great to have it included.

**Comment by kennethreitz** [comment]
Great feedback, thanks!

**Comment by henrykironde** [comment]
you could try  
1) https://github.com/Esri/raster2gpkg  copy the packages missing
2) https://trac.osgeo.org/osgeo4w/

**Comment by kennethreitz** [comment]
according to my research, [this](http://gis.stackexchange.com/questions/82977/is-it-possible-to-use-gdal-without-admin-rights/83297#83297) is actually required. 

Closing, for now.
