### ISSUE TITLE
Pypy v2.6 is not yet supported

### ISSUE THREAD

**Issue by cclauss** [heroku/heroku-buildpack-python#229]
We need a file https://github.com/heroku/heroku-buildpack-python/blob/master/builds/runtimes/pypy-2.6.0 to support http://morepypy.blogspot.fr/2015/06/pypy-260-release.html or http://doc.pypy.org/en/latest/release-2.6.0.html

**Comment by kennethreitz** [comment]
<3

**Comment by kennethreitz** [comment]
done!
