### ISSUE TITLE
Support for Django migrations

### ISSUE THREAD

**Issue by lukasklein** [heroku/heroku-buildpack-python#233]
I was wondering why there is support for Django's `collectstatic`, but none for `migrate`. Is it, since the `migrate` command is built into Django only from version 1.7?

I couldn't find any references in previous issues / discussions, so I started building support for it here: https://github.com/lukasklein/heroku-buildpack-python/commit/e02629145c794ee2420a7f7713f76eb1fa66402d

Though I'm a bit stuck. The tests don't pass, but they also don't pass on the main repository for me. Is there any documentation on how to hack on this repository?
Simply trying to use it as the buildpack for a Django project doesn't work either, it seems to not execute the `migrate` step.

**Comment by mfenniak** [comment]
Hey @lukasklein, I'm not a developer on this project, but just saw your issue and wanted to comment.  There might be an argument not to support the Django migration automatically in the buildpack.

The buildpack runs once Heroku finds your git modifications, and then it creates a slug that is distributed to other application servers.  This might not be the right time to run DB migrations.  If you ran it during the buildpack, you'd still be running software that is expecting the old DB schema.  And then, while the slug is distributed among your app nodes, some of them would expect the old schema and some the new schema.

DB migrations typically require either a lot of care to make backwards-compatible schema changes, or, a maintenance window to apply the schema changes while the app is offline.  Neither approach can be done in a buildpack.  On my own personal projects, I have an automatic deployment process that includes turning on the maintenance option in Heroku, pushing the git repo, running the migrations, and then turning off the maintenance option.  This way nobody is ever accessing the software in the half-deployed state if there are migrations.  A more sophisticated approach would be to only do this dance when DB migrations are present.

**Comment by kennethreitz** [comment]
What @mfenniak said :)

It would be much better to provide an official way to enable a user to do this themselves without modifying the build pack.

There's a little secret feature of the Python buildpack: if you add a `bin/post_compile` script, it will be run inline with the rest of the buildpack. This only works with the Python buildpack, however.

**Comment by lukasklein** [comment]
Ahh I see, thank you very much for the clarification :)

The `bin/post_compile` script looks promising and just like what I need for my case.

**Comment by edmorley** [comment]
If using `bin/post_compile` for operations that touch external resources, be aware of the caveats mentioned here:
https://discussion.heroku.com/t/django-automaticlly-run-syncdb-and-migrations-after-heroku-deploy-with-a-buildpack-or-otherwise/466/8

Heroku are in the process of adding something that will fit this use case however, see:
https://github.com/heroku/heroku-buildpack-postrelease
