### ISSUE TITLE
Update changelog for tagged versions

### ISSUE THREAD

**Issue by ltvolks** [heroku/heroku-buildpack-python#234]
For those of us pinning to tagged versions (e.g. for use with multi-buildpack or because we want to avoid surprises), an up-to-date changelog, including previous changes, would be very helpful. 

The [Ruby buildpack](https://github.com/heroku/heroku-buildpack-ruby/blob/master/CHANGELOG.md) sets a good example.

**Comment by kennethreitz** [comment]
This was started for [v60](https://github.com/heroku/heroku-buildpack-python/blob/master/Changelog.md).
