### ISSUE TITLE
Don't run pip with --allow-all-external

### ISSUE THREAD

**Issue by alex** [heroku/heroku-buildpack-python#236]
This was intentionally moved away from being pip's default because it's a performance, maintainability, and security nightmare.

**Comment by kennethreitz** [comment]
At the time, this was added for compatibility reasons. May be time to re-evaluate.

**Comment by alex** [comment]
At this point it's not needed for basically any packages on PyPI, not sure if there are other important usecases for heroku.

**Comment by dstufft** [comment]
pip 8 (the next version) is going to complete no-op this flag, and PyPI is going to get rid of them when the new site launches.

**Comment by kennethreitz** [comment]
:check:
