### ISSUE TITLE
Avoiding compile time penalty from `collectstatic --dry-run`

### ISSUE THREAD

**Issue by edmorley** [heroku/heroku-buildpack-python#252]
Currently, if a `manage.py` file is present and `DISABLE_COLLECTSTATIC` is not defined, then the buildpack runs collectstatic twice - once with `--dry-run` and then again for real:
https://github.com/heroku/heroku-buildpack-python/blob/ce3bdb37bafa3f56c54346d28ee5ef138cbc1893/bin/steps/collectstatic#L16-L32

In order to avoid this time penalty, I've seen blog posts suggesting people set `DISABLE_COLLECTSTATIC=1` then add collectstatic themselves to `bin/post_compile`, so it only runs once.

It seems like there must be a better way to do this? Perhaps one of:
(a) Have an `ENABLE_COLLECTSTATIC` or `SKIP_COLLECTSTATIC_DRY_RUN` env for people to set if they know their config definitely works and doesn't need a dry run.
(b) Cache the result in the case of a successful `--dry-run` so on subsequent deploys it's not run.
(c) Use a less expensive way of checking whether the project has a working collectstatic config. eg run collectstatic **without** the dry run param, and if that fails, try to clean up after it & then print the same error message that people currently get if `--dry-run` failed. (Or if this is too problematic: file bugs against Django to make collectstatic play more nicely.)

Thoughts? :-)

**Comment by kennethreitz** [comment]
C is a possible option. The reasoning behind the current implementation is the assumption that a tremendous amount of users have their apps misconfigured for collectstatic.

**Comment by edmorley** [comment]
Many thanks for your reply :-)

An additional issue with the current behaviour of just printing a warning (and allowing the build to continue) if the dry-run fails, is that it means people who have a correct collectstatic configuration can inadvertently break that configuration after months of it working and still have their deploy succeed, hiding the breakage.

Caching the success of previous runs would also avoid this, however I wonder if it would just result in less user surprise (and a simpler implementation) if we just did:

(d) only run the non-dry-run collectstatic, and if it fails, always fail the compile. In this case, show the collectstatic error output, a message linking to the collectstatic docs, and also explain that they can set the environment variable `DISABLE_COLLECTSTATIC=1` if they just want to skip it entirely.

> The reasoning behind the current implementation is the assumption that a tremendous amount of users have their apps misconfigured for collectstatic.

Is there a way to see how many people hit this in practice?

Given the build logs have shown the warning for months, might these users have already fixed their configs? If they haven't noticed the warning, then making the failure explicit would alert them to the problem, which actually might be preferable. And if they in fact don't need collectstatic, then informing them about `DISABLE_COLLECTSTATIC` would mean they can speed up their deploys by skipping the dry run that's only going to fail every time :-)

**Comment by edmorley** [comment]
Fixed in v76 (https://github.com/heroku/heroku-buildpack-python/compare/v75...v76).

Many thanks :-)

**Comment by kennethreitz** [comment]
🎉
