### ISSUE TITLE
Caching stopped unless you remove cache/.heroku dir

### ISSUE THREAD

**Issue by darklow** [heroku/heroku-buildpack-python#256]
Not sure why, but caching of pip installed apps stopped working for me.
Every time i deployed with dokku all the apps where installed as new.
Maybe because of this pull request https://github.com/heroku/heroku-buildpack-python/pull/255 ?
When I deleted `.heroku` dir caching started working again.
Not an issue anymore, but just as a note for somebody else who might run into same problem.

**Comment by sibeliusseraphini** [comment]
:+1:

**Comment by sibeliusseraphini** [comment]
:+1:

**Comment by sibeliusseraphini** [comment]
This really slow down deploys

**Comment by kennethreitz** [comment]
Caching is functioning properly on Heroku. Is this an issue with Dokku apps?

**Comment by sibeliusseraphini** [comment]
I think so, I'm using dokku for the deploys

**Comment by kennethreitz** [comment]
I think this is something that needs to be explored with the Dokku folks, because this has been in production for quite some time at Heroku, without any problems.
