### ISSUE TITLE
Only prepend to PKG_CONFIG_PATH

### ISSUE THREAD

**Issue by vesterbaek** [heroku/heroku-buildpack-python#263]
I need to install the pyav python package. pyav requires ffmpeg, so I'm using a buildback that provides ffmpeg before the heroku/python buildback

```
heroku buildpacks:add --index=1 https://github.com/apptitude/heroku-buildpack-ffmpeg.git
heroku buildpacks:add --index=2 heroku/python
```

Problem is that the install via pip (done by heroku/python buildpack) fails:

```
remote:            Complete output from command python setup.py egg_info:
remote:            Could not find libavformat with pkg-config.
remote:            Could not find libavcodec with pkg-config.
remote:            Could not find libavdevice with pkg-config.
remote:            Could not find libavutil with pkg-config.
remote:            Could not find libswscale with pkg-config.
remote:            Could not find either of libswresample or libavresample with pkg-config.
remote:            Some required libraries are missing, and PyAV cannot be built; aborting!
```

It fails because PKG_CONFIG_PATH is overridden and pkg-config therefore cannot find the .pc files in $HOME/vendor/ffmpeg/lib/pkgconfig.

Right now as a workaround, I've removed the av dependency from requirements.txt and install it manually via the post_compile hook as 

```
source ~/.profile.d/ffmpeg.sh
pip install av
```

Would it be possible to just prepend to the PKG_CONFIG_PATH variable?

**Comment by kennethreitz** [comment]
Can `PKG_CONFIG_PATH` take multiple values?

**Comment by vesterbaek** [comment]
From http://linux.die.net/man/1/pkg-config:

*it will also look in the colon-separated (on Windows, semicolon-separated) list of directories specified by the PKG_CONFIG_PATH environment variable.*

**Comment by kennethreitz** [comment]
Actually, the Python buildpack never touches `PKG_CONFIG_PATH`. 

Looks like you've hit a limitation on our multi-buildpack implementation.

**Comment by vesterbaek** [comment]
https://github.com/heroku/heroku-buildpack-python/blob/master/bin/compile#L107

**Comment by Jubjub** [comment]
We're having this same issue.
A possible solution is shown by https://github.com/jasrusable/heroku-buildpack-python by prepending to both `LIBRARY_PATH` and `LD_LIBRARY_PATH`, and by skipping the unsetting of both variables in line 50 of `bin/compile`.

**Comment by kennethreitz** [comment]
When the Python buildpack starts, `PKG_CONFIG_PATH` is not an available environment variable, even though it was set by the previous buildpack (ffmpeg). They are isolated from each-other. Because of this, the proposed solutions will not help the situation.

**Comment by furious-luke** [comment]
Hi! Actually, prior buildpacks can create an `export` file that sets up environment variables for future buildpacks ([see here](https://devcenter.heroku.com/articles/buildpack-api#composing-multiple-buildpacks)). My PR fixes this issue by appending any pre-existing `PKG_CONFIG_PATH` to the values set by this buildpack. Cheers!

**Comment by kennethreitz** [comment]
@furious-luke ah, fantastic! I was unaware of this mechanism, and felt like something was deeply missing ;)

**Comment by groovecoder** [comment]
I'm hitting the same issue trying to install the `paypalrestsdk` and/or `stripe` python packages, which require libffi. I made an (updated) heroku-buildpack-libffi here:

https://github.com/groovecoder/heroku-buildpack-libffi

But when pip tries to install `cffi` it says:

```
remote:          Running setup.py install for cffi: started
remote:            Running setup.py install for cffi: finished with status 'error'
remote:            Complete output from command /app/.heroku/python/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-QvHczS/cffi/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-7Tm_SL-record/install-record.txt --single-version-externally-managed --compile:
remote:            Package libffi was not found in the pkg-config search path.
remote:            Perhaps you should add the directory containing `libffi.pc'
remote:            to the PKG_CONFIG_PATH environment variable
remote:            No package 'libffi' found
```

**Comment by groovecoder** [comment]
Oh, and the app I'm deploying is using multi-buildpack with this `.buildpacks` file:

https://github.com/codesy/codesy/blob/libffi-buildpack/.buildpacks

**Comment by groovecoder** [comment]
Ah, now I see I just had to add `cffi` explicitly to my `requirements.txt` file to trigger libffi. Got the build working now.
