### ISSUE TITLE
Should setuptools be upgraded to v18.7.1?

### ISSUE THREAD

**Issue by cclauss** [heroku/heroku-buildpack-python#264]
https://github.com/heroku/heroku-buildpack-python/blob/master/bin/compile currently uses setuptools v18.3.2.  Are there reasons to upgrade to the current v18.7.1?

http://pythonhosted.org/setuptools/history.html

**Comment by kennethreitz** [comment]
Planning on doing this tomorrow, actually :)

**Comment by cclauss** [comment]
Closed via https://github.com/heroku/heroku-buildpack-python/commit/364ddc98b731e4e270ad0b9f42c047b2efcc8d8a
