### ISSUE TITLE
Spammy collectstatic for ManifestStaticFilesStorage

### ISSUE THREAD

**Issue by Chronial** [heroku/heroku-buildpack-python#268]
With [`ManifestStaticFilesStorage`](https://docs.djangoproject.com/en/1.8/ref/contrib/staticfiles/#manifeststaticfilesstorage) as `STATICFILES_STORAGE`, `collectstatic` outputs another line for each file, saying "Post-processed ...". That makes the output of the heroku build very spammy.

This can be fixed by replacing this line: https://github.com/heroku/heroku-buildpack-python/blob/a637ec3d11a5f2/bin/steps/collectstatic#L23 with this:
```bash
python $MANAGE_FILE collectstatic --noinput  2>&1 | sed '/^Post-processed/d;/^Copying/d;/^$/d;/^ /d' | indent
```

**Comment by kennethreitz** [comment]
Done! Many thanks. https://github.com/heroku/heroku-buildpack-python/commit/78b6142d1861ba0fe73cd59deadc92c46d68c499

:sparkles: :cake: :sparkles:

**Comment by Chronial** [comment]
thanks :smile:
