### ISSUE TITLE
Handling multiple python versions on the heroku shell

### ISSUE THREAD

**Issue by Immortalin** [heroku/heroku-buildpack-python#269]
I have an application that utilizes Python 3, however, one of its JavaScript dependencies requires Python 2 to build e.g. it has the following line in its package.json:
```JSON
"scripts": {
"postinstall": "cd ./node_modules/blockly/ ; python build.py"
},
```
On Ubuntu for example, you could specify the python version by calling either python2 or python3 at the command line but how do you do this/the equivalent on heroku? Can you use multiple python runtimes?

**Comment by edmorley** [comment]
I suspect being able to run multiple versions of Python would be useful for other cases too, however for Blockly, it looks like they have a yet-to-be-merged branch that adds Python 3 support (at least for the compiled code) - perhaps they'd be open to making compatibility changes to the build script too?
https://github.com/google/blockly/commit/1facefc3cfbce2493d31c2df73740c30d6a491d1
https://github.com/google/blockly/pull/228

I've asked for clarification at the end of https://github.com/google/blockly/issues/227

**Comment by Immortalin** [comment]
I have attempted to port build.py over to python 3 today but gave up since it requires an almost complete rewrite of the closure build code because calcdeps.py has been deprecated in favour of closurebuilder.py

**Comment by kennethreitz** [comment]
@Immortalin your JS dependency should utilize the underlying system python then, instead of the one provided for your application.

**Comment by Immortalin** [comment]
@kennethreitz can you elaborate on what do you mean? Doesn't installing `Python 3` symlink it to `bin/Python` and override the default system Python?

**Comment by cclauss** [comment]
Perhaps but it might not override `bin/python2` or `bin/python2.7` or `bin/python2.6`.  Can you please try to see if those are still around on your machine?

**Comment by kennethreitz** [comment]
@Immortalin just because of the way the PATH is setup. `/usr/bin/python` is built into the stack image :)

**Comment by kennethreitz** [comment]
It's easy to explore these things with `$ heroku run bash`

**Comment by Immortalin** [comment]
Thanks, will this be changed if e.g. the Linux base image that heroku is built on updated their version of python?

**Comment by kennethreitz** [comment]
Yes.
