### ISSUE TITLE
How to start additional agent(start with shell script) while starting python?

### ISSUE THREAD

**Issue by dwu-pivotal** [heroku/heroku-buildpack-python#272]
I have some agent write with shell script, and need to start before python web server starts, how to do this?

**Comment by kennethreitz** [comment]
Your Procfile entry can be a shell script :)

**Comment by dwu-pivotal** [comment]
Thx kennethreitz, but I need to make it default for all the developers that using this buildpack. Any place I can extend it?

**Comment by ChaosEternal** [comment]
another place is put such code in bin/post_compile .

**Comment by kennethreitz** [comment]
@dwu-pivotal I don't know of a way to do that, unfortunately.
