### ISSUE TITLE
django[bcrypt] and libffi

### ISSUE THREAD

**Issue by jambonrose** [heroku/heroku-buildpack-python#277]
[According to Django's docs, the way to include `bcyrpt` is to install `django[bcrypt]`](https://docs.djangoproject.com/en/1.9/topics/auth/passwords/#using-bcrypt-with-django).

Pushing to Heroku with `django[bcrypt]` declared in a `requirements.txt` file fails, as `libffi` is not installed. It appears as though `pip-grep` is not detecting the `bcrypt` requirement.

To be fair, the requirement is not a large one.

        # django/setup.py, lines 25-27, from stable/1.9.x
        extras_require={
            "bcrypt": ["bcrypt"],
        },

The problem disappears if `bcrypt` is defined separately from Django. Nonetheless, it would be nice if the recommended usage in the documentation worked.

I believe the easiest fix would be to add `django[bcrypt]` to the list on line 23 of `heroku-buildpack-python/bin/steps/cryptography`, and will open a PR if that is the desired solution.

**Comment by kennethreitz** [comment]
That is the desired solution!

Although, it should be noted that the best practice is to include *all* requirements, with pinned versions, in your `requirements.txt` files.

**Comment by jambonrose** [comment]
I've just created PR #278 with the suggested fix.
