### ISSUE TITLE
Allow pip to pickup manually installed packages [idea]

### ISSUE THREAD

**Issue by jvenezia** [heroku/heroku-buildpack-python#293]
related to: https://github.com/heroku/heroku-buildpack-python/pull/292

Exemples:
- [jvenezia/conda-buildpack](https://github.com/jvenezia/conda-buildpack) installs packages with conda.
- [ddollar/heroku-buildpack-apt](https://github.com/ddollar/heroku-buildpack-apt) installs any packages manually.

Packages installed like this should not be reinstalled during `pip-install`.

The workaround for now is to fork [heroku/heroku-buildpack-python](https://github.com/heroku/heroku-buildpack-python) and set `PYTHONPATH` with the previously installed packages before `pip-install` or any needed step.

**Comment by louy2** [comment]
Could you elaborate on the workaround?

**Comment by evdoks** [comment]
Are you talking about #338?
If yes, then it seems @kennethreitz has some strong arguments against modifying `PYTHONPATH`. However, your fork has helped us a lot in installing Scikit-Learn with pip. We can't use [conda-buildpack](https://github.com/kennethreitz/conda-buildpack) directly, as it does not play well with Django and in general does not have the same level of support as [heroku-buildpack-python](https://github.com/heroku/heroku-buildpack-python) has. 
Setting `PYTHONPATH` to `/app/.apt/usr/lib/python2.7/dist-packages:$PYTHONPATH` and using [heroku-buildpack-apt](https://github.com/heroku/heroku-buildpack-apt) for installing BLAS and LAPACK libraries finally allowed us to have `scipy` installed via `pip`.
Still it would be nice to have some sort of official way to combine packages installed with `apt-get` and `pip`. We are paying every month a quite significant amount to Heroku and are really happy with their services, but absence of an ability to use Scipy and Scikit-Learn with Django can be a deal breaker for us :(
