### ISSUE TITLE
pip-grep does not match local packages

### ISSUE THREAD

**Issue by whit537** [heroku/heroku-buildpack-python#299]
Reticketing from https://github.com/gratipay/inside.gratipay.com/issues/612#issuecomment-218132276 ...
### Steps
1. `cd vendor/pip-pop/`
2. `echo ./foo.zip > requirements.txt`
3. `./pip-grep requirements.txt foo`
### Expected

"Package foo found!"
### Actual

"Not found."

(Well, the _actual_ actual is https://github.com/heroku/heroku-buildpack-python/pull/298. ;-)

**Comment by kennethreitz** [comment]
This is an intentional design decision. You can't tell anything about something like a zip-file without opening and inspecting it.

**Comment by whit537** [comment]
What does `pip-grep` do with non-zip-files? Does it download hit the network to get more information about it? If it's willing to hit the network, why isn't it willing to peak inside local files?

Barring that, any suggested workarounds short of forking the buildpack?

**Comment by kennethreitz** [comment]
Hmm, I'm not sure. I feel like zipfiles (and any local files, actually) is outside the scope of (automatic installation of system sub-deps / uninstallation of no-longer-listed packages). This is intended for augmenting pip's management of pypi-index-style package distributions.
