### ISSUE TITLE
Python seems to be configured with UCS2 strings

### ISSUE THREAD

**Issue by jgraham** [heroku/heroku-buildpack-python#305]
Python in the buildpack is compiled with UCS2 strings so that e.g. `len(u"\U0010FFFF") == 2` and `re.compile(u"\U0010FFFF", re.U)` throws an exception. Although this seems to be the default, it is the configuration that is more likely to break in edge cases since it exposes surrogate pairs directly to the programmer and means that a variety of functions don't work as expected when passed a non-BMP character. It also doesn't match the default configuration of at least Ubuntu linux, so things are rather likely to break between dev and production.

Needless to say, I am filing this as a result of a bug handling non-BMP characters that only manifested on heroku and no other environment.

I think it would be preferable to change the buildpack to use the UCS4 option.

**Comment by kennethreitz** [comment]
Interesting. 

How would one go about changing this configuration during the Python build? What would the build flags look like?

**Comment by jgraham** [comment]
> configure supports a new option --enable-unicode, with the values ucs2 and ucs4 (new in 2.2a1). With --disable-unicode, the Unicode type and supporting code is completely removed from the interpreter.

From [https://www.python.org/download/releases/2.4.1/notes/](https://www.python.org/download/releases/2.4.1/notes/)

**Comment by kennethreitz** [comment]
That document is for Python 2.4.1, not modern Pythons.

**Comment by jgraham** [comment]
Well yes, because that's when the feature was first noted in the changelog. Apparently it is otherwise poorly documented. It then applies to every subsequent Python until 3.3 when [PEP 393](https://www.python.org/dev/peps/pep-0393/) landed and changed the unicode implementation to something more sane.

**Comment by kennethreitz** [comment]
Relevant: https://github.com/yyuu/pyenv/issues/257

**Comment by edmorley** [comment]
Fixed via #322 and related :-)
