### ISSUE TITLE
Buffered responses?

### ISSUE THREAD

**Issue by ckcollab** [heroku/heroku-buildpack-python#307]
Heyo! First of all, thanks for all the work on this, love Heroku and how easy it is to use :)

I am having a pretty annoying problem, it seems like I keep getting Request Timeouts when using code like this, in Django:

```python
def do_import(request):
    return StreamingHttpResponse(some_generator())
```

I keep getting hangs here, even with `send_bytes=1` set for Waitress, which should stop any responses from buffering. So I'm wondering, what the heck is causing buffering/timeouts? Can I force flush the buffer somehow? Is there some nginx setting, and if so, how do I overwrite/provide extra nginx stuff?

Thanks again, appreciate any help/response :)

**Comment by kennethreitz** [comment]
Streaming responses should "just work". There is no nginx involved, unless you're using a special custom buildpack configuration. 

I would recommend giving this a read:

https://devcenter.heroku.com/articles/http-routing

There may be something simple that you're missing for your configuration.

**Comment by ckcollab** [comment]
Hm, maybe it's just Waitress? In any case, I got something working good enough for now, thanks for the reply!

Have a good one.
