### ISSUE TITLE
Default Start Command

### ISSUE THREAD

**Issue by RochesterinNYC** [heroku/heroku-buildpack-python#309]
The Heroku python buildpack does not provide a default start command. It'd be great for the buildpack to provide the correct default start command for flask, django, and regular python apps in a manner similar to the Ruby, PHP, or Nodejs heroku buildpacks.

**Comment by kennethreitz** [comment]
Thank you for the feedback! The current design, however, is quite intentional :)

**Comment by RochesterinNYC** [comment]
Gotcha, is there a link/reference where I can see the context behind the design decision? Trying to understand as we might be looking to implement something downstream for the Cloud Foundry buildpack. Thanks!

**Comment by kennethreitz** [comment]
The reasons are many. 

Personally, I think it's a poor design decision in general, and should only be considered if there's an extremely reasonable and sane default for the Procfile entry.

In Python's case, people have the choice of any webserver they like, and it can be configured in a myriad number of ways, pointing to any sort of WSGI application at any sort of path. Providing a Procfile entry automatically would required making a large number of (often incorrect) assumptions, automatically installing production-grade server dependencies (no), and involve a lot of "intelligent" guesswork at where entrypoints lie.

In short, it would be poor, faulty, and prone to massive amounts of breakage.

I also think this increases user confusion about the platform and not understanding what's actually going on or what's actually required to run an application. It would be acceptable, but less than ideal, in my opinion.

Every application pushed up, in my opinion, should have a Procfile, if they want Heroku to run any processess for them. Having none is acceptable (a "$ heroku run"-only app). 

Ruby effectively set this precedent. Then, Python came along. The cultures of these two languages are extremely different — the Ruby/Rails community takes great pride in "convention over configuration" (e.g. default Procfile), while Python does not. That's another big factor.
