### ISSUE TITLE
pip-grep not working to detect cffi 

### ISSUE THREAD

**Issue by ShaneXie** [heroku/heroku-buildpack-python#311]
seems this line is actually fail to dectect cffi
https://github.com/heroku/heroku-buildpack-python/blob/master/bin/steps/cryptography#L23

and please add scrapy into the list after fixed this problem.

**Comment by kennethreitz** [comment]
`cffi` should be detected properly. Can you provide the `requirements.txt` file you are using?

**Comment by ShaneXie** [comment]
```
cffi
gunicorn==19.4.5
Flask==0.11.1
Scrapy==1.1.0
py2neo==3.0.0
scrapyd==1.1.0
scrapyd-client==1.0.1
python-scrapyd-api==2.0.1
```
I think this is related to https://github.com/kennethreitz/pip-pop/pull/12

**Comment by kennethreitz** [comment]
It is not.

**Comment by ShaneXie** [comment]
ok... :) anyway, I got to fork this repo and remove that line in order to get libffi.

**Comment by kennethreitz** [comment]
Which line?
