### ISSUE TITLE
Failures during vendored libs script don't cause the compile to fail

### ISSUE THREAD

**Issue by edmorley** [heroku/heroku-buildpack-python#312]
In the case of #302, exceptions occurred during the pip-grep invocations in the `bin/steps/*` scripts.

However the compile completed without error, meaning that anyone not paying attention to the build logs would not be aware that parts of the build hadn't completed successfully.

IMO, if any of the `bin/steps/*` scripts fail, the build should also fail.

**Comment by kennethreitz** [comment]
pip-grep is a non-essential step in the buildpack compile process, and is configured intentionally to continue upon failure (although becoming a little less rare with `--hash`), in the event that a horribly strange `requirements.txt` file is passed in.
