### ISSUE TITLE
Python Buildpack version numbers in bin/comple

### ISSUE THREAD

**Issue by cclauss** [heroku/heroku-buildpack-python#315]
https://github.com/heroku/heroku-buildpack-python/blob/master/bin/compile#L48 does not align with https://github.com/heroku/heroku-buildpack-python/blob/master/CHANGELOG.md

**Comment by kennethreitz** [comment]
yeah, that number is just for metrics, and isn't really needed. It's a pain to update, and isn't useful, but can't be removed.

**Comment by cclauss** [comment]
Well explained.
