### ISSUE TITLE
Allow comments in runtimes.txt

### ISSUE THREAD

**Issue by edmorley** [heroku/heroku-buildpack-python#318]
Currently the Python version is extracted from `runtimes.txt` using:
```bash
PYTHON_VERSION=$(cat runtime.txt)
```

It would be helpful for us to be able to add comments to `runtimes.txt` (eg: a link to the runtimes docs for those unfamilar with Heroku, or an explanation as to why we're pinned to a particular Python version).

I'm happy to open a PR that greps comments out - does `#` as a comment character sound ok to you?

**Comment by kennethreitz** [comment]
This is entirely unnecessary, but thank you.

**Comment by inoks** [comment]
I think it will be good to have that feature, to add some notes. 
For example:
```
python-3.6.10  # Can't upgrade to Python 3.7 due to the  Celery 4.2.2 incompatibility
```

**Comment by pataquets** [comment]
I'd like to add comments, too. Sometimes it's necessary to add notes on why we're sticking to a particular runtime version and avoid further troubles. It would help in a nicer DX.
@kennethreitz Is there any feature wishlist for users (uservoice or similar) where people might chime in and show interest?
