### ISSUE TITLE
better support for setting env. vars when building packages

### ISSUE THREAD

**Issue by aljosa** [heroku/heroku-buildpack-python#324]
My specific problem is w/ xmlsec, as discussed before in issues #106 and #257 by other buildpack users but could easily be any other python package (w/ c deps).

I've added apt buildpack to install required dependencies when building xmlsec package:

```
$ heroku  buildpacks
=== app Buildpack URLs
1. https://github.com/heroku/heroku-buildpack-apt
2. https://github.com/heroku/heroku-buildpack-python

$ cat Aptfile
libxml2
libxml2-dev
libxmlsec1
libxmlsec1-dev

$ cat .profile.d/apt_paths.sh
export PATH=/app/.apt/usr/bin:$PATH
export C_INCLUDE_PATH=/app/.apt/usr/include:/app/.apt/usr/include/xmlsec1:$C_INCLUDE_PATH
export CPLUS_INCLUDE_PATH=/app/.apt/usr/include:/app/.apt/usr/include/xmlsec1:$CPLUS_INCLUDE_PATH
export INCLUDE_PATH=/app/.apt/usr/include:/app/.apt/usr/include/xmlsec1:$INCLUDE_PATH
export LIBRARY_PATH=/app/.apt/usr/lib/x86_64-linux-gnu:/app/.apt/usr/lib/i386-linux-gnu:/app/.apt/usr/lib:$LIBRARY_PATH
export LD_LIBRARY_PATH=/app/.apt/usr/lib/x86_64-linux-gnu:/app/.apt/usr/lib/i386-linux-gnu:/app/.apt/usr/lib:$LD_LIBRARY_PATH
export PKG_CONFIG_PATH=/app/.apt/usr/lib/x86_64-linux-gnu/pkgconfig:/app/.apt/usr/lib/i386-linux-gnu/pkgconfig:/app/.apt/usr/lib/pkgconfig:$PKG_CONFIG_PATH
export CPATH=/app/.apt/usr/include:$CPATH
export CPPPATH=/app/.apt/usr/include:$CPPPATH
```

so when I run `heroku run bash` and try to install xmlsec, it works w/o problems:

```
$ heroku run bash
Running bash on ⬢ app... up, run.5444
~ $ which pip
/app/.heroku/python/bin/pip
~ $ pip freeze
libxml2-python==2.7.8
~ $ pip install xmlsec
Collecting xmlsec
  Downloading xmlsec-0.6.1.tar.gz
Collecting lxml>=3.0 (from xmlsec)
  Downloading lxml-3.6.1.tar.gz (3.7MB)
    100% |████████████████████████████████| 3.7MB 129kB/s
Installing collected packages: lxml, xmlsec
  Running setup.py install for lxml ... -
done
  Running setup.py install for xmlsec ... done
Successfully installed lxml-3.6.1 xmlsec-0.6.1
~ $
```

to  achieve the same thing during the build I've added:

```
$ cat bin/pre_compile
APP_BIN_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source $APP_BIN_DIR/../.profile.d/apt_paths.sh
```

but this fails although the the env should be the same as for `heroku run bash`:

```
...
remote:            In file included from src/xmlsec/constants.c:288:0:
remote:            src/xmlsec.h:1:27: fatal error: xmlsec/xmlsec.h: No such file or directory
remote:             #include <xmlsec/xmlsec.h>
remote:                                       ^
remote:            compilation terminated.
remote:            error: command 'gcc' failed with exit status 1
remote:
...
```

while I can't be sure why, I'm guessing I missed some bin/lib/include env settings in python buildpack which makes the same env in one-off dyno different from build env.
the solution is to build my own buildpack and I'm hoping I'm wrong.

**Comment by edmorley** [comment]
Ah so `pre_compile` is run in a sub-shell (see: [here](https://github.com/heroku/heroku-buildpack-python/blob/0ed4089cb9e9f6abcaf91f48e3b8fc27fc9bf9b2/bin/steps/hooks/pre_compile#L6) and [here](https://github.com/heroku/heroku-buildpack-python/blob/0ed4089cb9e9f6abcaf91f48e3b8fc27fc9bf9b2/bin/utils#L86-L107) - note the `sub-env`'s use of `( ... )` for the sub-shell), presumably to prevent people's custom scripts from breaking the build (eg by changing the working directory).

However this does mean any variables that are exported won't be set in the parent bash process.

This made things harder than they need be for me recently too, when trying to vendor a newer libmysqlclient, which I ended up working around by creating symlinks instead ([here](https://github.com/mozilla/treeherder/blob/c1dfa498cc8e7a57a9d304e00aa44e9f6ae66f40/bin/pre_compile#L18-L27)).

@kennethreitz would you be open to adjusting the `pre_compile`/`post_compile` scripts such that they don't run in a sub-env, but instead reset things like working directory and shell options (eg errexit mode) afterwards? This would mean people can at least export the variables they need, whilst hopefully still minimising the things people can break.

Given the hooks are listed as experimental and will typically only be used by more advanced users, I think it's probably fine to make them slightly less resilient to human error, if it means they're actually more useful for vendoring libraries etc.

Many thanks :-)
