### ISSUE TITLE
Symlinks to missing files

### ISSUE THREAD

**Issue by f0r4y312** [heroku/heroku-buildpack-python#327]
75870dd changes
`-    deep-cp $BUILD_DIR $APP_DIR`
`+    # deep-cp $BUILD_DIR $APP_DIR`
`+    ln -s $BUILD_DIR/* $APP_DIR`

seems to link to a missing Procfile (and probably other files) causing:
`remote: -----> Discovering process types`
`remote: Procfile declares types -> (none)`

**Comment by stefanosala** [comment]
We also get a failure, but with different message:

```
remote: -----> Python app detected

remote: ln: failed to create symbolic link /app/tmp: File exists

remote:  !     Push rejected, failed to compile Python app.
```

That's probably because we have a `/tmp` folder in our repository.

**Comment by kennethreitz** [comment]
This change has been reverted.

Ideally, this should have just simply sped up the buildpack by reducing the number of IOPS required during the build process—and all worked well in my exploratory tests. Further investigation will have to be required.

Thanks for the report.
