### ISSUE TITLE
package installed but not in requirements.txt

### ISSUE THREAD

**Issue by aljosa** [heroku/heroku-buildpack-python#33]
package that was installed in previous push wasn't removed after it (django-piston) was removed from requirements.txt.
when i try to run "pip install -r requirements.txt" in a new "virtualenv --no-site-packages env" it doesn't install piston.

when connected w/  "heroku run bash":

~ $ pwd
/app

~ $ ls lib/python2.7/site-packages/
piston
django_piston-0.2.3-py2.7.egg-info 
...

~ $ cat requirements.txt |grep piston
# django-piston

**Comment by eroninjapan** [comment]
Is modifying runtime.txt, deploying, reverting runtime.txt still the best method to accomplish purging the cached dependencies? I tried using the Heroku Repo plugin's purge_cache command but it's not working as expected.

**Comment by kennethreitz** [comment]
Packages are now automatically uninstalled when removed from requirements.txt

**Comment by wooyek** [comment]
I have no versions in the `requirements.txt`. How can I make sure that the latest packages will be installed on deploy to heroku? 

PS. No versions freeze is on purpose. I know it's not the best practice. but I want my CI to catch any incompatibilities as quicly as it can and I don't want to keep to versions of requirements file.

**Comment by leemengtaiwan** [comment]
I know this issues is closed, but I tried to specify a different runtime in runtime.txt and redeploy and revert and heroku still include many packages even if I already remove them all in requirement.txt.

Any further suggestion available?

**Comment by wooyek** [comment]
For anyone who stumbles here, as a workaround you can user `post_compile` hook, eg.:

```bash
#!/usr/bin/env bash
# File path should be ./bin/post_compile
# https://gist.github.com/kylefox/7044491259b6b2586ca1

echo "UPGRADE_REQUIREMENTS: $UPGRADE_REQUIREMENTS"

if [[ "$UPGRADE_REQUIREMENTS" == "True" ]]; then
    echo "====> Upgrading requirements"
    pip install -r requirements.txt -U
fi
echo "====> Installed versions"
pip freeze
```
…or similar.
