### ISSUE TITLE
How can I always fetch latest version of packages from requirements.txt?

### ISSUE THREAD

**Issue by erichonkanen** [heroku/heroku-buildpack-python#330]
Hello,

How can I always do the equivalent of `pip install --upgrade -r requirements.txt` on heroku with this buildpack?

**Comment by kennethreitz** [comment]
That is not possible, at this time. 

This functionality has been requested by someone before, and was heavily considered — however, at this time it was opted against. Thanks for your feedback! I've added it to my list of things to evaluate as improvements (perhaps with an environment variable switch). 

✨🍰✨

**Comment by erichonkanen** [comment]
environment flag seems simple enough maybe in Procfile or elsewhere
