### ISSUE TITLE
collectstatic fails for Review Apps because environment variables are not being set

### ISSUE THREAD

**Issue by ovidiusabou** [heroku/heroku-buildpack-python#333]
If the Heroku environment depends on an environment variable being set, e.g. `DJANGO_SETTINGS_MODULES=config.settings.production`, the `collectstatic` might fail, as `manage.py` takes the default settings value (usually for local development), which is not necessarily appropriate for production (in my case it's not).

I've tried disabling the `collectstatic` step using the `env` section from `app.json`, but Heroku doesn't set those variables during the compile phase, so `collectstatic` is executed anyway in a review app.

This problem only occurs with review apps, since for normal apps the environment variables can be configured manually, in which case they are available during the compile phase. It only seems to be an issue with variables that are specified in`app.json`, which is the only way to declare variables for review apps.

**Comment by ovidiusabou** [comment]
https://devcenter.heroku.com/articles/github-integration-review-apps this is the feature I'm referring to

**Comment by kennethreitz** [comment]
thanks for bringing this to our attention

**Comment by kennethreitz** [comment]
I believe the proper solution here is to set those environment variables in `app.json`.
