### ISSUE TITLE
Could not import setuptools which is required to install from a source distribution

### ISSUE THREAD

**Issue by toothywalrus** [heroku/heroku-buildpack-python#336]
Whenever I'm trying to push using the 'git push origin HEAD:master --force' command, I'm getting the following setuptools error (check out the screenshot): "Could not import setuptools which is required to install from a source distribution".

![screenshot at 2016-11-21 15 33 58](https://cloud.githubusercontent.com/assets/5265045/20497393/a1aaa436-b031-11e6-9bcc-dd489136cfbc.png)

I thought it was related to the recent pip/setuptools update in official python buildpack.. so i made a fork of buildpack's repository and did a roll-back to the previous commits where old versions were used, but it didn't help. I tried to execute a 'purge-cache' command.. no luck. Then I tried to do a 'reset', change requirements.txt.. But it all just doesn't help to solve the problem. Would appreciate any help. Thanks!

**Comment by edmorley** [comment]
In the screenshot I see this error message displayed:

> "Hello! It looks like your application is using an outdated version of Python.
> This caused the security warning you saw above during the 'pip install' step.
> We recommend 'python-2.7.12', which you can specify in a 'runtime.txt' file."

Further up in the screenshot, I also see:

> "---> Installing Python 2.7.5"

...so I'd check the `runtime.txt` file in your repo and update the Python version listed there.

**Comment by toothywalrus** [comment]
edmorley, thanks for the respond, but I already tried that =) yes, if I'll update the runtime.txt with the newest version of Python - then i'll get rid of that warning. But it has nothing to do with the main issue. Maybe I'm doing something wrong, but I just can't seem to find what exactly. Can it be related to some internal heroku cache thing? Like, some old package stuck somewhere or something?

**Comment by toothywalrus** [comment]
So, @edmorley, i updated the `runtime.txt`, and it doesn't help, as you see:

![screenshot at 2016-11-22 01 25 37](https://cloud.githubusercontent.com/assets/5265045/20504943/cc8e5aa0-b052-11e6-9ae1-68acf1a35cc9.png)

**Comment by edmorley** [comment]
It looks like ez_setup (https://pypi.python.org/pypi/ez_setup) is incompatible with newer setuptools.
Try removing it from your requirements.txt - I doubt you need it anyway.

**Comment by kennethreitz** [comment]
it looks like one of your package dependencies is trying to run `ez_setup.py` (bootstraps setuptools), which is neither proper or supported on heroku. Setuptools is already available.

**Comment by toothywalrus** [comment]
I thought so too.. and i tried to remove it. But i'm getting the same error regardless of the presence of that package.It fails in exactly the same way even if i have only BeatifulSoup package listed in requirements.txt file.

**Comment by toothywalrus** [comment]
`Compressing objects: 100% (38255/38255), done.
Writing objects: 100% (163612/163612), 334.32 MiB | 1.28 MiB/s, done.
Total 163612 (delta 125127), reused 161216 (delta 123158)
remote: Compressing source files... done.
remote: Building source:
remote: 
remote: -----> Deleting 28 files matching .slugignore patterns.
remote: -----> Python app detected
remote: -----> Installing python-2.7.12
remote: -----> Noticed pylibmc. Bootstrapping libmemcached.
remote: -----> Noticed cffi. Bootstrapping libffi.
remote:      $ pip install -r requirements.txt
remote:        Collecting BeautifulSoup==3.2.1 (from -r requirements.txt (line 1))
remote:          Downloading BeautifulSoup-3.2.1.tar.gz
remote:        Could not import setuptools which is required to install from a source distribution.
remote:        Traceback (most recent call last):
remote:          File "/app/.heroku/python/lib/python2.7/site-packages/pip-9.0.1-py2.7.egg/pip/req/req_install.py", line 387, in setup_py
remote:            import setuptools  # noqa
remote:          File "build/bdist.linux-x86_64/egg/setuptools/__init__.py", line 10, in <module>
remote:          File "build/bdist.linux-x86_64/egg/setuptools/extern/__init__.py", line 1, in <module>
remote:        ImportError: No module named extern
remote:        
remote:  !     Push rejected, failed to compile Python app.
remote: 
remote:  !     Push failed
remote: Verifying deploy...
remote: 
remote: !	Push rejected to alpha-getshelf.
remote: 
`

**Comment by toothywalrus** [comment]
![screenshot at 2016-11-22 20 46 25](https://cloud.githubusercontent.com/assets/5265045/20537201/df527002-b0f4-11e6-8aed-594ea8716256.png)

**Comment by toothywalrus** [comment]
Well, I finally found the reason. I had some weird `pkg_resources.py` module sitting in the root directory. Have no idea what is it for and why it was there (it's like a long-time project, so I didn't participate in adding that module). But the thing is that after I removed that crap - everything works like a charm. Thanks for everyone's help!
