### ISSUE TITLE
editable install not working

### ISSUE THREAD

**Issue by codingjoe** [heroku/heroku-buildpack-python#345]
Since yesterday a couple of things changed, which currently keep us from deploying to our production systems.

All packages are shown to be installed normally during build, but when I connect to the dyno later, the `-e` installed dependecies are missing.
I presume it had something to do with the pip update. Anyways, that should have taken down our production system, but there was another bug, which stopped the deploy (luckily).

We use a gettext buildpack to compile gettext messages during the deploy. Even tho we set the path there and this worked before, since today, it says it can't find the executable.
That really strange since the only buildpack updated during that time, was this one.

I rolled back to v85 and everything is fine again, so it must be a change merged yesterday.

**Comment by systemizer** [comment]
I am experiencing the same issue and is blocking deploys on our production environment.

On heroku, it looks like the egg-links are pointing to a nonexistant directory in /tmp. In the production environment (working), it points to a directory in /app

**Comment by kennethreitz** [comment]
Will work on a fix on Monday.

**Comment by kennethreitz** [comment]
This should now work, in v88!

**Comment by kennethreitz** [comment]
Sorry for the bug.

**Comment by codingjoe** [comment]
@kennethreitz sorry, but that didn't do it for me :/
```shell
PATH=/app/.gettext/bin:$PATH
LD_LIBRARY_PATH=/app/.gettext/lib:$LD_LIBRARY_PATH
msgfmt -c -o foo/locale/de/LC_MESSAGES/django.mo foo/locale/de/LC_MESSAGES/django.po
remote: make: msgfmt: Command not found
remote: make: *** [foo/locale/de/LC_MESSAGES/django.mo] Error 127
```

**Comment by alanct-minted** [comment]
Our team is also having related issues today with a `-e .` in our requirements. Clearing the repo cache before each push has helped temporarily, some, and now we're facing other (possibly different failures):

```
    mv: inter-device move failed: /app/.heroku/src to /tmp/build_08cc463eebac4215aef2b9e546c91086/.heroku/src; unable to remove target: Is a directory
    !     Push rejected, failed to compile Python app.
    !     Push failed
```

I haven't had a chance to dig in much as we're on some more critical feature work today, but will try to post more details for debugging this week if others don't chime in before.

**Comment by alanct-minted** [comment]
Errr, in our case, builds weren't succeeding (and then missing the actual deps) like @codingjoe's, they were failing with something like this:

```
remote:        AssertionError: Egg-link /tmp/build_ae04897baf4d241ad0d379f9fd90b409 does not match installed location of hitchedup (at /tmp/build_a97245df09b37d58ae842c69a7b21f01)
```

Soooo possibly unrelated to this thread. Sorry for the lack of details! Just want to keep it on the radar that there could still be outstanding issues for others.

**Comment by zph** [comment]
Saw similar issue here as @alanct-minted 

```
AssertionError: Egg-link /app does not match installed location of <internal_library> (at /tmp/build_<SHA>)
```

Resolved by clearing build cache and then pinning to v85 of buildpack, which was last known good for this repo.

```
$  heroku repo:purge_cache -r production # from https://github.com/heroku/heroku-repo
$  heroku buildpacks:remove "https://github.com/heroku/heroku-buildpack-python.git"
$  heroku buildpacks:add "https://github.com/heroku/heroku-buildpack-python.git#v85"
$  git push production

```

Pinning to v85 and pushing didn't work for us without purging cache.

**Comment by kennethreitz** [comment]
This should now work properly, but a purge cache may be required if pushes were done during this unfortunate bug period.

**Comment by alanct-minted** [comment]
Cache purge has still been necessary on every build over the past day... similar messages:

```
remote:        AssertionError: Egg-link /tmp/build_6998afdf610505b870007147f449b54b does not match installed location of hitchedup (at /tmp/build_d4a26a97d93d04dd4ad6d81b572631f5)
```

**Comment by zph** [comment]
@kennethreitz Thank you for your work on this buildpack and issue.
