### ISSUE TITLE
"Host key verification failed." while running pip with private repositories

### ISSUE THREAD

**Issue by NovaDev94** [heroku/heroku-buildpack-python#346]
```
-----> Python app detected
     $ pip install -r requirements.txt
       Obtaining file:///tmp/build_ad399ed5a7665bbd6b06c006e4a664f1 (from -r requirements.txt (line 2))
       Obtaining sp-backend-imaging from git+ssh://git@github.com/***/sp-backend-imaging.git@feature/testing_Dec19#egg=sp-backend-imaging (from -r requirements.txt (line 1))
         Cloning ssh://git@github.com/***/sp-backend-imaging.git (to feature/testing_Dec19) to /app/.heroku/src/sp-backend-imaging
       Host key verification failed.
       fatal: Could not read from remote repository.

       Please make sure you have the correct access rights
       and the repository exists.
       Command "git clone -q ssh://git@github.com/***/sp-backend-imaging.git /app/.heroku/src/sp-backend-imaging" failed with error code 128 in None
 !     Push rejected, failed to compile Python app.

 !     Push failed
```

I had a `.ssh` folder in the Heroku repository (checked on GitHub deploy keys and it works normally) and it worked normally a week ago, it just breaks today when I'm trying to push some changes...

Maybe this is related to the recent changes?

**Comment by NovaDev94** [comment]
I've tried to go through commits to find the exact commit introducing this problem: https://github.com/heroku/heroku-buildpack-python/commit/991f4126d76dff1aff09e0c4fb0d4488e8c9407c

**Comment by kennethreitz** [comment]
I don't believe this was a supported way to do this before, hence the breakage. Are you using the heroku buildpack for ssh keys? One exists.

**Comment by kennethreitz** [comment]
https://elements.heroku.com/buildpacks/bjeanes/ssh-private-key-buildpack

**Comment by NovaDev94** [comment]
Before this change, all I need to do is put a `.ssh` folder (with `id_rsa` and `id_rsa.pub`) in the Heroku repo folder (as shown on this https://github.com/heroku/heroku-buildpack-python/issues/97#issuecomment-20902506).  

---

I just tried the `ssh-private-key-buildpack`, seem like it works correctly now! Though I have another error but I think it's addressed and already fixed by you 👍 

```
AssertionError: Egg-link /app does not match installed location of thumbor-exts
```

**Comment by kennethreitz** [comment]
Sorry for the change!
