### ISSUE TITLE
mv: inter-device move failed

### ISSUE THREAD

**Issue by systemizer** [heroku/heroku-buildpack-python#348]
We've been experiencing the following error since the latest release (v89 or v90). It's causing our builds to fail. Any help would be appreciated. thanks!

`mv: inter-device move failed: ‘/app/.heroku/src’ to ‘/tmp/build_9d3ed15e37a7202634a4ea4a5070db60/Twoniverse-trackgenius-api-030dde3cb4d0d4fa8f8097eaebb4e95e56883626/.heroku/src’; unable to remove target: Is a directory`

**Comment by alanct-minted** [comment]
Same for us!

```
    mv: inter-device move failed: /app/.heroku/src to /tmp/build_08cc463eebac4215aef2b9e546c91086/.heroku/src; unable to remove target: Is a directory
    !     Push rejected, failed to compile Python app.
    !     Push failed
```

Our deploys are blocked at present.

**Comment by kennethreitz** [comment]
should now be fixed

**Comment by systemizer** [comment]
rgr. thanks!

**Comment by kennethreitz** [comment]
confirmed?

**Comment by alanct-minted** [comment]
:hugs: confirmed

**Comment by JoshDrake-minted** [comment]
No longer experience the issue with ``mv``, but the symlink right after is now erroring (just needs the force flag, I think):

```bash
ln: failed to create symbolic link /tmp/build_5116ea80ec343e848e69d0442e2b17f5/.heroku/src/src: File exists
!     Push rejected, failed to compile Python app.
!     Push failed
```

**Comment by JoshDrake-minted** [comment]
Looks like 19513067bbc734ee3cf19a3a9a13b6be94838b76 fixed this issue entirely. Thanks!

**Comment by kennethreitz** [comment]
fantastic news!
