### ISSUE TITLE
collectstatic fails with latest buildpack (v96) but works with v83

### ISSUE THREAD

**Issue by fomojola** [heroku/heroku-buildpack-python#351]
Recently pushed a new version of my Django app, and experienced the following error:

```
remote:      $ python manage.py collectstatic --noinput
remote:        Traceback (most recent call last):
remote:          File "manage.py", line 36, in <module>
remote:            execute_from_command_line(sys.argv)
remote:          File "/app/.heroku/python/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
remote:            utility.execute()
remote:          File "/app/.heroku/python/lib/python2.7/site-packages/django/core/management/__init__.py", line 377, in execute
remote:            self.fetch_command(subcommand).run_from_argv(self.argv)
remote:          File "/app/.heroku/python/lib/python2.7/site-packages/django/core/management/base.py", line 288, in run_from_argv
remote:            self.execute(*args, **options.__dict__)
remote:          File "/app/.heroku/python/lib/python2.7/site-packages/django/core/management/base.py", line 338, in execute
remote:            output = self.handle(*args, **options)
remote:          File "/app/.heroku/python/lib/python2.7/site-packages/django/core/management/base.py", line 533, in handle
remote:            return self.handle_noargs(**options)
remote:          File "/app/.heroku/python/lib/python2.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 168, in handle_noargs
remote:            collected = self.collect()
remote:          File "/app/.heroku/python/lib/python2.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 98, in collect
remote:            for path, storage in finder.list(self.ignore_patterns):
remote:          File "/app/.heroku/python/lib/python2.7/site-packages/django/contrib/staticfiles/finders.py", line 111, in list
remote:            for path in utils.get_files(storage, ignore_patterns):
remote:          File "/app/.heroku/python/lib/python2.7/site-packages/django/contrib/staticfiles/utils.py", line 27, in get_files
remote:            directories, files = storage.listdir(location)
remote:          File "/app/.heroku/python/lib/python2.7/site-packages/django/core/files/storage.py", line 270, in listdir
remote:            for entry in os.listdir(path):
remote:        OSError: [Errno 2] No such file or directory: '/app/appname/static'
```

Given I hadn't made any major changes in the app was quite surprised: this worked the last time I pushed it (November 7th). After some editing got it to stop making the error, but suddenly started seeing errors that collectstatic wasn't generating the actual output files (my app's slug size dipped from 100M to 78M). After some additional futzing around I got this fixed by forcing the buildpack version to match the last version I successfully pushed with using 

`heroku buildpacks:set https://github.com/heroku/heroku-buildpack-python#v83`

Looking at https://github.com/heroku/heroku-buildpack-python/compare/v83...v96 it appears that the BUILD_DIR is no longer set to /app (hence the above error). Previously my STATICFILES_DIR setting was this:

```
STATICFILES_DIRS = (
    os.path.join(APPPATH, 'appname/static'),
)
```

What should I use to properly comply with the requirements of v96 and later?

**Comment by ipmb** [comment]
The problem goes beyond just `collectstatic`. Doing the build in `/tmp/...` and then running the app from `/app` seems to be the source?

I can confirm that v83 is the last one that was functional for me.

Here's a minimal sample that exhibits the problem: https://gist.github.com/ipmb/4d8f2def75ef23f56944477349ce1ca2

Note the path for `__file__` on the script created by `setup.py` on the current buildpack  vs the actual location:

```
Running bash on ⬢ ll-test-build... up, run.8309 (Free)
~ $ which server.py
/app/.heroku/python/bin/server.py
~ $ cat `which server.py`
#!/app/.heroku/python/bin/python
# EASY-INSTALL-DEV-SCRIPT: 'build-test==1.0','server.py'
__requires__ = 'build-test==1.0'
__import__('pkg_resources').require('build-test==1.0')
__file__ = '/tmp/build_a5b88f1d3cffa5ad64ba2ef11e4ff8b7/server.py'
exec(compile(open(__file__).read(), __file__, 'exec'))
```

**Comment by kennethreitz** [comment]
Correct — you should not be referencing `/app` in your codebase.

**Comment by darklow** [comment]
I had same problem except I wasn't even seeing any errors, so I spent lot of time debugging and trying to figure out where `/app/static` disappeared, previously in `settings/production.py` I had:
```py
STATIC_ROOT = '/app/static'
MEDIA_ROOT = '/app/media'
```
Changing to following fixed the problem:
```py
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
```

And while building output is:
`112 static files copied to '/tmp/build/static', 112 post-processed.`
