### ISSUE TITLE
collectstatic does not run when using setup.py

### ISSUE THREAD

**Issue by davidism** [heroku/heroku-buildpack-python#359]
I am using `setup.py` instead of `requirements.txt` to specify my dependencies. The dependencies are installed correctly; however, the `collectstatic` step does not detect that Django is installed.

I verified this by adding `pip-grep requirements.txt django Django` to `bin/post_compile`. Since `requirements.txt` is generated and only contains `-e .` when using `setup.py`, `pip-grep` outputs `Not found.`.

This probably affects any other steps that rely on `pip-grep` to check dependencies.

**Comment by davidism** [comment]
Rather than parsing `requirements.txt`, it would be more straightforward to use `pkg_resources` to examine the actually installed distributions. Replace `pip-grep` with the following script.

~~~python
import sys
from pkg_resources import get_distribution, DistributionNotFound

try:
    get_distribution(sys.args[1])
except DistributionNotFound:
    sys.exit(1)
~~~

**Comment by davidism** [comment]
@kennethreitz was this fixed in a commit?

**Comment by davidism** [comment]
@kennethreitz this doesn't appear to be fixed. Why was this closed?

**Comment by kennethreitz** [comment]
sorry for closing without explanation — this is intentional.

**Comment by davidism** [comment]
Why is it intentional? [Heroku says that they support `setup.py`]( https://devcenter.heroku.com/articles/python-pip#traditional-distributions), but the tooling clearly doesn't in this case. The change would be backwards compatible while fulfilling the statement in the docs.
