### ISSUE TITLE
[Question/Suggestion] Unified Utils

### ISSUE THREAD

**Issue by dhilipsiva** [heroku/heroku-buildpack-python#360]
I see a lot of boilerplates for `indent`, `puts-cmd`, `puts-step`, etc. across may buildpack repos. Why not have a have these things in a separate repo called `heroku-buildpack-utils` (Or something similar) and have them in environment (in the docker image) be default? Or some other means of utilizing these functions. This will:

1. Reduce the amount of boilerplates Buildpack authors write.
2. Will standardize the conventions for the outputs.
3. Custom buildpack docs can be improved by incorporating these functions.

**Comment by dhilipsiva** [comment]
Apologies for creating an Issue for this matter. Did not know if this the right way to ask developers. Just had to ask this somewhere.

**Comment by kennethreitz** [comment]
We're working on it :)
