### ISSUE TITLE
Fails build whenever a `runtime.txt` is present

### ISSUE THREAD

**Issue by maxamante** [heroku/heroku-buildpack-python#361]
I'm trying to deploy a Python app to the `cedar-14` stack. Whenever I declare a `runtime.txt` file with either allowed runtime I get output similar to this (this is output from when I tried declaring the default runtime):
```
remote: Compressing source files... done.
remote: Building source:
remote:
remote: -----> Python app detected
remote: -----> Found python-2.7.13, removing
remote: -----> Installing python-2.7.13
remote: ) is not available for this stack (cedar-14).
remote:  !     Aborting.  More info: https://devcenter.heroku.com/articles/python-support
remote:  !     Push rejected, failed to compile Python app.
remote:
remote:  !     Push failed
remote: Verifying deploy...
```
When I remove the `runtime.txt` file, the deploy completes with no errors.

Thanks for the code otherwise!

**Comment by maxamante** [comment]
For the output above:
```
python-2.7.13
```

**Comment by edmorley** [comment]
I can repro if I create a runtime.txt that uses `CR` rather than `LF` line endings. Convert your runtime.txt to use Unix style line endings and make sure no leading/trailing unicode or other such problematic characters.

That said, I think the buildpack could be made more resilient to this, by either tweaking `IFS` [1] or more likely by trimming any whitespace via something like:
```
PYTHON_VERSION="$(cat runtime.txt | tr -d '[:space:]')"
```
(here: https://github.com/heroku/heroku-buildpack-python/blob/0b8741916676f70eb6537aa8da402fbdbe5292c7/bin/steps/python#L33)

[1] https://bash.cyberciti.biz/guide/$IFS

**Comment by cclauss** [comment]
Like a bad penny... https://github.com/heroku/heroku-buildpack-python/issues/186

**Comment by cclauss** [comment]
@edmorley Line 2 or line 33?

**Comment by edmorley** [comment]
Ah line 2, I copied from the wrong tab.

**Comment by kennethreitz** [comment]
no newlines!

**Comment by cclauss** [comment]
Why force humans to do what computers can do faster and better?  This issue has caught up several of us.  Why not just add a line or two of whitespace stripping code as an acknowledgement that we humans are imperfect.

**Comment by jmorrell** [comment]
I'll take a look at making this more robust to whitespace errors @cclauss. If nothing else it should at least warn you.

**Comment by edmorley** [comment]
The example in https://github.com/heroku/heroku-buildpack-python/issues/361#issuecomment-282852084 worked when I tried a few known broken cases locally, if that helps?

**Comment by kennethreitz** [comment]
https://github.com/heroku/heroku-buildpack-python/commit/df52fd46e5b357503601d0f336c7fccb31b1f68b

**Comment by kennethreitz** [comment]
this is fixed in master
