### ISSUE TITLE
Pip/setuptool version updates leave old installs behind

### ISSUE THREAD

**Issue by edmorley** [heroku/heroku-buildpack-python#362]
eg:
```
$ heroku run bash
Running bash on REMOVED... up, run.3117 (Standard-1X)
~ $ ls -ld .heroku/python/lib/python2.7/site-packages/pip-*
drwx------ 4 u56615 dyno 4096 Mar  2 19:21 .heroku/python/lib/python2.7/site-packages/pip-8.1.2-py2.7.egg
drwx------ 4 u56615 dyno 4096 Mar  2 19:21 .heroku/python/lib/python2.7/site-packages/pip-9.0.1-py2.7.egg
~ $ ls -l .heroku/python/lib/python2.7/site-packages/setuptools-*th
-rw------- 1 u56615 dyno 492154 Mar  2 19:21 .heroku/python/lib/python2.7/site-packages/setuptools-25.2.0-py2.7.egg
-rw------- 1 u56615 dyno 792919 Mar  2 19:21 .heroku/python/lib/python2.7/site-packages/setuptools-32.1.0-py2.7.egg
```

In our case the cache had been purged not that long ago, however I imagine some users (who haven't recently changed their python version or manually run purge_cache) will have many more installs. Each old install is about 7MB.

pip/setuptools are currently installed via `python setup.py install`, which doesn't handle uninstallation:
https://github.com/heroku/heroku-buildpack-python/blob/66f5a66740a7d30ed2d4250fefdc547a0037e800/bin/steps/python#L49-L75

Other than say switching to `get-pip.py` instead of `setup.py install`ing the archive (which is probably not desired for a few reasons), I think the best solution might just be to run this as part of that install block, prior to installing the new version:
```bash
rm -fr .heroku/python/lib/python2.7/site-packages/pip-*
rm -fr .heroku/python/lib/python2.7/site-packages/setuptools-*
```

**Comment by edmorley** [comment]
For anyone curious as to whether this was fixed or wontfixed (since there was no comment), it was fixed by:
https://github.com/heroku/heroku-buildpack-python/commit/09b7e448410b08e96a763fa1c73178e2ff5dddd3

(This was non-obvious, since the commit message was "fix tests" and it was landed directly to master without using pull requests, and GitHub doesn't email people watching the repo about direct commits to master.)

**Comment by kennethreitz** [comment]
this fixed a problem i was having today, thanks!

**Comment by edmorley** [comment]
You're welcome!

This can now be closed, fixed by:
https://github.com/heroku/heroku-buildpack-python/commit/65648fb7a802078e125f4e0926b2042ba1f55b11#diff-57a28f8b2bf70b3efa895ae239e9d986R61
