### ISSUE TITLE
Hook required post_promte or post_deploy

### ISSUE THREAD

**Issue by wooyek** [heroku/heroku-buildpack-python#367]
The hook post_compile is great to do things like database migrations, but when it's used that way you cannot fully automate heroku pipelines because post_compile wont be run on `heroku pipelines:promote`.

Is it possible to add a hook for deploy or promote?

**Comment by edmorley** [comment]
You're in luck! Heroku has a relatively new feature, "release phase" that allows for running such tasks:
https://devcenter.heroku.com/articles/release-phase

For example usage, see:
https://github.com/mozilla/treeherder/blob/2b0ef8a6ddd1df50ec8a01e69d35324934e87afe/Procfile#L15
https://github.com/mozilla/treeherder/blob/2b0ef8a6ddd1df50ec8a01e69d35324934e87afe/bin/pre_deploy

**Comment by wooyek** [comment]
Splendid!
