### ISSUE TITLE
Upgrade pypy to 5.7.1

### ISSUE THREAD

**Issue by alex** [heroku/heroku-buildpack-python#377]
http://doc.pypy.org/en/latest/release-v5.7.1.html

**Comment by kfwls** [comment]
+1

5.7 is available for python2, but not python3

https://devcenter.heroku.com/articles/python-runtimes#available-runtimes

**Comment by cclauss** [comment]
https://github.com/heroku/heroku-buildpack-python/pull/331#issuecomment-250023790

**Comment by kfwls** [comment]
This is a beta release

http://doc.pypy.org/en/latest/release-v5.7.1.html

**Comment by kennethreitz** [comment]
There is such a shockingly low amount of PyPy usage on the platform that I may stop updating PyPy as often as the other runtimes.

**Comment by kennethreitz** [comment]
Closing for #370

**Comment by kennethreitz** [comment]
deployed to both stacks!

**Comment by kfwls** [comment]
Excellent, thanks!

**Comment by kfwls** [comment]
The python3 version hasn't actually been added - only python2.

**Comment by kennethreitz** [comment]
@kfwls deployed now.
