### ISSUE TITLE
Heroku-16 Python runtime archives contain additional packages (boto/bob/...)

### ISSUE THREAD

**Issue by edmorley** [heroku/heroku-buildpack-python#379]
The cedar-14 Python runtime archive does not contain any already installed packages:
```bash
$ curl -sSf https://lang-python.s3.amazonaws.com/cedar-14/runtimes/python-2.7.13.tar.gz  | tar -zt  --wildcards '*/site-packages/*.py'
tar: */site-packages/*.py: Not found in archive
tar: Exiting with failure status due to previous errors
```

However the Heroku-16 equivalent does:
```
$ curl -sSf https://lang-python.s3.amazonaws.com/heroku-16/runtimes/python-2.7.13.tar.gz | tar -zt  --wildcards '*/site-packages/*.py'
lib/python2.7/site-packages/docopt.py
lib/python2.7/site-packages/boto/storage_uri.py
lib/python2.7/site-packages/boto/requestlog.py
lib/python2.7/site-packages/boto/auth_handler.py
...
lib/python2.7/site-packages/bob/cli.py
lib/python2.7/site-packages/bob/utils.py
lib/python2.7/site-packages/bob/models.py
...
lib/python2.7/site-packages/pip-8.1.2-py2.7.egg/pip/cmdoptions.py
lib/python2.7/site-packages/pip-8.1.2-py2.7.egg/pip/wheel.py
lib/python2.7/site-packages/pip-8.1.2-py2.7.egg/pip/status_codes.py
...
lib/python2.7/site-packages/envoy/core.py
lib/python2.7/site-packages/envoy/__init__.py
```

There are appear to be other files present that were not in cedar-14, eg:
```
requirements-declared.txt
requirements-installed.txt
requirements-stale.txt
```

I'm guessing the method used to build the archives has accidentally bundled parts of this buildpack's development environment into the archive?

**Comment by edmorley** [comment]
There also appear to be some 2.7.12 related files in the 2.7.13 Heroku-16 archive, eg:
```
lib/python2.7/lib-dynload/Python-2.7.12-py2.7.egg-info
lib/python2.7/lib2to3/Grammar2.7.12.final.0.pickle
lib/python2.7/ensurepip/_bundled/pip-8.1.1-py2.py3-none-any.whl
```

I'm presuming the builds were generated sequentially in the same environment, and perhaps these are leftover files from the previous build?

**Comment by kennethreitz** [comment]
I have noticed this as well. It doesn't seem to be problematic yet (especially since those packages automatically get uninstalled on first push), but I would like to figure out what is causing this and remove them. 

Builds for `heroku-16` are done with the Docker runtime, instead of with the standard platform. That's the only difference.

**Comment by edmorley** [comment]
> Builds for heroku-16 are done with the Docker runtime, instead of with the standard platform.

Do you mean:
* for cedar-14 the steps used were those documented [here](https://github.com/heroku/heroku-buildpack-python/blob/master/builds/README.md)?
* for heroku-16 the Dockerfile in the root of this repo is used to generate the builds? eg something like:
```
$ docker build . -t heroku-buildpack-python-dev
...
Successfully built 6e4db1d7371c
Successfully tagged heroku-buildpack-python-dev:latest

$ docker run -it heroku-buildpack-python-dev
root@e090f86d92d3:/app# bob build runtimes/python-2.7.13
...
```

Unfortunately I can't complete a build using bob-builder, since even if I set `S3_BUCKET=lang-python`, and then force the boto connection to be anonymous (eg `sed -i 's/boto.connect_s3()/boto.connect_s3(anon=True)/' /usr/local/lib/python2.7/dist-packages/bob/models.py` inside that docker container), I get:
`WARNING: Archive libraries/sqlite.tar.gz does not exist.`

One thing I did spot was that both the `requirements.txt` in the root of this repo and the `Dockerfile` use `bob-builder==0.0.5`, when the latest is `0.0.12` and the newer releases include a fix to remove the build directory before building, if it already exists:
https://github.com/kennethreitz/bob-builder/compare/v0.0.5...v0.0.12
-> https://github.com/kennethreitz/bob-builder/commit/de2a44e31093e7682da363606eeb7edaf989ae57

> especially since those packages automatically get uninstalled on first push

I don't think this is happening?

```bash
$ echo 'requests' > requirements.txt
$ git init
Initialized empty Git repository in C:/Users/Ed/src/python-test/.git/
$ git add -A
$ git commit -m 'foo'
...

$ heroku create --buildpack heroku/python --stack heroku-16
Creating app... done, aqueous-thicket-92110, stack is heroku-16
Setting buildpack to heroku/python... done
https://aqueous-thicket-92110.herokuapp.com/ | https://git.heroku.com/aqueous-thicket-92110.git

$ git push heroku master
...
remote: -----> Installing requirements with pip
remote:        Collecting requests (from -r /tmp/build_19fe2fa648d7c6d9f6a9c9e852c05d72/requirements.txt (line 1))
remote:          Downloading requests-2.14.2-py2.py3-none-any.whl (560kB)
remote:        Installing collected packages: requests
remote:        Successfully installed requests-2.14.2
remote:
remote: -----> Discovering process types
...
remote: Verifying deploy... done.

$ heroku run ls -1d .heroku/python/lib/python2.7/site-packages/*/
Running ls -1d .heroku/python/lib/python2.7/site-packages/*/ on aqueous-thicket-92110... up, run.5856 (Free)
.heroku/python/lib/python2.7/site-packages/appdirs-1.4.3.dist-info/
.heroku/python/lib/python2.7/site-packages/bob/
.heroku/python/lib/python2.7/site-packages/bob_builder-0.0.5-py2.7.egg-info/
.heroku/python/lib/python2.7/site-packages/boto/
.heroku/python/lib/python2.7/site-packages/boto-2.42.0.dist-info/
.heroku/python/lib/python2.7/site-packages/docopt-0.6.2-py2.7.egg-info/
.heroku/python/lib/python2.7/site-packages/envoy/
.heroku/python/lib/python2.7/site-packages/envoy-0.0.3.dist-info/
...
```

**Comment by edmorley** [comment]
> Unfortunately I can't complete a build using bob-builder, since even if I ...

Ah I was missing the `S3_PREFIX="heroku-16/"`. If you could confirm that a local docker image is what is used to build for Heroku-16, I'll open a PR to update the docs in `builds/README.md`.

**Comment by edmorley** [comment]
> especially since those packages automatically get uninstalled on first push

Ah - I've opened #393 since it turns out pip-uninstall is not working.

Now that the docker image uses a newer bob-builder (#387), newly generated archives shouldn't contain any stale files. However any existing heroku-16 apps will contain them, so I was thinking of opening a PR to bust the build cache (like happens for a new python version) if eg the `bob_builder-0.0.5-py2.7.egg-info` directory was found.

**Comment by edmorley** [comment]
Using this:
```bash
VERSIONS=(2.7.9 2.7.10 2.7.11 2.7.12 2.7.13 3.5.2 3.5.3 3.6.0 3.6.1)
for version in ${VERSIONS[@]}; do
    url="https://lang-python.s3.amazonaws.com/heroku-16/runtimes/python-${version}.tar.gz"
    echo -e "\n${url}"
    curl -sSfL "$url" | tar -zt | egrep '(requirements-|bob/|envoy/|_bundled|Python-[23])'| sed "s/^/ -> /"
done
```

Generated:
https://emorley.pastebin.mozilla.org/9024396

...which means the list of runtimes that need regenerating for Heroku-16 are:
* python-2.7.9
* python-2.7.10
* python-2.7.11
* python-2.7.12
* python-2.7.13

@kennethreitz, if you could regenerate those at some point, I'll then open a PR to detect existing apps that contain the stale files and force a Python environment refresh (like happens when the Python version for an app changes).

**Comment by kennethreitz** [comment]
@edmorley that would cause a lot of pain for a lot of customers — i think it would be better to leave the files be, unfortunately. I'll work on regenerating the binaries, however.

**Comment by edmorley** [comment]
> that would cause a lot of pain for a lot of customers — i think it would be better to leave the files be, unfortunately.

I was thinking along the lines of requiring all of the following to be true:
* stack=heroku-16
* using one of those specific Python 2.7.x versions
* site-packages contains both bob-builder=0.0.5 and envoy==0.0.3

...which is pretty specific, and would only catch heroku-16 early-upgraders.

Is the pain due to customers not pinning Python requirements, so not having them cached could pull in a newer version? On a separate note, I wonder if it's worth making the buildpack warn if people haven't pinned dependencies?

**Comment by kennethreitz** [comment]
well bob-builder and envoy get automatically uninstalled, so it's not a huge deal.

**Comment by edmorley** [comment]
For apps created since #397 landed (which fixed #393), yes. However for older apps, their `requirements-declared.txt` will have already been overwritten several times over, so bob/envoy/... won't be uninstalled.

**Comment by edmorley** [comment]
Anyway, I understand it's safer to leave them as is, and it doesn't affect me, since I can always clear the cache manually :-)

**Comment by edmorley** [comment]
With the fix for this as well as #425, for Python 2.7.13 the improvements are considerable...
* Size: 157MB -> 91MB
* File count: 6678 -> 2345

**Comment by edmorley** [comment]
> I'll work on regenerating the binaries, however.

@kennethreitz, I don't suppose you know when you might be able to do this? The binaries that need regenerating for Heroku-16 are:
* python-2.7.9
* python-2.7.10
* python-2.7.11
* python-2.7.12
* python-2.7.13

Many thanks :-)

> well bob-builder and envoy get automatically uninstalled

Sadly only bob-builder is uninstalled and not also {boto, envoy, docopt}:
```
-----> Uninstalling stale dependencies
       Uninstalling bob-builder-0.0.5:
         Successfully uninstalled bob-builder-0.0.5
-----> Installing requirements with pip
```
(See https://dashboard.heroku.com/apps/treeherder-prototype/activity/builds/19c9f181-64ce-4108-9a60-24b2f3256b60)

**Comment by kennethreitz** [comment]
Ah, interesting observation! That motivates me to rebuild. Thanks for the info.

**Comment by kennethreitz** [comment]
Deployed! ✨🍰✨

**Comment by edmorley** [comment]
Many thanks! All of the versions [here](https://github.com/heroku/heroku-buildpack-python/issues/379#issuecomment-316703334) are now fixed - apart from one: 2.7.12.

I don't suppose you could upload that last one? :-)

**Comment by kennethreitz** [comment]
Rebuilding

**Comment by kennethreitz** [comment]
deployed

**Comment by edmorley** [comment]
All good now - many thanks!
