### ISSUE TITLE
Collectstatic failure : /bin/steps/collectstatic: line 12: [: -eq: unary operator expected

### ISSUE THREAD

**Issue by dbarbeau** [heroku/heroku-buildpack-python#380]
Hello,

I am trying to deploy a django app and expected the collectstatic command to be called. It seems heroku tries but fails, as can be seen in this snippet

```
-----> Done

/app/tmp/buildpacks/[huge_hash_snip]/bin/steps/collectstatic: line 12: [: -eq: unary operator expected

-----> Discovering process types

       Procfile declares types -> defaultworker, web

-----> Compressing...
```

We don't seem to have any sort of custom code kicking in at this point. Could this be an error in Heroku's scripts? Or have you any clues on what could be causing such an error?

**Comment by kennethreitz** [comment]
That's very interesting, the line in question appears to be [this one](https://github.com/heroku/heroku-buildpack-python/blob/master/bin/steps/collectstatic#L12), which is an empty line

**Comment by kennethreitz** [comment]
I haven't heard of this error from anyone else, so it may have just been a glitch, somehow.

**Comment by kennethreitz** [comment]
I'm going to close this, since it hasn't been brought up by anyone else yet. @dbarbeau can you comment if this is still happening?

**Comment by dbarbeau** [comment]
Hello, in the rush we worked around the issue. I will try to restablish normal behaviour and keep you updated soon. Thank you!
