### ISSUE TITLE
Test output for 'assertCapturedSuccess' assertions hides the cause

### ISSUE THREAD

**Issue by edmorley** [heroku/heroku-buildpack-python#389]
Master is currently failing on Travis, with output:
```
...
testPipenv
ASSERT:Expected captured exit code to be 0; was <2> expected:<0> but was:<2>
testPipenvVersion
ASSERT:Expected captured exit code to be 0; was <2> expected:<0> but was:<2>
testNoRequirements
testNLTK
testSetupPy
testStandardRequirements
testPsycopg2
testPython2
testPython3
```
(See: https://travis-ci.org/heroku/heroku-buildpack-python/jobs/235746031)

Currently:
* neither stdout nor stderr are output (albeit this particular case would also need the fix for #388 too)
* the assertion message is a bit repetitive

I'll open a PR.

**Comment by kennethreitz** [comment]
thank you!
