### ISSUE TITLE
The pip-uninstall step is always a no-op

### ISSUE THREAD

**Issue by edmorley** [heroku/heroku-buildpack-python#393]
The pip-uninstall step aims to uninstall any stale packages from the buildpack python site-packages directory:
https://github.com/heroku/heroku-buildpack-python/blob/master/bin/steps/pip-uninstall

Unfortunately at the moment this isn't working since the sequence of steps are:
* Run `bin/steps/pip-install`, which:
  - runs pip install
  - makes a copy of the app's requirements.txt at `.heroku/python/requirements-declared.txt`
  - saves the output from `pip freeze` to `.heroku/python/requirements-installed.txt`
* Run `bin/steps/pip-uninstall`, which:
  - uses pip-diff to compare `.heroku/python/requirements-declared.txt` against `requirements.txt`, and generate a list of stale requirements
  - passes that list to `pip uninstall`

...which means that `requirements-declared.txt` used by the uninstall step is created by that run's install step (rather than the previous build), so is always identical to `requirements.txt`, so no packages are ever uninstalled.

This worked previously, since the pip-uninstall script was run prior pip-install - but the order was reversed in:
https://github.com/heroku/heroku-buildpack-python/commit/f27a84e0155c7752630aae6c93e230d2a24a880a

I also spotted that:
* `requirements-installed.txt` (the output from `pip freeze`) is never used
* even with the above fixed, the uninstall process wouldn't handle apps that have includes in `requirements.txt` (eg `-r requirements/foo.txt`). 
  - One way to fix this is to try and flattern the requirements chain using the pip API, like pip-diff already does, or else to make use of the sync command from [pip-tools](https://github.com/jazzband/pip-tools/blob/master/piptools/sync.py).
  - Though understand this might be a "wontfix and add to docs" case, since apps are encouraged to use a single requirements file at the root of the repo.

I'll take more of a look at this when I'm back next week :-)

**Comment by kennethreitz** [comment]
Thanks for reporting this!

**Comment by kennethreitz** [comment]
@edmorley I changed the ordering here again.

**Comment by edmorley** [comment]
> @edmorley I changed the ordering here again.

Indeed! Fixed by:
https://github.com/heroku/heroku-buildpack-python/pull/397/files#diff-c7b43338c09c3c9afd420fd8b6bb5198R174

I've split out the remaining parts of this to #411 and #412.

Many thanks!

**Comment by edmorley** [comment]
> Indeed! Fixed by:
> https://github.com/heroku/heroku-buildpack-python/pull/397/files#diff-c7b43338c09c3c9afd420fd8b6bb5198R174

Ah actually I spoke too soon. That PR was reverted in #404.
I've opened PR #413 to re-fix this and add a test.
