### ISSUE TITLE
Support for collect static with flask assets

### ISSUE THREAD

**Issue by sharoonthomas** [heroku/heroku-buildpack-python#394]
The build pack currency checks explicitly if it's a DJANGO app. To use this with Flask-Assets, my understanding is that you have to write a custom buildpack.

If there was a way to force running something like `python manage.py collectstatic`, a command could be added to a flask app with the same name and static assets collection would be possible with flask too?

**Comment by edmorley** [comment]
Another option is to add a script at `bin/post_compile` within the app's source directory, which will be run by the buildpack after the compile. See:
https://github.com/heroku/heroku-buildpack-python/tree/master/bin/steps/hooks

**Comment by sharoonthomas** [comment]
That works too.

Closing the ticket.

For anyone coming here in future:

1. Create a new file `bin/post_compile`
2. Add the following for flask-assets`python manage.py assets clean && python manage.py assets build`
