### ISSUE TITLE
requirements 'parser' discards lines with leading space

### ISSUE THREAD

**Issue by jayvdb** [heroku/heroku-buildpack-python#400]
pip requirements format allows leading spaces.
This 'parser' will discard those lines:
https://github.com/heroku/heroku-buildpack-python/pull/397/files#r119177564

**Comment by kennethreitz** [comment]
Thanks for the report! Want to send a PR?

**Comment by jayvdb** [comment]
Not sure that I could, as I think this requires someone more familiar with the codebase and userbase and roadmap than I.
I would be very inclined to drop the custom parser and a common requirements parsing library, as I am sure that this custom parser has other bugs but havent had time to confirm that.  Leading spaces was just the most obvious bug.

**Comment by cclauss** [comment]
@jayvdb You have the knowledge to submit a PR...  Just `line.strip()` (with no parameters) before any other processing.  This will get rid of the leading whitespace as well as the pesky '\n' at the end of every line.

**Comment by kennethreitz** [comment]
Now that setuptools has shipped a fix for this, we'll be able to remove this code.

**Comment by kennethreitz** [comment]
This code was temporary and was removed.
