### ISSUE TITLE
Python builds not working on CI since #e8a79bbda5f2563300b7e5bc280ee4005629243f

### ISSUE THREAD

**Issue by guybowden** [heroku/heroku-buildpack-python#401]
I've just run into an issue whereby my app which was building fine on Monday is now not building:

My runtime.txt is set to 2.7.10

My buildpack was set to `https://github.com/heroku/heroku-buildpack-python.git` - have also tried with `https://github.com/heroku/heroku-buildpack-python.git#v103` & `https://github.com/heroku/heroku-buildpack-python.git#v104` 

CI fails as when pip tries to install a requirement that imports six. 

However, if I set the buildpack to use #e8a79bbda5f2563300b7e5bc280ee4005629243f, things work. 

Happy to supply more info as requested.

**Comment by amureki** [comment]
@guybowden hi! 
This is not related to buildpack, but to the setuptools: https://github.com/pypa/setuptools/issues/1042

And it was already fixed, so builds should be fine now.

**Comment by kennethreitz** [comment]
@amureki thanks for the update!
