### ISSUE TITLE
requirements-installed.txt is never used

### ISSUE THREAD

**Issue by edmorley** [heroku/heroku-buildpack-python#411]
Broken out of #393.

During the `pip-install` script, `pip freeze` is run and the output saved to `requirements-installed.txt`. However this file is currently unused. (I'm presuming it was a leftover from an alternative pip-uninstall implementation, which compares to the installed packages list rather than requirements files.

https://github.com/heroku/heroku-buildpack-python/blob/master/bin/steps/pip-install
https://github.com/heroku/heroku-buildpack-python/blob/master/bin/steps/pip-uninstall
https://github.com/heroku/heroku-buildpack-python/search?q=requirements-installed.txt

**Comment by kennethreitz** [comment]
requirements-installed is used out-of-band by the platform.

**Comment by kennethreitz** [comment]
e.g. it's just useful metadata

**Comment by edmorley** [comment]
Oh right. It's just the comment immediately above it says "Smart Requirements handling". When I get a second I'll add a comment/whitespace to make that clearer (unless someone else beats me to it).
