### ISSUE TITLE
Add support to pip-uninstall for included/cascading requirements files

### ISSUE THREAD

**Issue by edmorley** [heroku/heroku-buildpack-python#412]
Broken out of #393.

For apps that use includes in their requirements files, `pip-uninstall` currently doesn't work.

For example:
```
# requirements.txt
-r requirements/main.txt
```

```
# requirements/main.txt
requests==2.7.13
gunicorn==19.7.1
```

If later `main.txt` were edited to remove `gunicorn`, pip-uninstall only uses the saved `requirements-declared.txt` file (which was copied from `requirements.txt`), which doesn't retain all of the old state. See:
https://github.com/heroku/heroku-buildpack-python/blob/master/bin/steps/pip-uninstall
https://github.com/heroku/heroku-buildpack-python/blob/master/bin/steps/pip-install

One solution to this would be to add a `pip-export` command (to go alongside `pip-diff`), which acts a bit like `pip freeze`, except it's source data is requirements files rather than the local site-packages. This would effectively allow saving a flattened requirements list to `requirements-declared.txt`, thereby not losing any state.

This is likely a "patches welcome" type of request, but in the meantime it might be worth adding a warning about lack of pip-uninstall support to:
https://devcenter.heroku.com/articles/python-pip#cascading-requirements-files

**Comment by kennethreitz** [comment]
Patches would be well-recieved, but they would also have to be battle-tested before being merged. We used to have this functionality, and it was problematic. People have *crazy* requirements files.

**Comment by kennethreitz** [comment]
No plans to support this, as we're moving towards `Pipfile`.
