### ISSUE TITLE
Please enable 'sub-env' at the pip install step

### ISSUE THREAD

**Issue by LegoStormtroopr** [heroku/heroku-buildpack-python#416]
This is basically to support installing from private repos without having to expose credentials.

I want to add an API token for GitLab or GitHub into my heroku dashboard and have that used to install a private repo, like so:

```
setup(
    install_requires=[
        'my_private_library'
    ],
    dependency_links=[
        'git+https://%s@gitlab.com/private/private.git#egg=my_private_library-1.2.3'%os.environ.get('GITLAB_TOKEN'), 
    ]
)
```

With a `requirements.txt` like this:
```
--process-dependency-links
-e .
```

Everything works fine locally, if I do: `GITLAB_TOKEN=my_secret_key pip install -r requirements.txt`

But on heroku, the environment variable isn't available.

I'll submit a PR soon, but am open to feedback.

**Comment by kennethreitz** [comment]
closing for https://github.com/heroku/heroku-buildpack-python/pull/417

**Comment by edmorley** [comment]
Thinking about this, I wonder if you could instead use a `.netrc` to pass the credentials?
This could be populated using just this buildpack via a `bin/pre_compile` file in your repository that pulled the token out of the app environment variables (this is run by the buildpack [here](https://github.com/heroku/heroku-buildpack-python/blob/master/bin/steps/hooks/pre_compile)).

Alternatively an additional buildpack could be added prior to the Python one, based on this netrc one for GitHub (perhaps they'd accept PRs to add GitLab support?):
https://github.com/timshadel/heroku-buildpack-github-netrc

**Comment by kennethreitz** [comment]
Pip uses Requests, which in turn supports netrc (unless they've disabled it).

**Comment by LegoStormtroopr** [comment]
I've finally got around to looking at this, and using a pre_compile hook to popular `.netrc` was perfect (and much better than attempts I'd already tried).

Thanks again everyone!

**Comment by edmorley** [comment]
Ah that's great! Thank you for confirming that works :-)
