### ISSUE TITLE
migrate fails but deploy succeeds

### ISSUE THREAD

**Issue by EmSyndio** [heroku/heroku-buildpack-python#419]
I am having an issue where one of my migrations fails (still trying to figure why)
but mostly critical is that even though it failed, the deploy succeeds and my app is now broken on prod!

I'm looking for help debugging the migration on heroku, because I only get a stack trace with an ImpotError which doesn't make sense to me since a prior migration uses the same import and seems to work.

How do I activate DEBUG mode for the buildpack? Or at least get further information on what's happening during this migration.

And then, what should be done to prevent the build from being deployed on such failure.
Thanks

**Comment by EmSyndio** [comment]
added the migration step in the Procfile 
release: python manage.py migrate --noinput

and then it fails to deploy.
but migrate is ran in the build command, and errors are not caught there.

**Comment by edmorley** [comment]
Migrate should never be run during the buildpack compile, only as part of the [release-phase](https://devcenter.heroku.com/articles/release-phase) release command. 

> but migrate is ran in the build command, and errors are not caught there.

How do you mean? Are you using the `bin/post_compile` hook/script?

**Comment by EmSyndio** [comment]
@edmorley migration runs on the build phase for sure.
I think this is ne from this PR https://github.com/heroku/heroku-buildpack-python/pull/358

**Comment by EmSyndio** [comment]
My issues seems to be due to a mismatch in Postgres version.
I'm working on that part. Nevertheless, as I mentioned, the build 'succeeds' when it shouldn't.

**Comment by EmSyndio** [comment]
My bad, i guess the PR mentioned was closed.
Yet my migrations are running on build, so not sure where this is coming from.

**Comment by edmorley** [comment]
A pastebin of the build log might make things clearer?

**Comment by EmSyndio** [comment]
> -----> Running post-compile hook
> Operations to perform:
>   Synchronize unmigrated apps: django_user_agents, s3_folder_storage, django_rq, gunicorn, staticfiles, messages, django_otp, syndio_admin, compressor, data_manager, storages, hijack
>   Apply all migrations: logs, generic_source, admin, sessions, auth, metrics, contenttypes, survey, dashboard, django_agent_trust, syndio_main, otp_totp, settings, emails, user
> Synchronizing apps without migrations:
>   Creating tables...
>     Running deferred SQL...
>   Installing custom SQL...
> Running migrations:
>   Rendering model states... DONE
>   Applying settings.0006_field_definitions... OK
>   Applying survey.0008_new_survey... OK
>   Applying survey.0009_survey_migrate... OK
>   Applying survey.0010_survey_gen_modules... OK
>   Applying survey.0011_survey_update... OK
>   Applying survey.0012_survey_answer_migration...Traceback (most recent call last):
>   File "manage.py", line 13, in <module>
>     execute_from_command_line(sys.argv)
>   File "/app/.heroku/python/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
>     utility.execute()
>   File "/app/.heroku/python/lib/python2.7/site-packages/django/core/management/__init__.py", line 346, in execute
>     self.fetch_command(subcommand).run_from_argv(self.argv)
>   File "/app/.heroku/python/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
>     self.execute(*args, **cmd_options)
>   File "/app/.heroku/python/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
>     output = self.handle(*args, **options)
>   File "/app/.heroku/python/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 222, in handle
>     executor.migrate(targets, plan, fake=fake, fake_initial=fake_initial)
>   File "/app/.heroku/python/lib/python2.7/site-packages/django/db/migrations/executor.py", line 110, in migrate
>     self.apply_migration(states[migration], migration, fake=fake, fake_initial=fake_initial)
>   File "/app/.heroku/python/lib/python2.7/site-packages/django/db/migrations/executor.py", line 148, in apply_migration
>     state = migration.apply(state, schema_editor)
>   File "/app/.heroku/python/lib/python2.7/site-packages/django/db/migrations/migration.py", line 115, in apply
>     operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
>   File "/app/.heroku/python/lib/python2.7/site-packages/django/db/migrations/operations/special.py", line 183, in database_forwards
>     self.code(from_state.apps, schema_editor)
>   File "/tmp/build_c6b8b5756082056d72b36026dfe491fc/syndio-cv-16e68a1ad5a34b5dbb5b468a0b6a0230fa4a47c5/survey/migrations/0012_survey_answer_migration.py", line 84, in migrate_answers
>     schema_editor.execute(SQL)
>   File "/app/.heroku/python/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 111, in execute
>     cursor.execute(sql, params)
>   File "/app/.heroku/python/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
>     return self.cursor.execute(sql, params)
>   File "/app/.heroku/python/lib/python2.7/site-packages/django/db/utils.py", line 98, in __exit__
>     six.reraise(dj_exc_type, dj_exc_value, traceback)
>   File "/app/.heroku/python/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
>     return self.cursor.execute(sql, params)
> django.db.utils.ProgrammingError: syntax error at or near "not"
> LINE 20: create unique index if not exists survey_answer_pkey

**Comment by edmorley** [comment]
Your repo has a `bin/post_compile` file, which the buildpack is running:

> -----> Running post-compile hook

You should remove migrate from that file, since the buildpack compile should not affect external services (only eg files that end up in the slug). For more reasoning, see: https://github.com/heroku/heroku-buildpack-python/pull/358#issuecomment-276041951

**Comment by EmSyndio** [comment]
@edmorley ahhh. OK got it. I didn't even know we had this there...
I thought the post compile was from the buildpack

**Comment by EmSyndio** [comment]
Thanks. will update. I guess this has been there for longer than the feature has been available.

**Comment by edmorley** [comment]
The buildpack has some hooks that allow for custom scripts to be run before/after compile if the relevant file is present in the source repo:
https://github.com/heroku/heroku-buildpack-python/tree/master/bin/steps/hooks

For the right use-cases these are super handy, for example:
* installing additional libraries before compile, that are needed for pip to be able to build a package
* running additional UI building steps after the buildpack has run django collectstatic (eg the whitenoise compress tool to generate the gzip and brotli versions of static assets)

Release phase on the other hand is useful for:
* database migrations
* reporting deploys to services not supported by the Heroku deploy hooks
* running Django system checks (`./manage.py check --deploy`), which run against the DB instance in question

**Comment by edmorley** [comment]
Also, to ensure the build still fails if one of your custom commands in `bin/post_compile` fails, make sure to enable bash exit-on-error:
http://redsymbol.net/articles/unofficial-bash-strict-mode/

...otherwise the exit code of the script will be that of the last command run within it, which in this case was presumably something other than the migrate command.

**Comment by EmSyndio** [comment]
So, I moved the script to 'release' but it doesn't seem to run.
I didn't notive at first because migrations had run already, but after adding a new migration, these don't get ran.

How comes release is not running?

**Comment by edmorley** [comment]
Could you pastebin the deploy log and also your Procfile? (Plus if the Procfile references another script, pastebin that too)

**Comment by edmorley** [comment]
@EmSyndio can this be closed now?

**Comment by kennethreitz** [comment]
Thanks for the help @edmorley :) ✨🍰✨
