### ISSUE TITLE
Memory amount for DYNO_RAM on Performance-L Dynos should be `14000`

### ISSUE THREAD

**Issue by phil** [heroku/heroku-buildpack-python#421]
https://github.com/heroku/heroku-buildpack-python/blob/84f2fb5396469f5c9532806a17da70d682fd7a47/vendor/WEB_CONCURRENCY.sh#L25

**Comment by kennethreitz** [comment]
fixed by https://github.com/heroku/heroku-buildpack-python/pull/446
