### ISSUE TITLE
Exclude Python's test suite from generated Python archives

### ISSUE THREAD

**Issue by edmorley** [heroku/heroku-buildpack-python#424]
The output from a build of Python using default options includes Python's own test suite, which is significant in size compared to Python itself. As such, the official Docker Python images strip the test suite directories after building Python:
https://github.com/docker-library/python/blob/761d766baa0ff33754436c0a1fd9aedc68cf7947/Dockerfile-debian.template#L54

As such, it makes sense for this buildpack to do the same, to reduce slug size and for parity with the Docker Python images.

The affected directories can be listed using:
`find .heroku/python/ \( -type d -a \( -name test -o -name tests \) \)`

For Python 3.6.2 this matches:
```
.heroku/python/lib/python3.6/tkinter/test
.heroku/python/lib/python3.6/ctypes/test
.heroku/python/lib/python3.6/unittest/test
.heroku/python/lib/python3.6/distutils/tests
.heroku/python/lib/python3.6/sqlite3/test
.heroku/python/lib/python3.6/lib2to3/tests
.heroku/python/lib/python3.6/test
```

...and removing them decreases the build size by 34%:
```
$ bob build runtimes/python-3.6.2
...
$ du -sh .heroku/python/
184M    .heroku/python/
$ find .heroku/python/ \( -type d -a \( -name test -o -name tests \) \) -exec rm -rf '{}' +
$ du -sh .heroku/python/
121M    .heroku/python/
```

Similarly for Python 2.7.13 this matches:
```
.heroku/python/lib/python2.7/ctypes/test
.heroku/python/lib/python2.7/unittest/test
.heroku/python/lib/python2.7/distutils/tests
.heroku/python/lib/python2.7/bsddb/test
.heroku/python/lib/python2.7/lib-tk/test
.heroku/python/lib/python2.7/sqlite3/test
.heroku/python/lib/python2.7/lib2to3/tests
.heroku/python/lib/python2.7/json/tests
.heroku/python/lib/python2.7/email/test
.heroku/python/lib/python2.7/test
```

...and removing them decreases the build size by 28%:
```
$ bob build runtimes/python-2.7.13
...
$ du -sh .heroku/python/
127M    .heroku/python/
$ find .heroku/python/ \( -type d -a \( -name test -o -name tests \) \) -exec rm -rf '{}' +
$ du -sh .heroku/python/
91M     .heroku/python/
```

**Comment by kennethreitz** [comment]
This sounds like a healthy improvement! Python's size isn't a problem at the moment, but improvements are always welcome.

**Comment by kennethreitz** [comment]
The real improvement here isn't reducing the size (which will help speed up download times), but the number of files created, in my opinion. The fewer files in the tarball the better, they take a while to create on disk.

**Comment by kennethreitz** [comment]
These changes will be rolled out in the next release of Python.

**Comment by edmorley** [comment]
> The fewer files in the tarball the better, they take a while to create on disk.

Very true -- I've re-run the builds and added the filecounts above - it halves the number of files.

**Comment by kennethreitz** [comment]
That's fantastic news. I might do a rebuild of 3.6.2 then.

**Comment by kennethreitz** [comment]
Deployed 3.6.2! ✨🍰✨

**Comment by edmorley** [comment]
Looks great - thank you :-)
