### ISSUE TITLE
Issues with the vendored sqlite/libsqlite

### ISSUE THREAD

**Issue by edmorley** [heroku/heroku-buildpack-python#427]
Some context:
* Python has a run-time dependency on `libsqlite3-0` and a build-time dependency on `libsqlite3-dev`.
* The [Python build scripts](https://github.com/heroku/heroku-buildpack-python/blob/78767e71996ddde2de5fdb84fc1e0291cc5fe4e3/builds/runtimes/python-2.7.13#L3) used for this buildpack vendor a [custom-built sqlite](https://github.com/heroku/heroku-buildpack-python/blob/78767e71996ddde2de5fdb84fc1e0291cc5fe4e3/builds/libraries/sqlite) into `.heroku/python/`.
* The vendored sqlite archive includes three components: the shared library (a la `libsqlite3-0`), headers/static library (a la `libsqlite3-dev`), and the sqlite3 CLI binary. 
* The vendored archive is used whilst the Python binary is being compiled (otherwise it would skip the `_sqlite3` module) and then also included in the Python archive uploaded to S3 ready for the slug compile.

There are a few problems with this:
* The vendored sqlite is extremely old (v3.7.9, [released on 2011-11-01](https://www.sqlite.org/releaselog/3_7_9.html)). Compare this to [v3.11.0 on Xenial](https://packages.ubuntu.com/xenial/libsqlite3-0) and [v3.8.2 on Trusty](https://packages.ubuntu.com/trusty-updates/libsqlite3-0).
* Even if this version were updated now, keeping custom builds rather than using OS packages means:
  - an going battle to keep the version up to date with new releases/security fixes.
  - reduced parity with the Ubuntu Python and [Docker Python images]((https://github.com/docker-library/python/blob/c9954b06c8b178d7888bc1626bed5a14e43a9203/2.7/slim/Dockerfile#L14)) (that use the OS packages).
* It adds 12MB to the slug size on disk for every Python app (13% of the Python 2.7.13 archive size), even though part of the contents (`libsqlite3-0`) actually duplicates what is [installed in the stack image](https://devcenter.heroku.com/articles/stack-packages).

As such, I propose switching from vendoring sqlite to using the OS packages. I'm guessing the cedar-14 images will want to be left as-is, and so this only be done for Heroku-16.

This would require:
1) Adding `libsqlite3-dev` to the `heroku:16-build` image.
2) Adding `sqlite3` (the command line tool) to the `heroku:16` image, for parity with the vendored archive. (Whilst it's not needed to build Python, I'm presuming there are people relying on it.)
3) Making the [sqlite build script](https://github.com/heroku/heroku-buildpack-python/blob/78767e71996ddde2de5fdb84fc1e0291cc5fe4e3/builds/libraries/sqlite) return early for heroku-16 ([the same as for libmemcached](https://github.com/heroku/heroku-buildpack-python/blob/78767e71996ddde2de5fdb84fc1e0291cc5fe4e3/builds/libraries/vendor/libmemcache#L6-L9)), since bob-builder doesn't support per-platform dependencies.

@kennethreitz, thoughts? I'm happy to open the necessary stack-images PR if you think this makes sense.

**Comment by kennethreitz** [comment]
I don't think this will change any time soon, but I'm also interested in hearing David's thoughts on this.

**Comment by dzuelke** [comment]
The reason it's not there is historical: to prevent Rails apps from building with a "local DB" sqlite gem. I think we should revisit this in the interest of consistency. /cc @hone @schneems

**Comment by schneems** [comment]
Having sqlite on the platform would make detecting an extremely common "wrong" thing that Rails devs do much harder (maybe impossible).

**Comment by edmorley** [comment]
@schneems, I presume you're referring to this?
https://github.com/heroku/heroku-buildpack-ruby/blob/ef2a0a9f14ebb9ec6e9e902db5c8058af2ffc164/lib/language_pack/ruby.rb#L633-L639

Could this case be detected by grepping the gem install log for 'sqlite', or else running `gem list` and grepping that?

Also, if "prevent people from accidentally using sqlite on an ephemeral filesystem" is a goal, then perhaps the better direction is to stop supporting it on Python too? (Given Django defaults to using sqlite too for example.) If sqlite isn't available during Python compile, the compile still succeeds but just means that at runtime an `import sqlite3` will fail.

**Comment by schneems** [comment]
@edmorley we can already parse the Gemfile.lock and we know exactly which gems are installed. The issue is that a minority of users have installed sqlite3 via a buildpack and actually use it for some valid reason, so if we detect the gem and fail we will be preventing valid users from doing a valid thing on Heroku.

**Comment by kennethreitz** [comment]
sqlite is part of the standard library, and is expected to be importable for certian libraries — for example, the every-important iPython. Therefore, Python supports it.

**Comment by edmorley** [comment]
Another option here would be to use an approach similar to [heroku-buildpack-apt](https://github.com/heroku/heroku-buildpack-apt) and create temporary APT cache/state directories, allowing `apt-get update` and then `apt-get download` as non-root, to download the `.deb` package for `libsqlite3-dev` as part of the Python build script. This would then be extracted and referenced during the build, and deleted after.

If this sounds acceptable, I could try putting together an example for the new Python 2.7.14 release (doing this as part of a new version release is probably best; it means people have to opt into it).

**Comment by kennethreitz** [comment]
@edmorley closing this until you make progress on it :)

**Comment by edmorley** [comment]
I may not have time to double back to this for a while unfortunately. However it's worth emphasising:

> The vendored sqlite is extremely old (v3.7.9, released on 2011-11-01). Compare this to v3.11.0 on Xenial and v3.8.2 on Trusty.

Along with:
https://www.cvedetails.com/vendor/9237/Sqlite.html
