### ISSUE TITLE
Heroku-16 GDAL vendor libraries are empty

### ISSUE THREAD

**Issue by otanner** [heroku/heroku-buildpack-python#428]
Hi,

I'm unable to get GDAL working with Heroku-16 stack. After couple of hours debugging it looks like when the step in compile phase fetches pre-compiled vendor packages for gdal, the package is empty:

Package for cedar-14:

```
--2017-07-24 19:04:37--  https://lang-python.s3.amazonaws.com/cedar-14/libraries/vendor/gdal.tar.gz
Resolving lang-python.s3.amazonaws.com... 52.216.64.176
Connecting to lang-python.s3.amazonaws.com|52.216.64.176|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 55632483 (53M) [application/octet-stream]
```

Package for heroku-16:

```
--2017-07-24 19:06:40--  https://lang-python.s3.amazonaws.com/heroku-16/libraries/vendor/gdal.tar.gz
Resolving lang-python.s3.amazonaws.com... 52.216.227.56
Connecting to lang-python.s3.amazonaws.com|52.216.227.56|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 66 [application/x-tar]
```

Could you please provide a working pre-compiled GDAL package for Heroku-16 stack as well.

The step I'm referring can be found here: https://github.com/heroku/heroku-buildpack-python/blob/master/bin/steps/gdal

**Comment by otanner** [comment]
Just to mention, this issue breaks the `BUILD_WITH_GEO_LIBRARIES` support for GDAL as well.

**Comment by kennethreitz** [comment]
Thanks, a fix is in progress.

**Comment by codingjoe** [comment]
This is a duplicate to https://github.com/heroku/heroku-buildpack-python/issues/398

**Comment by kennethreitz** [comment]
This should be fixed shortly, as soon as the build is complete!

**Comment by kennethreitz** [comment]
Build complete! ✨🍰✨
