### ISSUE TITLE
DEFAULT_PYTHON_STACK is set to cedar-14

### ISSUE THREAD

**Issue by edmorley** [heroku/heroku-buildpack-python#429]
In `bin/compile` there is:
```bash
DEFAULT_PYTHON_STACK="cedar-14"
```

The default stack for Heroku is now heroku-16, so this should be updated.

However this variable is only used once in the buildpack, here:
```bash
# Support Anvil Build_IDs
[ ! "$SLUG_ID" ] && SLUG_ID="defaultslug"
[ ! "$REQUEST_ID" ] && REQUEST_ID=$SLUG_ID
[ ! "$STACK" ] && STACK=$DEFAULT_PYTHON_STACK
```

I don't think it makes sense to have a fall-back default stack since it may not match the actual OS being used and could result in a Python binary being installed that won't run on that system. 

This was added 3 years ago in:
https://github.com/heroku/heroku-buildpack-python/commit/5c4a414cb7140689a8e4303e75e448f690ef589d

@kennethreitz, would it perhaps be better to just assert at the start of compile that `STACK` and some of the other mandatory environment variables are set and not have a fallback? (As far as I'm aware they always should be set?)

**Comment by kennethreitz** [comment]
this is for use on other platforms that don't have a STACK environment variable. there are a surprising number of people out there using buildpacks on not-Heroku.

**Comment by edmorley** [comment]
Yeah I guessed as much, but I still don't think it's the best thing to do.

Someone using this stack outside of Heroku without STACK set on xenial will end up with strange breakage that's hard to track down, whereas an explicit `echo "STACK not set!" && exit 1` would make it much more clear.

I'll open a PR when I get a chance.

**Comment by kennethreitz** [comment]
There is an establish pattern of people using cedar-14 compatible stacks with their buildpacks, it seems.

**Comment by kennethreitz** [comment]
we can test this by switching it to heroku-16 and see who yells at us

**Comment by kennethreitz** [comment]
Also, STACK might not be set during Heroku CI, I'd have to check.

**Comment by kennethreitz** [comment]
in general, i'm a fan of not touching this part of the codebase
