### ISSUE TITLE
pipenv-python-version warning about no pipfile.lock can never be reached

### ISSUE THREAD

**Issue by edmorley** [heroku/heroku-buildpack-python#441]
Since the `[[ ! -f $BUILD_DIR/Pipfile.lock ]]` conditional is inside a `[[ -f $BUILD_DIR/Pipfile.lock ]]`conditional (the exact inverse) and so will never be true:
https://github.com/heroku/heroku-buildpack-python/blob/f74d4db8c5953b39ef69852157ad8f78d678bf8d/bin/steps/pipenv-python-version#L8-L10

I'm presuming the first conditional is meant to check for the presence of `Pipfile` rather than `Pipfile.lock`?

**Comment by edmorley** [comment]
This was fixed in #458.

**Comment by kennethreitz** [comment]
yessir!
