### ISSUE TITLE
Git tag missing for the v110 release

### ISSUE THREAD

**Issue by edmorley** [heroku/heroku-buildpack-python#448]
https://github.com/heroku/heroku-buildpack-python/blob/master/CHANGELOG.md#110
https://github.com/heroku/heroku-buildpack-python/releases

**Comment by edmorley** [comment]
The v111 and v112 tags are missing too.

The lack of these tags makes it less straight-forwards for people to roll back to a previous buildpack release in case of issues with the `heroku/python` stable release (eg #457).

**Comment by kennethreitz** [comment]
This is a side-effect of our new master branch protection, which gave me a mental block from pushing to the master branch (including pushing git tags — even though that's allowed). Sorry for the trouble.

**Comment by kennethreitz** [comment]
Just pushed a tag for v112.

**Comment by kennethreitz** [comment]
TODO:

- [ ] Add tag for v110
- [ ] Add tag for v111

**Comment by kennethreitz** [comment]
Need to find the right refs first.

**Comment by edmorley** [comment]
The new v115 release's tag is missing too (it should be on master, which is at d4b8c2aeda335c48b9f7dd6731c4b406d319ae1e).
I'll file an issue for adding a way to automate this :-)

> Need to find the right refs first.

By modifying the buildkits plugin so it dumps the raw JSON response from `heroku buildkits:revisions heroku/python`, I found an additional `tar_link` property not normally output, which gives the previous buildpack URLs as:
https://codon-buildpacks.s3.amazonaws.com/buildpacks/heroku/python-v110.tgz
https://codon-buildpacks.s3.amazonaws.com/buildpacks/heroku/python-v111.tgz

By diffing those against each other and comparing to the repository git log, I believe v111 should be at fb52d1bf595a1e4735d54724ffb778793ab64d38 , and v110 at 194932889dee79c1a6045e6208cca40edb90147c.

It also means that the v109/v110 CHANGELOG.md entries aren't quite right - I'll open a PR for that now.

**Comment by kennethreitz** [comment]
@edmorley you're a gentleman and a scholar. 

Pushed tags.

**Comment by edmorley** [comment]
Looks great - many thanks :-)
