### ISSUE TITLE
Output the Python version when restoring from cache

### ISSUE THREAD

**Issue by edmorley** [heroku/heroku-buildpack-python#453]
In #440 it was mentioned that 99% of apps don't specify a Python version via a checked-in runtime.txt and instead rely on the default Python version provided by the buildpack. 

In addition, the buildpack uses a sticky version -- that is whilst the buildpack default Python version does increase over time, an app will always use the version that was the default when it was first created [1].

This means apps can be using ancient/insecure [2] versions of Python with users having no way to notice, since the buildpack log output doesn't mention what version of Python is being used when it is restored from cache (unlike first install). 

Log output when Python restored from cache:
```
-----> Python app detected
-----> Installing requirements with pip
```

The buildpack API docs [recommend](https://devcenter.heroku.com/articles/buildpack-api#style) including version numbers where possible, and other buildpacks such as the nodejs one provide much more detailed information. 

nodejs buildpack output:
```
-----> Installing binaries
       engines.node (package.json):  7.10.0
       engines.npm (package.json):   unspecified (use default)
       engines.yarn (package.json):  unspecified (use default)
       
       Resolving node version 7.10.0...
       Downloading and installing node 7.10.0...
       Using default npm version: 4.2.0
       Resolving yarn version (latest)...
       Downloading and installing yarn (0.28.1)...
       Installed yarn 0.28.1
```

[1] If we're being pedantic, it in fact uses the default version when the apps' cache was last cleared, which may be more recent than when the app was created. But I doubt this set of people would ever manually clear their cache either, so it's the same end result.
[2] Yes, there is the warning for `InsecurePlatformWarning`, but that only covers Python <2.7.9 and there have been other security fixes since.

**Comment by kennethreitz** [comment]
Closing for #440
