### ISSUE TITLE
grep outputting usage during slug compile

### ISSUE THREAD

**Issue by prashnts** [heroku/heroku-buildpack-python#455]
While compiling slug for a Python 2.7 app, there's a lot of usage info for `grep`. Output is below:

```
remote: Building source:
remote:
remote: -----> Deleting 5 files matching .slugignore patterns.
remote: -----> Python app detected
remote: -----> Noticed cffi. Bootstrapping libffi.
remote: -----> Installing requirements with pip
remote:        Usage: grep [OPTION]... PATTERN [FILE]...
remote:        Try 'grep --help' for more information.
remote:        Usage: grep [OPTION]... PATTERN [FILE]...
remote:        Try 'grep --help' for more information.
remote:        Usage: grep [OPTION]... PATTERN [FILE]...
remote:        Try 'grep --help' for more information.
```

Note that the slug did compile successfully, but this error/help did not occur earlier.

**Comment by edmorley** [comment]
Hi! I tried reproducing using a Heroku-16 test app, that had the buildpack set to https://github.com/heroku/heroku-buildpack-python.git however didn't get that log output.

What stack are you using (see `heroku stack`), and what is the output from `heroku buildpacks`? What was the timestamp for that build? (v111 of the buildpack was released ~13 hours ago)

Looking for instances of grep in the buildpack on master, I see:

```
bin/steps/mercurial
4: if (grep -Fiq "hg+" requirements.txt) then

bin/utils
69:        echo "$e" | grep -E "$WHITELIST" | grep -qvE "$BLACKLIST" &&

bin/warnings
5:  if grep -qi 'InsecurePlatformWarning' "$WARNINGS_LOG"; then
16:  if grep -qi 'fatal error: libmemcached/memcached.h: No such file or directory' "$WARNINGS_LOG"; then
26:  if grep -qi 'running setup.py install for scipy' "$WARNINGS_LOG"; then
38:  if grep -qi 'Running setup.py install for distribute' "$WARNINGS_LOG"; then
49:  if grep -qi 'Running setup.py install for six' "$WARNINGS_LOG"; then
```

The `bin/steps/mercurial` instance is prior to the pip install step (so couldn't have resulted in that log output).

The `bin/utils` instance is inside the `sub-env` function - which on master / the v111 release pip recently started using.

**Comment by Coalpaw** [comment]
I had this pop up for a client app that I maintain.  It is still using cedar-14

```
=== Buildpack URL
heroku/python

=== Available Stacks
  heroku-16
* cedar-14
```

**Comment by prashnts** [comment]
I'm on `heroku-16` stack.

```
=== Buildpack URLs
1. heroku/python
2. https://github.com/dscout/wkhtmltopdf-buildpack.git
3. https://github.com/prashnts/heroku-buildpack-nodejs.git
4. https://github.com/prashnts/heroku-buildpack-textblob.git

=== Available Stacks
* heroku-16
  cedar-14
```

Note that there's also a `runtime.txt`:
```
~ cat runtime.txt
python-2.7.13
```

**Comment by kennethreitz** [comment]
Will investigate. I saw this yesterday too, but didn't have enough time to look into it.

**Comment by thejo** [comment]
I'm seeing the same grep usage logs, but the slug compiles.

`heroku-16` stack and Python 3.6.0.

**Comment by kennethreitz** [comment]
@thejo this should have been fixed today. When were you seeing this?

**Comment by thejo** [comment]
@kennethreitz I saw it over the weekend. I just deployed an update and can confirm that the issue is fixed.

**Comment by kennethreitz** [comment]
\o/ Sorry about the bug. Bash can be tricky sometimes!

**Comment by thejo** [comment]
@kennethreitz it happens! Thanks for the quick fix.
