### ISSUE TITLE
Automate adding the git tag when publishing a new release

### ISSUE THREAD

**Issue by edmorley** [heroku/heroku-buildpack-python#468]
To reduce the chance of forgetting to add the git tag to the repository when a new buildpack version is published using `heroku buildkits:publish`, it would be great to add some automation.

I was thinking perhaps a Makefile command (or several) that between them:
* helped adding a git tag
* made sure the version being published was from that exact tagged revision (eg not accidentally on a feature branch instead)
* checked the working directory was clean (to help work around heroku/heroku-buildkits#24)
* then runs `heroku buildkits:publish ...`

The Ruby buildpack has a few helpers that could be useful for inspiration:
https://github.com/heroku/heroku-buildpack-ruby/blob/dbf4ffbb11c16d9e593a7d622f49871b511ca70b/Rakefile#L89-L297

**Comment by edmorley** [comment]
I've found some more scripts some other buildpacks use:
https://github.com/heroku/heroku-buildpack-java/blob/master/etc/publish.sh
https://github.com/heroku/heroku-buildpack-go/blob/master/bin/publish

**Comment by kennethreitz** [comment]
I'm apt to make a `publish.py` :)

**Comment by kennethreitz** [comment]
i think i'll just learn some discipline :)
