### ISSUE TITLE
Support for test command

### ISSUE THREAD

**Issue by ntcong** [heroku/heroku-buildpack-python#477]
So I stumped upon some problem with auto test with Gitlab and found this
https://gitlab.com/gitlab-org/gitlab-ce/issues/26941

Basically gitlab said that python buildpack does not support test command. And then I also found this from Nov 2016 https://github.com/heroku/heroku-buildpack-python/commit/89125df805a8a942dbb18d7fa413da7cc28359c0 which we removed test command because it's deprecated

The test command is pretty simple, should I add it back?

**Comment by kennethreitz** [comment]
we have tests.

**Comment by kennethreitz** [comment]
they just don't exist there.
