### ISSUE TITLE
Can no longer set custom GUNICORN_CMD_ARGS via Heroku config vars

### ISSUE THREAD

**Issue by bits01** [heroku/heroku-buildpack-python#627]
It seems that a new buildpack is the default on Heroku now that breaks our production application. We used to be able to set GUNICORN_CMD_ARGS via the Heroku config vars. But after a deployment today our app broke because GUNICORN_CMD_ARGS now seems to be set to `--access-logfile -` in `python.gunicorn.sh`:
https://github.com/heroku/heroku-buildpack-python/blob/master/vendor/python.gunicorn.sh#L5:8

We do *not* want gunicorn to log to stdout and we want to be able to set other options via GUNICORN_CMD_ARGS that are now completely ignored. Is this a bug?

As a side note, not sure how this change ended up in the current Heroku buildpack as the latest tagged version seems to be v120 from Sept 26.

**Comment by edmorley** [comment]
It looks like a new version was released yesterday:

```
$ heroku buildkits:revisions heroku/python
=== Revisions
v122  a day ago      by kenneth@heroku.com
v121  2 months ago   by kenneth@heroku.com
v120  3 months ago   by kenneth@heroku.com
...
```
(Using this CLI addon: https://github.com/heroku/heroku-buildkits)

The git tags for v121 and v122 are missing from this repo.

Re the issue, it seems like the `GUNICORN_CMD_ARGS` export would be best defined like so:
```bash
export GUNICORN_CMD_ARGS=${GUNICORN_CMD_ARGS:-'--access-logfile -'}
```

**Comment by bits01** [comment]
Thanks for your quick reply. Can we get a fix for this please as I'm sure it's affecting more than our application.

**Comment by edmorley** [comment]
For urgent issues I'd recommend filing a support ticket to get someone from Heroku to take a look (I'm not an employee).

**Comment by bits01** [comment]
Thank you. I do have an open ticket with Heroku.

**Comment by edmorley** [comment]
In the meantime I'd suggest either:
* pinning to a previous buildpack release (either by tag or SHA, see: https://devcenter.heroku.com/articles/buildpacks#buildpack-references)
* setting `GUNICORN_CMD_ARGS` via [<repo_root>/.profile](https://devcenter.heroku.com/articles/dynos#the-profile-file) since it takes precedence over the [profile.d/ scripts](https://devcenter.heroku.com/articles/buildpack-api#profile-d-scripts), so won't be overwritten by python.gunicorn.sh

**Comment by bits01** [comment]
Thanks for the tips. For now I just added the custom flags to the gunicorn startup command in the `Procfile`.

**Comment by kennethreitz** [comment]
Thanks, i'll make this a "set default" instead of a bare set

**Comment by kennethreitz** [comment]
https://github.com/heroku/heroku-buildpack-python/pull/628
