### ISSUE TITLE
.heroku/python/bin/pip: No found.

### ISSUE THREAD

**Issue by crayfishx** [heroku/heroku-buildpack-python#629]
I'm using this buildpack from pkgr and can't seem to get around the following issue...

```
-----> Python app
-----> Installing python-3.6.2
-----> Installing pip
-----> Installing requirements with pip
       /root/.pkgr/buildpacks/custom/693f4db00ef26f80d6165bc950d89e3479b1c8d3/heroku-buildpack-python/bin/steps/pip-install: line 10: /opt/puppetboard/.heroku/python/bin/pip: No such file or directory
     ! ERROR: compile failed
```

I've tried this against various older versions of the buildpacks with different runtimes, this was generated from v117 with...

```
# cat runtime.txt
python-3.6.2
```

Everything I've dug up on Google seems to suggest this is common but solved by just using the right runtime, but I've tried almost every combination I can think of and just can't get past this.

Any suggestions appreciated.

Thx.

**Comment by kennethreitz** [comment]
Please use a supported version of Python.

**Comment by crayfishx** [comment]
@kennethreitz I thought I was using the supported version.  v120 states python-3.6.2 in the README but I get the same error....

```
-----> Python app
-----> Installing python-3.6.2
-----> Installing pip
-----> Installing requirements with pip
       /root/.pkgr/buildpacks/custom/78925a16cd23476e3c0d2910b1d9f5fde81b8786/heroku-buildpack-python/bin/steps/pip-install: line 10: /opt/puppetboard/.heroku/python/bin/pip: No such file or directory
     ! ERROR: compile failed
```

?

**Comment by kennethreitz** [comment]
Using 3.6.4 will solve your problem
