### ISSUE TITLE
[Question] package pinned with a git commit is not reinstalled during deployment

### ISSUE THREAD

**Issue by jxltom** [heroku/heroku-buildpack-python#631]
If I setup a package in requirements.txt with a specific commit such as ```git+https://github.com/repo.git@s8c76d8```, buildpack of course can install it.

But if I change the commit to another one, since they have same package version, pip in the buildpack will not install this newer package again. This is the default behaviour of pip.

But in the deployment, I really need to install the newer one. In my local system, I can reinstall the package and install it again manually. In heroku, I don't know how to deal with it. So any solution for this? Thanks

**Comment by kennethreitz** [comment]
you need to add -e

**Comment by jxltom** [comment]
@kennethreitz Thanks, but using ```-e``` option, the package will be installed in the ```src``` folder of current working directory. Is there any way to install it to ```site-packges``` when installing by ```pip install -r requirements.txt```? That's because in my local system, I still would like to install requirements by ```pip install -r requirements``` and I would like to install from any folder I want witout going to specfic folder such as ```lib/python/site-packages```

Thanks a lot.

**Comment by kennethreitz** [comment]
you can specify the location of `src` with the `--src` flag to pip.

**Comment by jxltom** [comment]
@kennethreitz 

Thanks.

```--src``` works with single pip command perfectly, but I would like to install requirements via requirements.txt with ```-e git+https://github.com/flask-admin/flask-admin.git@2c2c98e.zip#egg=flask-admin --src=~/Desktop/tmp``` format inside it.  The with the command ```pip install -r requirements.txt``` or buildpack's default requirements installation procedure, ```pip: error: no such option: --src``` will be raised.

Is there any way to solve this?
