### ISSUE TITLE
install dev deps with pipenv on CI

### ISSUE THREAD

**Issue by kennethreitz** [heroku/heroku-buildpack-python#632]
https://github.com/pypa/pipenv/issues/1295

**Comment by dbinetti** [comment]
(cross-posted)

What is the best practice for using pipenv with Continuous Integration systems (specifically, with Heroku CI)? Currently I have testing dependencies in my dev-packages but that doesn't load when using Heroku CI, so I have to include all dev stuff in my default (ie, production.) list. Is there a [test] header? Some other practice?

**Comment by kennethreitz** [comment]
Thanks for bringing this to my attention. `[dev-packages]` is definitely the intended place for this, but it is currently not supported by the buildpack. I'll do my best to add support as soon as possible.

**Comment by kennethreitz** [comment]
https://github.com/heroku/heroku-buildpack-python/pull/633

**Comment by kennethreitz** [comment]
fixed in master branch

**Comment by dbinetti** [comment]
nice! thanks  I'm assuming you'll close when ready?

**Comment by kennethreitz** [comment]
yes!

**Comment by dbinetti** [comment]
FYI, I just ran a deploy and while heroku-ci worked and it deployed on prod, a quick check indicates that all the dev packages were included in the prod build (even though I have split them into `packages` and `dev-packages`.  I believe I have configured correctly.  Repo: https://github.com/barberscore/barberscore-api
