### ISSUE TITLE
Push rejected, failed to compile Python app.

### ISSUE THREAD

**Issue by aneumeier** [heroku/heroku-buildpack-python#641]
Hi heroku-buildpack-python team,

as of recently I have one issue with an app that worked before. The issue seems to relate to a failed update of pip during deployment. here is what happens:

```
> Counting objects: 26, done.
> Delta compression using up to 2 threads.
> Compressing objects: 100% (24/24), done.
> Writing objects: 100% (26/26), 8.95 KiB | 0 bytes/s, done.
> Total 26 (delta 14), reused 0 (delta 0)
> remote: Compressing source files... done.
> remote: Building source:
> remote: 
> remote: -----> Python app detected
> remote: Traceback (most recent call last):
> remote:   File "/app/.heroku/python/bin/pip", line 11, in <module>
> remote:     load_entry_point('pip==6.0.6', 'console_scripts', 'pip')()
> remote:   File "/app/.heroku/python/lib/python3.6/site-packages/pkg_resources/__init__.py", line 572, in load_entry_point
> remote:     return get_distribution(dist).load_entry_point(group, name)
> remote:   File "/app/.heroku/python/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2755, in load_entry_point
> remote:     return ep.load()
> remote:   File "/app/.heroku/python/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2408, in load
> remote:     return self.resolve()
> remote:   File "/app/.heroku/python/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2414, in resolve
> remote:     module = __import__(self.module_name, fromlist=['__name__'], level=0)
> remote:   File "/tmp/build_0116644674281592b0275f50121a6cb8/.heroku/python/lib/python3.6/site-packages/pip-6.0.6-py3.6.egg/pip/__init__.py", line 13, in <module>
> remote:     from pip.utils import get_installed_distributions, get_prog
> remote:   File "/tmp/build_0116644674281592b0275f50121a6cb8/.heroku/python/lib/python3.6/site-packages/pip-6.0.6-py3.6.egg/pip/utils/__init__.py", line 22, in <module>
> remote:     from pip._vendor import pkg_resources, six
> remote:   File "/tmp/build_0116644674281592b0275f50121a6cb8/.heroku/python/lib/python3.6/site-packages/pip-6.0.6-py3.6.egg/pip/_vendor/pkg_resources/__init__.py", line 1649, in <module>
> remote:     register_loader_type(importlib_bootstrap.SourceFileLoader, DefaultProvider)
> remote: AttributeError: module 'importlib._bootstrap' has no attribute 'SourceFileLoader'
> remote: -----> Installing pip
> remote: -----> Installing requirements with latest Pipenv…
> remote:  !     Push rejected, failed to compile Python app.
> remote: 
> remote:  !     Push failed
> remote: Verifying deploy...
> remote: 
> remote: !	Push rejected to app.
> 
```

I reviewed a few other cases related to pip, but this appears to be something different.

Until now, I updated the version in `runtime.txt`, and also migrated to Pipfile, neither helped. 

Is there anything I can do?

**Comment by kennethreitz** [comment]
are you using an unsupported version of Python?

**Comment by aneumeier** [comment]
I'm using python-3.6.4 now.

First, I bumped runtime.txt up from 3.6.2, and replaced that with a Pipfile later.

**Comment by kennethreitz** [comment]
try purging your cache with heroku-repo:

https://github.com/heroku/heroku-repo

**Comment by kennethreitz** [comment]
$ heroku plugins:install heroku-repo
    $ heroku repo:purge_cache -a appname

**Comment by kennethreitz** [comment]
looks like pip got corrupted somehow.

**Comment by kennethreitz** [comment]
if you could share your `Pipfile` or `requirements.txt` that would be great, as well.

**Comment by aneumeier** [comment]
`requirements.txt`

> django==2.0.2
> social-auth-app-django
> dj-database-url
> gunicorn==19.6.0
> psycopg2-binary
> whitenoise==3.2
> requests

`Pipfile`

> [[source]]
> 
> url = "https://pypi.python.org/simple"
> verify_ssl = true
> name = "pypi"
> 
> 
> [dev-packages]
> 
> 
> 
> [packages]
> 
> django = "==2.0.2"
> social-auth-app-django = "*"
> dj-database-url = "*"
> gunicorn = "==19.6.0"
> "psycopg2-binary" = "*"
> whitenoise = "==3.2"
> requests = "*"
> 
> 
> [requires]
> 
> python_version = "3.6"
> python_full_version = "3.6.4"


In the process of trying and fixing this condition, I removed requirements.txt, though, only sticking with Pipfile.

**Comment by kennethreitz** [comment]
I see nothing here out of the ordinary. I recommend the heroku-repo method suggested.

**Comment by aneumeier** [comment]
Yep, that worked! Thanks for the pointer!
