### ISSUE TITLE
Generated `requirements.txt` doesn't include git repo deps

### ISSUE THREAD

**Issue by frostming** [heroku/heroku-buildpack-python#654]
Here is a part of my `Pipfile`
```
[packages]
...
gunicorn = "==19.7.1"
flask-login = "==0.4.0"
"psycopg2" = "*"
mistune-contrib = {git = "https://github.com/frostming/mistune-contrib.git", editable = true}
flask-sslify = "*"
```
After deployment, the app can't be established because it can't find `mistune-contrib`. I login `heroku run bash` to see the generated `requirements.txt` and found that mistune-contrib is not included

This issue blocks my deployment.

**Comment by adamkowalczyk** [comment]
We are also being affected by this. The release phase on our staging app started failing 6 days ago (which coincides with the release of v125) due to missing dependencies.

If I examine the generated `requirements.txt` all of our editable checkout dependencies are missing.

e.g.
`django-floppyforms = {git = "https://github.com/rtpg/django-floppyforms", editable = true, ref = "e118e79c77664ea08ae72f59ea02412da7d9b3a8"}`

**Comment by frostming** [comment]
Thanks for that solution

I am now use `requirements.txt` including the editables as a workaround.

**Comment by kennethreitz** [comment]
This shouldn't be affecting you, as the requirements.txt isn't being used for installation.

**Comment by kennethreitz** [comment]
What is the behavior you're not seeing as expected, other than the requirements.txt not containing the git dep?

**Comment by frostming** [comment]
As I previously commented, if I use `Pipfile` to manage deps, the editable deps are missed in installation. And they are not included in `requirements.txt` nor `claimed_requirements.txt`.

After I switch to use `requirements.txt` to manage them, this issue is gone.

**Comment by kennethreitz** [comment]
This shouldn't be happening. I'll investigate. 

I suspect it's related to the "skipping installation" bit — might have to not do that if git is present.

**Comment by kennethreitz** [comment]
they shouldn't be in `requirements.txt` or `claimed_requirements.txt`, that's to be expected, FYI.

**Comment by kennethreitz** [comment]
First push succeeded and installed the dependency as expected.

**Comment by kennethreitz** [comment]
Second push — no git dep. 

On it.

**Comment by frostming** [comment]
Thanks a lot!

**Comment by kennethreitz** [comment]
released!

**Comment by adamkowalczyk** [comment]
Thanks!
