### ISSUE TITLE
Latest release v126 does not build cffi dependencies

### ISSUE THREAD

**Issue by georgejlee** [heroku/heroku-buildpack-python#658]
I notice that the latest release v126 does not detect and include the dependencies for cffi in my project. This app worked fine on release v123. This is a cedar-14 app.

Steps to reproduce: 
1. Build review app using the app.json below with heroku/python buildpack.
2. Build fails with error shown below (`ffi.h: No such file or directory`)

This works fine if the buildpack is replaced with `https://github.com/heroku/heroku-buildpack-python.git#v123`.

Here is a build log using the latest heroku/python buildpack on cedar-14:
[failure.txt](https://github.com/heroku/heroku-buildpack-python/files/1809567/failure.txt)

Here is a successful build using buildpack `https://github.com/heroku/heroku-buildpack-python.git#v123`:
[success2.txt](https://github.com/heroku/heroku-buildpack-python/files/1809568/success2.txt)

Notice that the failed buildpack does not have the "Noticed cffi. Bootstrapping libffi." message at the top.

Here is my app.json for the successful build. For the failed build, just replace the heroku-buildpack-python line with heroku/python:
```
{
  "name": "pasturemap-api-django",
  "stack": "cedar-14",
  "description": "The PastureMap API server",
  "scripts": {
  },
  "env": {
    "APNS_CERTIFICATE": {
      "required": true
    },
    "CACHE_ENABLED": {
      "required": true
    },
    "CACHE_TIMEOUT_SECONDS": {
      "required": true
    },
    "DEFAULT_USER_TIMEZONE": {
      "required": true
    },
    "DJANGO_SETTINGS_MODULE": {
      "required": true
    },
    "GCM_API_KEY": {
      "required": true
    },
    "INTERCOM_PERSONAL_ACCESS_TOKEN": {
      "required": true
    },
    "JWT_SECRET_KEY": {
      "required": true
    },
    "MANDRILL_API_KEY": {
      "required": true
    },
    "MIXPANEL_TOKEN": {
      "required": true
    },
    "NOTIFICATION_EMAIL": {
      "required": true
    },
    "PAPERTRAIL_API_TOKEN": {
      "required": true
    },
    "PROFILING_ENABLED": {
      "required": true
    },
    "SENTRY_DSN": {
      "required": true
    },
    "STRIPE_API_KEY": {
      "required": true
    },
    "MAXMIND_USER_ID": {
      "required": true
    },
    "MAXMIND_LICENSE_KEY": {
      "required": true
    }
  },
  "formation": {
    "web": {
      "quantity": 1
    },
    "worker": {
      "quantity": 1
    }
  },
  "addons": [
    {
      "plan": "heroku-postgresql",
      "options": {
        "version": "9.4"
      }
    },
    "heroku-redis",
    "papertrail",
    "scheduler"
  ],
  "buildpacks": [
    {
      "url": "https://github.com/heroku/heroku-buildpack-python.git#v123"
    },
    {
      "url": "https://github.com/cyberdelia/heroku-geo-buildpack.git#1.3"
    }
  ]
}
```

Here is my requirements.txt:
[requirements.txt](https://github.com/heroku/heroku-buildpack-python/files/1809578/requirements.txt)

**Comment by kennethreitz** [comment]
Please provide your full build traceback as well.

**Comment by kennethreitz** [comment]
Interesting, can you update to cffi 1.11.5? They ship wheels now.

**Comment by georgejlee** [comment]
Upgrading cffi to 1.11.5 worked, thanks!
