### ISSUE TITLE
Bad Pipenv version

### ISSUE THREAD

**Issue by Benjamin-Dobell** [heroku/heroku-buildpack-python#661]
I can't deploy to Heroku at the moment:

https://stackoverflow.com/questions/49313660/heroku-importerror-cannot-import-name-insecurerequestwarning

This seems to be related to an (old) Pipenv issue:

https://github.com/pypa/pipenv/issues/693

I see that two days ago Pipenv was pinned to a specific version. I'm unclear on whether that caused the problem, or whether that was the resolution for the issue - and for some reason my app on Heroku is not yet on v126.

**Comment by Benjamin-Dobell** [comment]
As an side, is there some way to:

1. Check which buildpack version I'm running on Heroku? Presumably the latest.

2. Is there a way to force Heroku to use an old version of a buildpack?

I recognise these two questions are about Heroku at large and not this buildpack, but they'd help me identify the underlying cause. At the moment I feel free useless with respect to what information I was able to provide in this issue.

**Comment by Benjamin-Dobell** [comment]
Alright, forked this repo and pinned to Pipenv `11.0.2`, that version works for me. Presumably the current pinned version of Pipenv has issues.

**Comment by dbinetti** [comment]
set your build pack to a tagged release on GitHub.

eg: https://github.com/heroku/heroku-buildpack-python.git#v123

**Comment by kennethreitz** [comment]
Thanks for the report! I'll investigate.

**Comment by harrybiddle** [comment]
We're also seeing this error during our CI tests. Have not confirmed it if appears during deploy... I've pegged to heroku-buildpack v124 which seems to have fixed it. Here is some info, in case it's helpful:

[error.txt](https://github.com/heroku/heroku-buildpack-python/files/1824684/error.txt)
[Pipfile.lock.txt](https://github.com/heroku/heroku-buildpack-python/files/1824681/Pipfile.lock.txt)

**Comment by kennethreitz** [comment]
Pipenv is now pinned to 11.8.2, which I believe does not have this issue. I just ran a fresh deploy without any issues.

Any issues you are having might be related to a pip bug where it doesn't fully uninstall old versions of libraries — including old source files that are now removed from the pipenv source tree. 

This can be resolved by running:

    $ heroku plugins:install heroku-repo
    $ heroku repo:purge_cache

**Comment by harrybiddle** [comment]
Thanks for the quick fix again! I've tried this out and it fixes our problem.

**Comment by kennethreitz** [comment]
Sorry for the issue!
