### ISSUE TITLE
Error building buildpack

### ISSUE THREAD

**Issue by jsandovalc** [heroku/heroku-buildpack-python#673]
Hi,
I'm trying to push changes to heroku and I'm getting the following error in buildpack:

```
remote: -----> Python app detected        
remote: -----> Installing pip        
remote: Traceback (most recent call last):        
remote:   File "/app/tmp/buildpacks/e017775c13d244d4397e291ca027b523107af72c5d9945c1d691716ebdc6865d95882d7fe8567e96701275f1e1ac0664c5a117eda176535a12ebfcaae7e4f7f2/vendor/pipenv-to-pip", line 23, in <module>        
remote:     main()        
remote:   File "/app/tmp/buildpacks/e017775c13d244d4397e291ca027b523107af72c5d9945c1d691716ebdc6865d95882d7fe8567e96701275f1e1ac0664c5a117eda176535a12ebfcaae7e4f7f2/vendor/pipenv-to-pip", line 16, in main        
remote:     packages.append('{0}{1}'.format(package, lockfile['default'][package]['version']))        
remote: TypeError: string indices must be integers        
remote:  !     Push rejected, failed to compile Python app.        
remote: 
remote:  !     Push failed        
remote: Verifying deploy...
```

The temporary solution was to set the buildpack to tag 124. Not sure what's the problem with latest revisions.

**Comment by jsandovalc** [comment]
I see the error is in this dependency: "django": "==1.11.*"

The pipenv-to-pip script expects it to be a dict with a "version" (and "hash") key. But in Pipfile.lock is like that, a string.

**Comment by kennethreitz** [comment]
you have `==1.11.*` in your `Pipfile.lock`?

**Comment by jsandovalc** [comment]
Yes, it was like that. I set it with `pipenv` to a specific version (`1.11.10`) to be able to use the buildpack.

**Comment by kennethreitz** [comment]
That looks like a bug in your version of pipenv. Only exact versions should land in pipfile.lock.

**Comment by jsandovalc** [comment]
I see. We decided to leave it with an exact version. But I'll upgrade pipenv to the last version anyway.

Thanks.

**Comment by sigmavirus24** [comment]
The latest comments here make it sound like this has been resolved (more or less). As a result, I'm closing this. If this should be re-opened, please leave a comment letting me know @jsandovalc
