### ISSUE TITLE
Import failure on requests.

### ISSUE THREAD

**Issue by Riandy** [heroku/heroku-buildpack-python#679]
Traceback (most recent call last):
remote:   File "/app/tmp/buildpacks/779a8bbfbbe7e1b715476c0b23fc63a2103b3e4131eda558669aba8fb5e6e05682419376144189b29beb5dee6d7626b4d3385edb0954bffea6c67d8cf622fd51/vendor/pip-pop/pip-diff", line 15, in <module>
remote:     from pip.req import parse_requirements
remote:   File "/app/.heroku/python/lib/python2.7/site-packages/pip/req/__init__.py", line 3, in <module>
remote:     from .req_install import InstallRequirement
remote:   File "/app/.heroku/python/lib/python2.7/site-packages/pip/req/req_install.py", line 25, in <module>
remote:     import pip.wheel
remote:   File "/app/.heroku/python/lib/python2.7/site-packages/pip/wheel.py", line 28, in <module>
remote:     from pip.download import path_to_url, unpack_url
remote:   File "/app/.heroku/python/lib/python2.7/site-packages/pip/download.py", line 40, in <module>
remote:     from pip._vendor import requests, six
remote:   File "/app/.heroku/python/lib/python2.7/site-packages/pip/_vendor/requests/__init__.py", line 83, in <module>
remote:     from pip._internal.compat import WINDOWS
remote:   File "/app/.heroku/python/lib/python2.7/site-packages/pip/_internal/__init__.py", line 42, in <module>
remote:     from pip._internal import cmdoptions
remote:   File "/app/.heroku/python/lib/python2.7/site-packages/pip/_internal/cmdoptions.py", line 16, in <module>
remote:     from pip._internal.index import (
remote:   File "/app/.heroku/python/lib/python2.7/site-packages/pip/_internal/index.py", line 15, in <module>
remote:     from pip._vendor import html5lib, requests, six
remote: ImportError: cannot import name requests
remote: mount: failure.bad-requirements: No such file or directory

**Comment by jxltom** [comment]
Same issue

```
-----> Installing pip        
remote: Traceback (most recent call last):        
remote:   File "/tmp/buildpacks/custom/vendor/pip-pop/pip-diff", line 15, in <module>        
remote:     from pip.req import parse_requirements        
remote:   File "/app/.heroku/python/lib/python2.7/site-packages/pip/req/__init__.py", line 3, in <module>        
remote:     from .req_install import InstallRequirement        
remote:   File "/app/.heroku/python/lib/python2.7/site-packages/pip/req/req_install.py", line 25, in <module>        
remote:     import pip.wheel        
remote:   File "/app/.heroku/python/lib/python2.7/site-packages/pip/wheel.py", line 28, in <module>        
remote:     from pip.download import path_to_url, unpack_url        
remote:   File "/app/.heroku/python/lib/python2.7/site-packages/pip/download.py", line 40, in <module>        
remote:     from pip._vendor import requests, six        
remote:   File "/app/.heroku/python/lib/python2.7/site-packages/pip/_vendor/requests/__init__.py", line 83, in <module>        
remote:     from pip._internal.compat import WINDOWS        
remote:   File "/app/.heroku/python/lib/python2.7/site-packages/pip/_internal/__init__.py", line 42, in <module>        
remote:     from pip._internal import cmdoptions        
remote:   File "/app/.heroku/python/lib/python2.7/site-packages/pip/_internal/cmdoptions.py", line 16, in <module>        
remote:     from pip._internal.index import (        
remote:   File "/app/.heroku/python/lib/python2.7/site-packages/pip/_internal/index.py", line 15, in <module>        
remote:     from pip._vendor import html5lib, requests, six        
remote: ImportError: cannot import name requests
remote: mount: can't find failure.bad-requirements in /etc/fstab or /etc/mtab
```

**Comment by Riandy** [comment]
Issue is resolved without any changes on my end. Should be fixed by the heroku build pack team.

**Comment by jxltom** [comment]
Yes, nothing is done to my buildpack and application code. Maybe it is fixed in upstream
