### ISSUE TITLE
Pip 10 being installed

### ISSUE THREAD

**Issue by harrywhite4** [heroku/heroku-buildpack-python#680]
This buildpack is currently installing pip 10, but looking through the scripts it seems like it was supposed to be set at 9.0.2 not sure if using pip 10 is intended or not

We are having some issues installing git dependencies with the new version of pip as described here https://github.com/pypa/pip/issues/5251

I have tried disabling the buildpacks install to manually get pip 9, but looking at the pipenv script skip_pipenv_install is set back to 1 when there are git dependencies.

**Comment by edmorley** [comment]
It looks like the `get-pip.py` invocation here should be passing `pip==<version>`:
https://github.com/heroku/heroku-buildpack-python/blob/9eddeaeef98dbbaf4174cd279c7ecc86bbf4e3d1/bin/steps/python#L70

**Comment by makmanalp** [comment]
@edmorley is passing `pip==version` to get-pip.py an option? I was under the impression that the get-pip.py bundled all the code within it.

**Comment by edmorley** [comment]
Yes:
https://github.com/pypa/get-pip/blob/ba67ea6b49a0caa1c3be638b9f913590a8af624e/templates/default.py#L130-L154

The problem is that the pip that's bundled with get-pip.py self-upgrades:
https://github.com/pypa/get-pip/blob/ba67ea6b49a0caa1c3be638b9f913590a8af624e/templates/default.py#L157

**Comment by kennethreitz** [comment]
This is now resolved.
