### ISSUE TITLE
Deploy fails when uploading Pipfile.lock

### ISSUE THREAD

**Issue by ddahan** [heroku/heroku-buildpack-python#702]
When I deploy my project with Pipfile and Pipfile.lock, here is the error I got on Heroku:

```
-----> Python app detected
-----> Installing dependencies with Pipenv 11.8.2…
       Your Pipfile.lock (48bdc8) is out of date. Expected: (2bfadf).
       Aborting deploy.
 !     Push rejected, failed to compile Python app.
 !     Push failed
```

Note that my Pipfile.lock is up to date since I ran `pipenv update` just before commiting, pushing and deploying.

If I erase my Pipfile.lock, then commiting, pushing, deploying, it works.
However, it's not a clean solution because the Pipfile.lock must be updated to ensure deterministic builds.

I'm using Python 3.6.5 and Pipenv `2018.05.18`.
Not sure why the buildpack hardcoded the `11.8.2` version.

**Comment by sigmavirus24** [comment]
Related to #701

**Comment by CaseyFaist** [comment]
Buildpack is currently pinned at Pipenv version `2018.05.18` - are you still seeing this behavior @ddahan?
