### ISSUE TITLE
Changelog entries

### ISSUE THREAD

**Issue by amureki** [heroku/heroku-buildpack-python#707]
Hi Heroku fellows,

thanks for this buildpack!

I would kindly ask if we can update changelog during the releases/tags. It is hard to keep an eye on commits to see what is going on here.
Do you think, we can manage this somehow?

That would be awesome! ✨

**Comment by KevinBrolly** [comment]
Hi @amureki,

We added a changelog for v135 in #710 and will try to make sure we do this better in the future.

Thanks

**Comment by amureki** [comment]
@KevinBrolly thank you for the update! Very well done 👍
