### ISSUE TITLE
Using python 3.7.0 raises warning "This version is unsupported"

### ISSUE THREAD

**Issue by KevinBrolly** [heroku/heroku-buildpack-python#728]
Currently we are supporting:

2.7.15
3.6.6 (default)
3.7.0

The buildpack does not currently have the ability to support 2 separate minor versions (3.6.6 and 3.7.0 in this case) without outputting a "(you are using python-x.x.x, which is unsupported)" message.

This is because we only have a single variable for $LATEST_3 - https://github.com/heroku/heroku-buildpack-python/blob/a0275888a26b8f0132c7bb9fe3bf194b5c4fab1f/bin/steps/python#L18

**Comment by DEKHTIARJonathan** [comment]
I still have the same issue.

### With python-3.6.6

```
Staging...
-----> Installing python-3.6.6
 !     Requested runtime (python-3.6.6) is not available for this stack (cedar-14).
 !     Aborting.  More info: https://devcenter.heroku.com/articles/python-support
Failed to compile droplet: Failed to compile droplet: exit status 1
```

### With python-3.7.0

```
Staging...
Downloaded build artifacts cache (602.1M)
 !     The latest version of Python 3 is python-3.6.6 (you are using python-3.7.0, which is unsupported).
 !     We recommend upgrading by specifying the latest version (python-3.6.6).
       Learn More: https://devcenter.heroku.com/articles/python-runtimes
-----> Installing python-3.7.0
 !     Requested runtime (python-3.7.0) is not available for this stack (cedar-14).
 !     Aborting.  More info: https://devcenter.heroku.com/articles/python-support
Failed to compile droplet: Failed to compile droplet: exit status 1
```

**Comment by iocohen** [comment]
me too!

**Comment by agstew** [comment]
Requested runtime (Python 3.7.0) is not available for this stack (heroku-18)
Got the problem too!

**Comment by WisnuBramantyo** [comment]
I got the same issue with Python 3.6.6 on heroku-18.
`remote: -----> Python app detected`
`remote: -----> Installing Python 3.6.6`
`remote:  !     Requested runtime (Python 3.6.6) is not available for this stack (heroku-18).`
`remote:  !     Aborting.  More info: https://devcenter.heroku.com/articles/python-support`
`remote:  !     Push rejected, failed to compile Python app.`
What version of python we should use actually?

**Comment by hiroakikitaji** [comment]
same issue with Python 3.7.0

`remote: -----> Python app detected
remote:  !     Requested runtime (python 3.7.0) is not available for this stack (heroku-18).
remote:  !     Aborting.  More info: https://devcenter.heroku.com/articles/python-support
remote:  !     Push rejected, failed to compile Python app.
remote:
remote:  !     Push failed
remote: Verifying deploy...
remote:
remote: !       Push rejected to glacial-cove-95818.
remote:
To https://git.heroku.com/glacial-cove-95818.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/glacial-cove-95818.git'`
