### ISSUE TITLE
Add pypy3-6.0.0 support

### ISSUE THREAD

**Issue by Marocco2** [heroku/heroku-buildpack-python#758]

**Comment by joshfriend** [comment]
Yes please. The current pypy runtime version is getting a bit old

**Comment by kennethreitz** [comment]
pypy is not currently being updated.

**Comment by joshfriend** [comment]
@kennethreitz yes i know, this is a request to update the runtime to the latest available version because what's currently in the buildpack is so old.

**Comment by MarshalX** [comment]
The end of 2019. Any news?

**Comment by MarshalX** [comment]
The way to use the latest PyPy is Docker

Dockerfile:
```
FROM pypy:3

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD [ "pypy3", "./src/main.py" ] 
```

heroku.yml:
```
build:
  docker:
    worker: Dockerfile 
```

Don\`t forget set the stack of your app to container:
`heroku stack:set container` (in heroku cli, `-a` to select app)

Useful links:
https://hub.docker.com/_/pypy
https://devcenter.heroku.com/articles/build-docker-images-heroku-yml
https://docs.docker.com/engine/reference/builder/

**Comment by CaseyFaist** [comment]
Pypy 7.2.0 is now beta supported on Heroku 16 and 18: https://devcenter.heroku.com/articles/python-support#beta-support-pypy
