### ISSUE TITLE
pip uninstall/removing packages does not work

### ISSUE THREAD

**Issue by azreda** [heroku/heroku-buildpack-python#76]
I know this issue has been raised multiple times, but it remains to exist.

Right now, the only way to force a rebuild of your virtualenv seems to be to set a different runtime: https://devcenter.heroku.com/articles/python-runtimes#changing-runtimes

But I don't want to change my python runtime just so that I can remove a tiny package that I have modified, and instead want to use from my source tree.

I think being able to uninstall pagckages, even if you have set some flag to enable it, is a very important functionality. Thank you.

**Comment by dhbradshaw** [comment]
So ... what do you need to do to uninstall a package?

**Comment by kennethreitz** [comment]
@dhbradshaw remove the package from `requirements.txt`.

**Comment by d6tdev** [comment]
What do I need to do to update a package linked to a git commit? Like `git+https://github.com/abc/xyz.git@b33ce3f7d940da99fccf80bfe1615362b9de2143#egg=xyz`

**Comment by sumansai14** [comment]
How do I uninstall a package whose requirements are installed from setup.py?

**Comment by sumansai14** [comment]
How do I uninstall a package that was installed from a custom setup.py?
