### ISSUE TITLE
Gitlab auto Devops Heroku Buildpack Python, Error on Auto Test

### ISSUE THREAD

**Issue by PaulSka** [heroku/heroku-buildpack-python#773]
Hi,

I use auto devops feature on Gitlab, but i have problem with auto test

The Python buildpack failed with this error

`Selected buildpack does not support test feature`

I try with https://github.com/heroku/django-heroku

Thanks for your help !

**Comment by jmorrell** [comment]
Hi @PaulSka, this sounds like it might be a Gitlab issue, or a documentation issue.

This buildpack is on [their list of support buildpacks](https://docs.gitlab.com/ee/topics/autodevops/#currently-supported-languages), however python does not automatically run tests and require you to specify them. We cover this in our docs here: https://devcenter.heroku.com/articles/heroku-ci#python

However I'm not sure how you would do that in Gitlab's feature

**Comment by PaulSka** [comment]
Hi @jmorrell ,

I try with app.json into root folder, but same result.

I post this issues into gitlab

Thanks for your help.

**Comment by PaulSka** [comment]
I try to recreate herokuish env locally

```
docker run -it -v $PWD/:/tmp/app gliderlabs/herokuish:latest /bin/bash
/bin/herokuish buildpack test
```

Same error 

```
-----> Python app detected
Selected buildpack does not support test feature
```

I put a app.json into my app

```
{
    "environments": {
      "test": {
        "scripts": {
          "test": "pytest"
        }
      }
    }
  }
```

Same error

**Comment by jmorrell** [comment]
@PaulSka `app.json` is particular to Heroku. In this case `Selected buildpack does not support test feature` means that there is no `bin/test` script for the buildpack, which the python buildpack does not have.

Unless that changes, you will need to manually specify a test command using whatever mechanism GitLab provides for doing so

**Comment by kennethreitz** [comment]
I think the buildpack could automatically run 'pytest' if it's installed.

**Comment by cdbennett** [comment]
It seems a more generic way to run tests than the command `pytest` would be to use setuptools with `python setup.py test`, which might run pytest, or any other test framework configured in `setup.py`.

**Comment by consideRatio** [comment]
> I think the buildpack could automatically run 'pytest' if it's installed.

Makes a lot of sense to me.

**Comment by MichalBryxi** [comment]
AFAIK GitLab does not look at `app.json` at all. The test script would enable those that are running their CI/CD on GitLab to use this buildpack.

**Comment by gamer4life1** [comment]
I am having the same issue.

**Comment by CaseyFaist** [comment]
This is not a good experience, but since Heroku does not explicitly support Gitlab integration at this time, I'm unfortunately inclined to say this issue is not prioritized: https://devcenter.heroku.com/articles/integrating-with-version-control-providers-besides-github

I will create a new issue to audit the Python experience on Heroku CI though, and whether this buildpack should be making use of auto test.
