### ISSUE TITLE
[Feature reqeust] Let python buildpack can access private repo with custom environment variables

### ISSUE THREAD

**Issue by bruce3557** [heroku/heroku-buildpack-python#776]
In production build, we often need to hide some credentials (oauth token, username / password ...) to environment variables and use them in building resources like `setup.py` or `requirements.txt`.

After trying the code like this
```python
GITHUB_USER = os.getenv("GITHUB_USER")
GITHUB_PASSWD = os.getenv("GITHUB_PASSWD")
...
install_requires=[
    ...
    "https://{github_user}:{github_password}@github.com/codementordev/cm-data-utils.git".format(
        github_user=GITHUB_USER,
        github_password=GITHUB_PASSWD
    )
    ...
]
```
and it doesn't work.

Is it possible to support this kind of features in the official buildpack? (or something like this)

**Comment by kennethreitz** [comment]
environment variables are not exposed during installation. This is for security purposes, as setup.py's can theoretically do anything, including sending your credentials off to some server somewhere.

**Comment by kennethreitz** [comment]
you can just commit a revocable token to your source tree

**Comment by edmorley** [comment]
Another option is:
https://github.com/timshadel/heroku-buildpack-github-netrc

**Comment by bruce3557** [comment]
@kennethreitz @edmorley  Thanks for the answers!

Agree that the `setup.py` has some security issues.

In fact, we also discussed above solutions and have security concerns on them:
- In general, we avoid to commit credentials-like stuffs in code.
- The things why we don't use third-party buildpacks is about the maintenance and security.

Currently we solve the issue by generating private repo links before executing `pip install` but still want to discuss how can make this kind of process more efficient.

**Comment by edmorley** [comment]
> The things why we don't use third-party buildpacks is about the maintenance and security.

For the above buildpack, one of the forks is hosted within the Heroku GitHub org, if that helps:
https://github.com/heroku/heroku-buildpack-github-netrc
(plus with any buildpack you can always fork to your own org and point the app at the forked repo)

**Comment by bruce3557** [comment]
Thanks for your sharing! It is helpful!
We traced the code and have another solution on it.
We use `pre_compile` file to generate private repo link with credentials and it works~

**Comment by CaseyFaist** [comment]
Thanks for opening this feature request as we discussed in your support ticket @bruce3557 ! 👍 I'll put together a contribute/request guide so it's clearer in the future, but I'd like to start using the feature request label I added so I can preserve conversations around feature requests and work done on them. From your ticket it sounds like we got to a good solution, but definitely share how the `.netrc` file option turns out! 😄 🌮

**Comment by bruce3557** [comment]
@CaseyFaist Yes~ Thanks for your help. I think there's another problem you may encounter when users from different CI integration service. For example, CircleCI  has built-in support with ssh-key setting but not `.netrc`, so users can easily install private github packages without hacking anything. With the restriction we also found another buildpack which supports ssh-key setting.
https://github.com/debitoor/ssh-private-key-buildpack

You're awesome team really 🥇 🥇 Very thanks for answering my many questions 😄

**Comment by CaseyFaist** [comment]
@bruce3557 That's good to know! I'm glad you got a solution that works for you 💯 🎉 ❤️
