### ISSUE TITLE
Would it be possible to specify pipenv release to be used just like python version?

### ISSUE THREAD

**Issue by ykhrustalev** [heroku/heroku-buildpack-python#780]
So far I run into the case where my local version (2018.10.13) generates different hash for the lock file comparing to what buildpack expects.

I tried downgrading my local pipenv version to match heroku but that leads to a failure locking the dependencies. Heroku's version simple doesn't work (that's other issue).

Would it be possible to allow user defined pipenv version via perhaps `runtime.txt` file?

**Comment by CaseyFaist** [comment]
Thanks for opening an issue! I can understand this concern, but this sounds like an issue you might want to raise on the Pipenv project for possible resolution. While we allow specifying python version, we lock the `pip` version used for all users at 9.0.3 to ensure the best possible experience and allow for uniform upgrades - however, allowing users to specify their own Pipenv versions could run into pip-pipenv incompatibility problems.

Have you tried using a quick `pip freeze > requirements.txt` in your local version environment to grab the dependencies and then re-installing them using the pinned version of pipenv?

**Comment by ykhrustalev** [comment]
I understand the complexity; it wasn't a surprise that such change will get non-positive feedback 😄. That's fine. 

So, I just downgraded to the supported version of pipenv and currently supported python3.6 on the cloud (3.6.6 at the moment of writing), in other words, I made my local environment closer to Heroku, and it went smooth.
