### ISSUE TITLE
Python 3.7.0 and 3.7.1 not working on Cedar-14 (pip error)

### ISSUE THREAD

**Issue by malthejorgensen** [heroku/heroku-buildpack-python#787]
This is a minor issue – we ended up upgrading to the Heroku-18 stack.

So, according to the docs (https://devcenter.heroku.com/articles/python-support#supported-runtimes) Cedar-14 should support 3.7.1 (was previously 3.7.0).

However, it fails during the build with the error:

```
remote: -----> Python app detected
remote: -----> Installing python-3.7.1
remote: -----> Installing pip
remote: -----> Installing SQLite3
remote: -----> Installing requirements with pip
remote:        /app/tmp/buildpacks/8790c95df.../bin/steps/pip-install: line 42: /app/.heroku/python/bin/pip: No such file or directory
remote:  !     Push rejected, failed to compile Python app.
remote:
remote:  !     Push failed
```

The very long hash in the `pip-install` path I've abbreviated is: `8790c95df255b386056ea169648fd4a33d1cb3fba81f73b536f26374f6af107145f64a5980db7a52177f63bb41527f360ebd2e3bef7b8917bda7b51cf284cfdb`.

The repo I'm using to produce the issue is this one:
https://github.com/malthejorgensen/heroku-cedar-14-python-37-test

**Comment by jasperchih** [comment]
i am fail by using the 3.7.2. After downgrade to 3.7.1 version, it is solved. 
can you verify the requirements.txt file content by manual "pip install xxx" to verify the package definition?

My error message in 3.7.2 is 
remote: -----> Python app detected
remote:  !     Python has released a security update! Please consider upgrading to python-3.7.1
remote:        Learn More: https://devcenter.heroku.com/articles/python-runtimes
remote: -----> Installing python-3.7.2
remote: -----> Installing pip
remote: -----> Installing SQLite3
remote: -----> Installing requirements with pip
remote:        /app/tmp/buildpacks/8790c95df255b386056ea169648fd4a33d1cb3fba81f73b536f26374f6af107145f64a5980db7a52177f63bb41527f360ebd2e3bef7b8917bda7b51cf284cfdb/bin/steps/pip-install: line 42: /app/.heroku/python/bin/pip: No such file or directory
remote:  !     Push rejected, failed to compile Python app.
remote:
remote:  !     Push failed
remote: Verifying deploy...
remote:

**Comment by gone** [comment]
Can confirm this happens when upgrading to 3.7.1 on cedar-14

**Comment by CaseyFaist** [comment]
Thanks for reporting this! Since [Cedar 14 will be sunset this April](https://devcenter.heroku.com/articles/stack), I highly recommend that if you are experiencing this issue to upgrade your stack first and see if that resolves your issue.

Since that sunset is quite soon, it's very likely that issues related to upgrading will be prioritized above backwards compatibility fixes at this point - so test your stack updates early and report related bugs so I can help make that transition as smooth as possible 🎉 💟 🎉

**Comment by CaseyFaist** [comment]
Closing as Cedar 14 is being sunset
