### ISSUE TITLE
Can't install GDAL libraries before pipenv install is done

### ISSUE THREAD

**Issue by itsMichaelBates** [heroku/heroku-buildpack-python#788]
Looking at https://github.com/heroku/heroku-buildpack-python/blob/master/bin/compile it looks like the `pipenv` step is done before the `geo-libs` step is done. This causes problems when trying to install the Python `gdal` package (or any other python geo packages), because the gdal system package isn't installed.

It looks like the `pip-install` step is done after `geo-libs` is done, so it works if using a requirements.txt file, but not if using a Pipfile.

**Comment by CaseyFaist** [comment]
Hey! We will be deprecating the in-buildpack support for GDAL/GEOS in favor of using an external buildpack: https://github.com/heroku/heroku-geo-buildpack

see [this issue](https://github.com/heroku/heroku-buildpack-python/issues/852#issuecomment-536654273) for context on this decision 👍
