### ISSUE TITLE
Support for ortools

### ISSUE THREAD

**Issue by supriya-clutter** [heroku/heroku-buildpack-python#789]
When trying to run a python app with ortools on Heroku, I get the following error:

```File \"or.py\", line 2, in <module>\n    from ortools.constraint_solver import pywrapcp\nModuleNotFoundError: No module named 'ortools'```

I am setting up ortools in the post compile script:
```python -m pip install -U --user ortools```

Logs from the build:
```
-----> Running post-compile hook
Collecting ortools
  Downloading https://files.pythonhosted.org/packages/31/ea/7e085dc9add0875e235ac13723d4105977d1d5efaef6423454ef72c67b29/ortools-6.9.5824-cp36-cp36m-manylinux1_x86_64.whl (23.7MB)
Collecting six>=1.10 (from ortools)
  Downloading https://files.pythonhosted.org/packages/67/4b/141a581104b1f6397bfa78ac9d43d8ad29a7ca43ea90a2d863fe3056e86a/six-1.11.0-py2.py3-none-any.whl
Collecting protobuf>=3.6.1 (from ortools)
  Downloading https://files.pythonhosted.org/packages/c2/f9/28787754923612ca9bfdffc588daa05580ed70698add063a5629d1a4209d/protobuf-3.6.1-cp36-cp36m-manylinux1_x86_64.whl (1.1MB)
Collecting setuptools (from protobuf>=3.6.1->ortools)
  Downloading https://files.pythonhosted.org/packages/e7/16/da8cb8046149d50940c6110310983abb359bbb8cbc3539e6bef95c29428a/setuptools-40.6.2-py2.py3-none-any.whl (573kB)
Installing collected packages: six, setuptools, protobuf, ortools
Successfully installed ortools-6.9.5824 protobuf-3.6.1 setuptools-40.6.2 six-1.11.0
```
What else am I missing ?

**Comment by CaseyFaist** [comment]
Hi there - 

I'm sorry to hear you are having issues. This might be something we can better help you with if you reach out via support ticket, as I'd need more context around your specific app to begin to diagnose the problem. Closing, but feel free to open a support ticket if you are still having this issue.
