### ISSUE TITLE
Build failed at smtplib and email.mime.text

### ISSUE THREAD

**Issue by redallica** [heroku/heroku-buildpack-python#790]
Hi,

I'm trying to buils heroku app from the github repository, and I'm getting the following:

-----> Python app detected
 !     Python has released a security update! Please consider upgrading to python-3.6.7
       Learn More: https://devcenter.heroku.com/articles/python-runtimes
-----> Installing python-3.6.5
-----> Installing pip
-----> Installing SQLite3
-----> Installing requirements with pip
       Collecting numpy (from -r /tmp/build_d129ff7eb328bc286018cee3574acc22/requirements.txt (line 1))
         Downloading https://files.pythonhosted.org/packages/ff/7f/9d804d2348471c67a7d8b5f84f9bc59fd1cefa148986f2b74552f8573555/numpy-1.15.4-cp36-cp36m-manylinux1_x86_64.whl (13.9MB)
       Collecting pandas (from -r /tmp/build_d129ff7eb328bc286018cee3574acc22/requirements.txt (line 2))
         Downloading https://files.pythonhosted.org/packages/e1/d8/feeb346d41f181e83fba45224ab14a8d8af019b48af742e047f3845d8cff/pandas-0.23.4-cp36-cp36m-manylinux1_x86_64.whl (8.9MB)
       Collecting talib (from -r /tmp/build_d129ff7eb328bc286018cee3574acc22/requirements.txt (line 3))
         Downloading https://files.pythonhosted.org/packages/1a/80/3492aa3065d7d81a6c51db78920108f84fbe19c4e2740f6bbb83d42f77a4/talib-0.1.1.tar.gz
       Collecting ccxt (from -r /tmp/build_d129ff7eb328bc286018cee3574acc22/requirements.txt (line 4))
         Downloading https://files.pythonhosted.org/packages/29/33/67a2b7ae113b163f970a6955a889cc1dcf701faeffcf108a227926332c3a/ccxt-1.17.551-py2.py3-none-any.whl (1.1MB)
       Collecting email.mime.text (from -r /tmp/build_d129ff7eb328bc286018cee3574acc22/requirements.txt (line 5))
         Could not find a version that satisfies the requirement email.mime.text (from -r /tmp/build_d129ff7eb328bc286018cee3574acc22/requirements.txt (line 5)) (from versions: )
       No matching distribution found for email.mime.text (from -r /tmp/build_d129ff7eb328bc286018cee3574acc22/requirements.txt (line 5))
 !     Push rejected, failed to compile Python app.
 !     Push failed

In the requirements.txt file. I have:
numpy
pandas
talib
ccxt
email.mime.text
smtplib
email.mime.multipart

What am I doing wrong ? it seems it can not find a distribution for all related email packages
I guess there will be an issue with email.mime.multipart as well

**Comment by merwok** [comment]
email is a package in the standard library.  No third-party dependency is needed to access it.

**Comment by CaseyFaist** [comment]
Merwok is correct 👍 closing issue

**Comment by varchasa** [comment]
I have to deploy my application on heroku for this I need version of smtplib. I have tried many versions but still not working. In the python file of smtplib version 8.8.4 is present but on heroku platform this is also not working. 
I have searched on internet many times and by many ways but was unable to find. Can you help me regarding this that what is the current version of smtplib

**Comment by merwok** [comment]
Again, smtplib is part of the standard library, heroku does not remove it (just tested with a Python 3.8 app), so it’s hard to understand what is your problem.

**Comment by varchasa** [comment]
[
![heroku](https://user-images.githubusercontent.com/43700017/94332199-8c578000-fff0-11ea-9b03-15a8028aacf8.jpg)
](url)

Sir I have attatched the file. In this you can see that the distribution of smtplib is not found. And if I am not including it in the requirements.txt file the application in not performing it's task.

**Comment by merwok** [comment]
That does not seem right.  smtplib is not a package on PyPI, it is a module in the standard library.

> And if I am not including it in the requirements.txt file the application in not performing [its] task.

Can you show error message about that?

**Comment by edmorley** [comment]
@varchasa Hi! The build log screenshot you included shows that your `requirements.txt` currently has the line `smtplib==3.8` which should not be there, since that's not a valid package on PyPI:
https://pypi.org/search/?q=smtplib

The `smtplib` module is part of the Python stdlib, so should not be listed in `requirements.txt`, since it can be used with just the standard Python install. See:
https://docs.python.org/3/library/smtplib.html

Also I'd recommend always opening a new GItHub issue if you believe you've found a bug in the future. Comments on a closed issue are likely to not be seen, and it's best to keep a GitHub issue about just one topic.
