### ISSUE TITLE
Cannot Choose Requirements File

### ISSUE THREAD

**Issue by thekashifmalik** [heroku/heroku-buildpack-python#80]
Many projects have multiple individual deployments, such as dev, staging and production. Often these environments have different requirements.

Breaking up these requirements is easy to do locally but since the Heroku buildpack always uses the root _requirements.txt_ it's hard to do on Heroku, even with cascading.

Is there a way to do this? If not, is this something we could add?

**Comment by blueyed** [comment]
> Oh okay, cool! So then it should be totally possible to symlink to requirements.txt using that hook. 

It (probably) only works when specifying the build-pack explicitly, otherwise the python buildpack will not detect the it in the first place.

**Comment by edwardotis** [comment]
Hi, what happened to the symlink? Can I use my separate environment requirements files with heroku yet?

https://discussion.heroku.com/t/how-to-handle-requirements-txt-for-a-staging-and-production-environment-on-heroku/295
