### ISSUE TITLE
pip 9.0.2 can break Pipenv builds - need to change pip version

### ISSUE THREAD

**Issue by JeremyLoy** [heroku/heroku-buildpack-python#804]
[see this issue for more details](https://github.com/pypa/pip/issues/5079)

It is fixed in 9.0.3, or alternatively downgrade to 9.0.1

**Comment by JeremyLoy** [comment]
Any update on this?

**Comment by David-OConnor** [comment]
Looking for a fix on this as well. Appears not to work with `manylinux2010` wheels.

**Comment by JeremyLoy** [comment]
I believe this was fixed by #919 - can someone verify? A simple hello world using pipenv should suffice

**Comment by CaseyFaist** [comment]
Not sure I understand how the linked issue relates to Pipenv. Closing, if issues are still present after the pip update please reopen with a reproduce case I can test/develop against 👍

**Comment by vincentwoo** [comment]
Even today, pipenv seems to install a very old pip:

```
remote: -----> Installing python-3.9.0
remote: -----> Installing pip 9.0.2, setuptools 47.1.1 and wheel 0.34.2
remote: -----> Installing dependencies with Pipenv 2018.5.18…
```

How can we upgrade pip in pipenv?
