### ISSUE TITLE
Support for PIPENV_PIPFILE to set path to Pipfile from ENV vars

### ISSUE THREAD

**Issue by SimKennedy** [heroku/heroku-buildpack-python#830]
pipenv [supports custom Pipfile locations via the env var PIPENV_PIPFILE](https://docs.pipenv.org/en/latest/advanced/#pipenv.environments.PIPENV_PIPFILE)
It would be very useful if Heroku supported this.

Our use case:
We have a large Django monorepo that we deploy to multiple Heroku apps to have a single codebase but allow multiple apps and configurations to be run.
Some apps have conflicting requirements though so we it would be great to specify the Pipfile to use from the Heroku env vars.
Currently we have to have separate branches for each heroku app with each Pipfile and Pipfile.lock which is hard to maintain.

**Comment by JakeUrban** [comment]
I also have this use case. Multiple apps in a single repo with different requirements for each. This is really a must-have in order for us to use Heroku.

**Comment by CaseyFaist** [comment]
Unfortunately, we are not currently prioritizing pipenv support feature requests. See #786 for more info.
