### ISSUE TITLE
Python 2 runtime issue

### ISSUE THREAD

**Issue by HeatMint** [heroku/heroku-buildpack-python#849]
[Heroku runtime](https://devcenter.heroku.com/articles/python-support#supported-runtimes)
As this link suggested, python 2.7.16 should be supported in heroku.
How ever, in this issue, and also my account, python 2.7.16 is not supported
[](https://github.com/heroku/heroku-buildpack-python/issues/735)

**Comment by HeatMint** [comment]
[This issue](https://github.com/heroku/heroku-buildpack-python/issues/735)

**Comment by CaseyFaist** [comment]
Hey! This is probably best dealt with by opening a ticket with Heroku on the application in question, as I'll need more details on your specific application and the issues you're seeing.

Heroku 18 has had 2.7.16 for a while now and I'm unable to reproduce an issue deploying with 2.7.16 runtime on Heroku 18 (by specifying `python-2.7.16` in the `runtime.txt`), but I'd be happy to work with you if you submit a reproduce case via Heroku Support 👍
