### ISSUE TITLE
Support for vendoring our own versions of GEO libraries

### ISSUE THREAD

**Issue by thclark** [heroku/heroku-buildpack-python#852]
At present, the buildpack, when installing GEO libraries, uses the ``${VENDOR_URL}`` environment variable to determine which libraries to install.

Those of us who need to build our own geo libraries can't do so in the build phase, because gdal alone takes c.1hr to build, and so we hit Heroku's timeout. We have to vendor our own libraries.

This would be extremely simple if the geo libraries were installed from ``${GEO_VENDOR_URL}``, an envvar we could set (whose default value is otherwise the same as ``${VENDOR_URL}``). At present however, because all the vendored libraries are using the same origin, it's a much more complicated job involving either an additional/alternative buildpack or at least a postbuild hook.

Here's all the different uses of ``VENDOR_URL`` in the buildpack:
![Screenshot 2019-09-26 at 14 36 23](https://user-images.githubusercontent.com/7223170/65693647-8d1ba600-e06c-11e9-8b4e-b39de85a0bc3.png)

I believe the modification would be made [here](https://github.com/heroku/heroku-buildpack-python/blob/ff42f318a06b80873331bdd62a7e335573a35534/bin/compile#L42) and is as simple as:
```
VENDOR_URL="https://lang-python.s3.amazonaws.com/$STACK"
if [[ -n ${BUILDPACK_VENDOR_URL:-} ]]; then
    VENDOR_URL="$BUILDPACK_VENDOR_URL"
fi

GEO_VENDOR_URL="$VENDOR_URL"
if [[ -n ${GEO_VENDOR_URL:-} ]]; then
    VENDOR_URL="$GEO_VENDOR_URL"
fi

export GEO_VENDOR_URL
export VENDOR_URL
```

(ofc the references to it in the build steps would also need updating).

Use cases:
- you need plugins against which default vendored versions aren't linked, like Google's libkml
- you need a different version of GDAL to the default vendored version (at the time of writing, latest is 2.4.1, vendored is 2.2.1)

**Would you accept a pull request for this, which updated the compile script, the build steps, and the docs accordingly?**

**Comment by CaseyFaist** [comment]
Hi @thclark!

We will be deprecating support for in-buildpack gdal/geos installation, so while I appreciate the issue documentation and the offer to PR  ❤️ I won't be able to accept a pull request on this issue.

In the future, GEOS/GDAL support will be vendored by adding a third-party buildpack (will link when I have one to share) to your [application](https://devcenter.heroku.com/articles/using-multiple-buildpacks-for-an-app). This approach was chosen because this issue affects more than just Python users - applications regardless of language may need to vendor these libraries.

For anyone using the current process, there will be a migration period after this buildpack is released to ensure we get feedback and give time to migrate. A deprecation warning will appear on GDAL install (using the current in-buildpack feature) when the migration period begins with details and docs, and the period will likely be 2-3 months.

**Comment by thclark** [comment]
Hi @CaseyFaist good plan, very sensible (and less work for me, so no probs!).

Building GDAL has became a complete PITA for me, due to heroku's short build timeouts and the difficulty of doing the third party vendoring I describe above, so I'm actually in the process of leaving heroku as a result. But...
- IF the new geo buildpack is coming withing (say) 6 weeks
- AND it's planned to use a version linked against google's libkml, instead of the default (glaringly incapable) kml library
THEN I'd be quite keen to just stay around.
Do you know (or know who would know) about these things?

**Comment by CaseyFaist** [comment]
I'll let @KevinBrolly (who's doing the heavy lifting on this new buildpack) answer the timeline question definitely, but my understanding is that the goal is within 6 weeks

As to the linked version, this is not currently planned but I'm happy to look into it - I'll create an issue to follow once I have a github link to share to the new buildpack 👍

**Comment by thclark** [comment]
Oh my god @CaseyFaist you'd be my new heroine. Shoving this all onto GCP is so agonising...

**Comment by KevinBrolly** [comment]
Hey @thclark 👋 

The new Geo buildpack is here - https://github.com/heroku/heroku-geo-buildpack

Currently it does not include support for vendoring your own libraries, but this could be easily added if useful, I can also expand on the instructions for building new binaries. Similarly it is also not linked to google's libkml currently, but this could be added also.

It would be great if you would come over to the other repo and give the buildpack a try, and raise any issues you find.

Thanks.

**Comment by thclark** [comment]
Hi @KevinBrolly Great! I'll head over there. No need to vendor own libraries if libkml is installed already, so I'll create an issue over there for that, linked to this!
