### ISSUE TITLE
pre/post-compile hooks w/o using custom buildpacks

### ISSUE THREAD

**Issue by aljosa** [heroku/heroku-buildpack-python#87]
would you be open to add support for something like:
$ heroku config:set BUILDPACK_PRE_COMPILE=custom_script.sh

which would enable custom actions on build time (like using "django-admin.py collectstatic" w/ use-env-compile labs feature) where $BUILDPACK_PRE_COMPILE script must exists in git repo.

this would remove requirement to create custom buildpack for simple stuff like mentioned collectstatic problem.

**Comment by alexkahn** [comment]
Just wanted to clarify, will this honor a python shebang like `/usr/bin/env python` or must it be `/app/.heroku/python/bin/python` (the result of running `which python` against my app dyno)? Just in case - is the location of `which python` consistent across dynos assuming they're on the same stack?

**Comment by kennethreitz** [comment]
@alexkahn `env python` should work perfectly fine

**Comment by alexkahn** [comment]
Thanks!
