### ISSUE TITLE
ln: failed to create symbolic link '/tmp/build/.heroku/python': No such file or directory

### ISSUE THREAD

**Issue by wckao** [heroku/heroku-buildpack-python#873]
https://github.com/heroku/heroku-buildpack-python/commit/05e29c74bcc4b73a0ab2690f767a53bfdbd5de13#r35419023

**Comment by wckao** [comment]
[deploy_log.txt](https://github.com/heroku/heroku-buildpack-python/files/3705539/deploy_log.txt)

Here is the complete log

**Comment by jacobwegner** [comment]
I think this recent change is causing the failure:

https://github.com/heroku/heroku-buildpack-python/blob/1721fa3703ca85afecb09656299866c036461a66/bin/compile#L108

```patch
-mkdir -p "BUILD_DIR/.heroku"
+mkdir -p "$BUILD_DIR/.heroku"
```

**Comment by cw-intellineers** [comment]
I have the same issue. Will there be a hotfix in the near future? We are unable to deploy our changes otherwise.

**Comment by vinicyusmacedo** [comment]
Hey, I would like to grab this issue.
