### ISSUE TITLE
Support for Python 3.7.5 and 3.8

### ISSUE THREAD

**Issue by codeinteger6** [heroku/heroku-buildpack-python#884]
Hi, does anyone here have any idea when these two versions will be supported on Heroku? The last one (3.7.4) took quite a while.

**Comment by CaseyFaist** [comment]
Hey! Yep, last time it took a while to debug an issue we had with the version of get-pip we were on - resolved in #840. 

I'm still low this time, but this should be released on Monday - you can follow #885 and access it early on the Master branch once that pr is merged, though 👍
