### ISSUE TITLE
Tensorflow 2.0 not available

### ISSUE THREAD

**Issue by aghasemi** [heroku/heroku-buildpack-python#914]
Hi,
Tensorflow is only available in the Heroku buildpack up to the 1.14 stable and 2.0.0b1 versions, whereas the latest stable release now is 2.1.0. Moreover, there is no `tensorflow-cpu` and `tensorflow-gpu` is too big (>500MB) for a free Dyno. Therefore, for example one deploy an app that uses [keras-ocr](https://github.com/faustomorales/keras-ocr), whereas such app works flawlessly on the local machine. 

Is there a solution to that?

Many thanks

**Comment by CaseyFaist** [comment]
Hi there - for more information about Heroku resources and sizing, you can check out our page https://www.heroku.com/pricing. Heroku does not actually provide GPU resources, which would potentially cause some issues to a package looking for GPU bindings like `tensorflow-gpu`. We're a best-in-class web application platform as a service, and maybe not the best thing for deep learning training applications (although you can deploy your trained and compiled models as API endpoints or as parts of your application).
