### ISSUE TITLE
Check for Python version removed 

### ISSUE THREAD

**Issue by BRONSOLO** [heroku/heroku-buildpack-python#916]
@CaseyFaist I see that the`python_sqlite3_check` call was removed in [this](https://github.com/heroku/heroku-buildpack-python/commit/f0f3463658b3707ff19509e434e9930df726f4ae#diff-a5204ad59e8b0eaf8d0c3ecd8ba9d1b5) commit. 

I'm wondering if you could comment on why this was removed / suggest an approach that should be used so that **sqlite3** is installed _only_ for **Python 2.7.15+** and **Python 3.6.6+**

Thanks so much!

**Comment by edmorley** [comment]
Hi! We'll be removing the sqlite install step soon for all builds, at which point the check will no longer be needed anyway. Closing this out for now, since removing sqlite 3 is in our internal queue.
