### ISSUE TITLE
Pipenv is effectively dead - please support Poetry

### ISSUE THREAD

**Issue by JeremyLoy** [heroku/heroku-buildpack-python#921]
See [this issue on Pypa](https://github.com/pypa/packaging.python.org/issues/701) for references. The maintainers are silent. No official release has been made for over a year. No changes to master in 4 months.

In contrast, Poetry has made 6 releases in the past 3 months, and has a habit of resolving issues and PRs at an acceptable rate.

There are already some open issues regarding support for poetry, like #796, however they might need to be updated as Poetry was in beta at the time.

**Comment by adamkgoldfarb** [comment]
A note of support here: I am pausing on adopting poetry mainly because Heroku doesn't formally support it. I've been looking at [dephell](https://github.com/dephell/dephell) to move to plain old requirements.txt files, but poetry seems like a better replacement at the moment. Some guidance on plans to integrate support for poetry (or lack thereof) would be nice. AFAIK, @CaseyFaist has signaled intentions to do so-- or accept some pull requests-- in the past.

**Comment by JeremyLoy** [comment]
@adamkgoldfarb although not ideal, Poetry allows you to export as a `requirements.txt`. You could use this as a stopgap

https://python-poetry.org/docs/cli/#export

**Comment by rafalkrupinski** [comment]
There's a standard(?) way that pip uses to install poetry project from a git repo - pyproject.toml. Once it contains
```toml
[build-system]
build-backend = "poetry.masonry.api"
requires = ["poetry>=0.12"]
```
whatever build system is mentioned, it's used. Perhaps that path would suit heroku and the users?

**Comment by amureki** [comment]
@adamkgoldfarb we are able to use poetry in Heroku via something like:
https://github.com/python-poetry/poetry/issues/403#issuecomment-568180773
(as other commenters mentioned, we just need to export lock data to `requirements.txt`, so Heroku can take it.
But yeah, proper Heroku support of it would be nice.

**Comment by adamkgoldfarb** [comment]
Thanks @amureki @rafalkrupinski @JeremyLoy --I'll take these all into account in determining next steps. Might just default to requirements.txt from here on out, as the ecosystem seems not to have been eager to rush into anything else. 

Sidenote: I'd love to stay with pipenv and understand the relevance to Heroku in particular, so also understand the moving pieces that make change in this area harder. Still hoping that pipenv finds a long-term solution but I've held my breath a bit too long on this one.

**Comment by CaseyFaist** [comment]
Closing this issue to keep the conversation in one place, but see update in #796 - the first of three PRs submitted to bring Poetry support into the buildpack has been accepted. Can't offer a timeline unfortunately, but support for this tooling has been prioritized.
