### ISSUE TITLE
Automatically detect test command when using Heroku CI (bin/test support)

### ISSUE THREAD

**Issue by CaseyFaist** [heroku/heroku-buildpack-python#924]
Currently the Python Buildpack does not automatically detect tests run during Heroku CI: https://devcenter.heroku.com/articles/heroku-ci#python

- [ ] Should it?
- [ ] Which framework(s) should it support
- [ ] What would maintenance and forward compatibility look like

**Comment by edmorley** [comment]
See also recent discussion on:
https://github.com/heroku/heroku-buildpack-python/pull/982#issuecomment-815645795

**Comment by edmorley** [comment]
Closing this out for the reasons in https://github.com/heroku/heroku-buildpack-python/pull/982#issuecomment-815645795 - we can always revisit in the future if needed.
