### ISSUE TITLE
Only export BUILD_DIR and CACHE_DIR once on compile

### ISSUE THREAD

**Issue by CaseyFaist** [heroku/heroku-buildpack-python#928]
Currently, we export BUILD_DIR and CACHE_DIR as build vars twice.

Once on `bin/compile` line 36:
https://github.com/heroku/heroku-buildpack-python/blob/master/bin/compile#L35-L36

And then again on line 141:
https://github.com/heroku/heroku-buildpack-python/blob/master/bin/compile#L140-L141

- [ ] Add test for presence of BUILD_DIR and CACHE_DIR on compile
- [ ] Remove second instance of BUILD_DIR and CACHE_DIR

**Comment by edmorley** [comment]
This will be resolved as part of a future buildpack refactor (post CNB).
