### ISSUE TITLE
Python Version via .python-version

### ISSUE THREAD

**Issue by jamesward** [heroku/heroku-buildpack-python#932]
It doesn't seem like there is a standard way for a project to specify it's Python version, but I'm using https://github.com/pyenv/pyenv and it does this via a `.python-version` file.  Is adding support for reading the version from that file something that would be considered?

**Comment by CaseyFaist** [comment]
Absolutely! I can't promise when work will start on this feature specifically, but support for Poetry and using up to date python conventions is very much on my mind.

**Comment by joshfriend** [comment]
@jamesward have you discovered Heroku's [`runtime.txt`](https://devcenter.heroku.com/articles/python-runtimes#selecting-a-runtime) file yet?

There are community buildpacks for pyenv, but pyenv compiles python from source (lengthening your slug build time) whereas this buildpack has prebuilt python binaries for common versions.

Ideally the `runtime.txt` and `.python-version` files would be treated as interchangeable by this buildpack, since the format and names of the python versions used are _almost_ identical.

**Comment by jamesward** [comment]
I have seen that but it'd be nice to be able to specify the python version in just one place. :)

**Comment by abitrolly** [comment]
[`pyproject.toml`](https://snarky.ca/what-the-heck-is-pyproject-toml/) can also be used to avoid yet another file.

There is a [`requires-python`](https://www.python.org/dev/peps/pep-0621/#requires-python) directive, but it is designed to describe [all Python versions](https://packaging.python.org/specifications/core-metadata/#requires-python) a package is compatible with. For the `buildpack`, however, it may beneficial to set specific version in  `[tool.buildpack]`

```
[tool.buildpack]
python = "3.8.x"
```

**Comment by edmorley** [comment]
I'd love to be able to add support for this in a vendor-independent manner.

Perhaps we can use `requires-python` and either:
(a) insist it specifies a single version (or at least using only a fairly easy to manually parse version specifier),
(b) resolve the version range ourselves (similar to what the Node buildpack does), though we'll then have a pre-python-install-time dependency on `packaging` or whichever package it is

**Comment by edmorley** [comment]
I've written up my latest thoughts on ways to specify Python version for Heroku apps, here:
https://github.com/heroku/heroku-buildpack-python/issues/913#issuecomment-1031468659

**Comment by edmorley** [comment]
Sorry for the delay in getting to this! 

Our focus has been on creating our next generation buildpacks, Cloud Native Buildpacks (aka CNBs), which include support for new features like this one. (For more details on our CNBs see [this overview](https://github.com/heroku/buildpacks) and to follow along with the in-development Python CNB's progress see the [heroku/buildpacks-python](https://github.com/heroku/buildpacks-python) repo.)

However, as of #1664 this (non-CNB, aka "classic") buildpack now supports the `.python-version` file too.

Notably, the `.python-version` file optionally supports specifying a Python version using only the major version (such as `3.13`), which means that your app will use the latest Python patch version each time it builds - saving you from having to manually track new security updates.

See:
- https://github.com/heroku/heroku-buildpack-python/releases/tag/v261
- https://devcenter.heroku.com/changelog-items/3005
- https://devcenter.heroku.com/articles/python-runtimes
