### ISSUE TITLE
Cache buildpack version number

### ISSUE THREAD

**Issue by CaseyFaist** [heroku/heroku-buildpack-python#936]
An interesting idea from the [ruby buildpack](https://github.com/heroku/heroku-buildpack-ruby) is to cache the release number of the buildpack - this allows Heroku's support team (and me) to zero in on broken changes more quickly.

This would involve some process changes - currently changelog is updated after release, so that changelog isn't pointing to a release that doesn't exist here on Github. Need to chew on this chicken and egg problem a bit more - and open to suggestions 😄

**Comment by edmorley** [comment]
Tracking internally as part of overall observability work.
