### ISSUE TITLE
New deployments show caching error

### ISSUE THREAD

**Issue by jkutner** [heroku/heroku-buildpack-python#941]
Deploying the [python-getting-started app](https://github.com/heroku/python-getting-started) for the first time (and any other python app for the first time it seems), emits this meesage:

```
remote: -----> Python app detected
remote: cp: cannot create regular file '/app/tmp/cache/.heroku/requirements.txt': No such file or directory
```

**Comment by arpitr07** [comment]
Experienced the exact same issue today while deploying an app.
