### ISSUE TITLE
heroku failed to build on a dependency not specified in hashed requirements.txt

### ISSUE THREAD

**Issue by yunti** [heroku/heroku-buildpack-python#947]
I've used poetry to export a hashed requirement.txt (mimicking the poetry lockfile). 
It's not clear at the moment if heroku uses the requirement.txt file by default if the pyproject.toml is also there, so for now I added the pyproject.toml to .gitignore to make sure it uses the fully resolved requirement.txt generated by poetry. 
When I push to heroku to build, it fails with the below error:

```python
Collecting python3-openid>=3.0.8
remote:        ERROR: In --require-hashes mode, all requirements must have their versions pinned with ==. These do not:
remote:            python3-openid>=3.0.8 from https://files.pythonhosted.org/packages/bd/de/52c5699f52dcee3037db587196dcaf63ffedf5fbeba3183afe9b21a3a89f/python3_openid-3.1.0-py3-none-any.whl#sha256=0086da6b6ef3161cfe50fb1ee5cceaf2cda1700019fda03c2c5c440ca6abe4fa (from django-allauth==0.37.1->-r /tmp/build_b096feb1aad93867febc1ecfe3e7e8ad/requirements.txt (line 19))
```

From the requirements file it seems to be having a problem with
```python
django-allauth==0.37.1
--hash=sha256:02175aa1c2ddfd935a54011d1196d70c976647fc46f603f8b8758fc395b9d277
```

however that seems to be fully pinned.
The only open-id dependency in the requirement.txt file is the below, so I'm not sure where the error is coming from. It seems like heroku may be still fetching package sub-dependencies, which is shouldn't need to as these are all in the file.

```python
python-openid==2.2.5 \
--hash=sha256:92c51c3ecec846cbec4aeff11f9ff47303d4a63f93b0e6ac0ec02a091fed70ef \
--hash=sha256:c2d133e47e0a7705c9272eef00d7a09c174f5bf17a127fed8e2c6499556cc782
```

**Comment by edmorley** [comment]
@yunti Hi! Sorry for the delayed reply. Issues here aren't as actively monitored, so for support issues we recommend using https://help.heroku.com instead.

Looking at that error, it doesn't appear to be Heroku-specific. This same error would appear locally (same Python version/... caveats apply).

It seems there were conflicting dependencies. Your requirements file specified `python-openid==2.2.5` but `django-allauth==0.37.1` has a dependency on `python3-openid>=3.0.8`:
https://github.com/pennersr/django-allauth/blob/0.37.1/setup.py#L106-L110

Pip (at least until they added the new dependency resolver) has non-deterministic behaviour around conflicting dependencies. Newer pip would fail saying that the combination of dependencies specified are not valid.

To resolve this, the `python-openid==2.2.5` dependency needs updating to be `==3.0.8` (or any newer 3.x version).
