### ISSUE TITLE
Using an icon on flask doesn't work

### ISSUE THREAD

**Issue by Gionson13** [heroku/heroku-buildpack-python#976]
I'm trying to add an icon to my website using:
```python
@app.route('/favicon.ico')
def favicon():
    return url_for('static', filename='images/favicon.ico')
```

and when i'm using the "flask generated ip" hosted on my pc it works for all the pages, even the 404 pages, but when i host it on heroku it shows only on the ' / ' page.

I also tried 
```html
<link rel="shortcut icon" href="{{ url_for('static', filename='images/favicon.ico') }}">
```
and
```python
@app.route('/favicon.ico')
def favicon():
    return send_from_directory(os.path.join(app.root_path, 'static'),
                               'images/favicon.ico', mimetype='image/vnd.microsoft.icon')
```
but I got the same result.

How can I fix it?

**Comment by edmorley** [comment]
@Gionson13 Hi! For app-specific issues (as opposed to buildpack bugs or feature requests), I'd recommend opening a support ticket at https://help.heroku.com . That said for this issue it might be on the edge of what support can help with (https://www.heroku.com/policy/support).

Without seeing more of the code it's hard to debug the issue. I would recommend looking at what differences exist between your local development environment and production. For example locally `DEBUG` might be enabled and the Flask devserver used, vs production where DEBUG shouldn't be enabled and `gunicorn` used to serve. I'm less familiar with Flask, but I know for Djan go there are significant differences in static file handling when using the devserver for example.

I would also check the app logs ([docs](https://devcenter.heroku.com/articles/logging#view-logs)) to see if there are any clues there.

Good luck! :-)

**Comment by edmorley** [comment]
Closing since this is a support issue. If you are still having this problem please open a ticket at https://help.heroku.com/ :-)
